### PR TITLE
Split personsLogic for 1) persons scene, 2) cohorts drawer

### LINKED ISSUE #7157: Persons tab retains static cohort list
## Bug description

We use a static cohort to define beta users, if I click into this cohort, then go to the persons tab, the persons tab will only show users from that static cohort (even if I search).

## Expected behavior

The persons tab shows all persons, and I can search for users outside the static cohort.

## How to reproduce

1. Create a static cohort
2. View the static cohort matched users
3. Click the persons tab
4. Only users in the static cohort are shown, even when you search

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [x] self-hosted PostHog (Postgres-based, legacy), version/commit: e0fe499a0544a9a6ba914efcb1e58ed1fe1e3422

## Additional context

This caused confusion for users searching for users and they thought PostHog was broken and questioned the integrity of our data.

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Fixes https://github.com/PostHog/posthog/issues/7157
- The persons table in the cohort drawer was interfering with the persons table on the persons page.
- Also fixes this
image

## How did you test this code?

- Ran locally, saw the fixes fixed the bug.

### CODE REVIEW

File: frontend/src/scenes/persons/personsLogic.ts [hunk 1]
```diff
@@ -18,8 +18,15 @@ interface PersonPaginatedResponse {
...
-export const personsLogic = kea<personsLogicType<PersonPaginatedResponse>>({
-    path: ['scenes', 'persons', 'personsLogic'],
+export interface PersonLogicProps {
+    cohort?: number | 'new' | 'personsModalNew'
+    syncWithUrl?: boolean
+}
+
+export const personsLogic = kea<personsLogicType<PersonLogicProps, PersonPaginatedResponse>>({
+    props: {} as PersonLogicProps,
+    key: (props) => (props.cohort ? `cohort_${props.cohort}` : props.syncWithUrl ? 'scene' : 'default'),
```
Comment (Twixes) [inline frontend/src/scenes/persons/personsLogic.ts:28]: Is there a case were we actually want `default`? If not, then maybe it should throw an error to avoid inconsistencies like the one fixed by this PR

Comment (mariusandra) [reply frontend/src/scenes/persons/personsLogic.ts]: sure

**Review by Twixes — APPROVED** [review]
