### PR TITLE
fix: allow quesitons with IDs to be reordered after launch

### LINKED ISSUE #27200: Surveys: Wrong graph series after changing question order
## Bug description

related customer ticket: https://posthoghelp.zendesk.com/agent/tickets/22201

~After changing the order of the questions in a survey, the graphs in the results seems to mix-up answers from different questions~

At surveys, we rely on the question index in the array to determine which question we're showing. We're sort of using it as an `id`.

That means it must remain stable after launching the survey, otherwise the answers will be messed up in the data.

[We did a band-aid fix](https://github.com/PostHog/posthog/pull/27565) to prevent re-ordering after launching a survey.

So, when we have the time, we should update our BE schema to store the questions relying on an ID instead of relying on their position in the array. This way we can again support question re-ordering after launching a survey.

### Some caveats

[Questions are currently stored as a JSON field in the DB](https://github.com/PostHog/posthog/blob/fix/flagPropertyErrors-return-undefined/posthog/models/feedback/survey.py#L80).

So, if we update it  to use an ID for every question, it means a breaking change in the database. So we'll have to support **both versions** indefinitely. Unless we come up with a better plan.

If this ID is added, we need to make sure that, on our logic, we support both survey's versions.

### PR DESCRIPTION
**Pull request by lucasheriques**
## Problem

closes https://github.com/PostHog/posthog/issues/27200

## Changes

allow surveys with question ids to be reordered even if they are not drafts

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

yes

## How did you test this code?

unit tests

### CODE REVIEW

**Review by ioannisj — APPROVED** [review]
LGTM!

File: frontend/src/scenes/surveys/SurveyDragHandle.tsx [hunk 1]
```diff
@@ -4,6 +4,7 @@ import { SortableDragIcon } from 'lib/lemon-ui/icons'
 interface SurveyDragHandleProps {
     listeners: DraggableSyntheticListeners | undefined
     isDraftSurvey: boolean
+    allQuestionsHaveIds: boolean
```
Comment (marandaneto) [inline frontend/src/scenes/surveys/SurveyDragHandle.tsx:7]: do we actually need this? we ran the script adding IDs, so I don't see how this is ever returning false

File: frontend/src/scenes/surveys/SurveyDragHandle.tsx [hunk 2]
```diff
@@ -17,8 +18,13 @@ export function SurveyDragHandle({
...
     isDraftSurvey,
     hasMultipleQuestions,
+    allQuestionsHaveIds,
 }: SurveyDragHandleProps): JSX.Element | null {
-    if (!isDraftSurvey || !hasMultipleQuestions) {
+    if (!hasMultipleQuestions) {
+        return null
+    }
+
+    if (!allQuestionsHaveIds && !isDraftSurvey) {
```
Comment (marandaneto) [inline frontend/src/scenes/surveys/SurveyDragHandle.tsx:27]: `isDraftSurvey` should be removed from the conditions since now its allowed also for non draft surveys, right?

Comment (lucasheriques) [reply frontend/src/scenes/surveys/SurveyDragHandle.tsx:27]: i guess it's not really needed anymore, removed both

**Review by marandaneto — APPROVED** [review]
