### PR TITLE
Use flex-basis instead of percentage for funnel bar sizing

### LINKED ISSUE #5251: 100% funnel chart not taking up 100% height
## Bug description

The first funnel step is saying 100% but not taking up 100% of the bar.

image

## Expected behavior

Bar to fill 100%

## How to reproduce

1. https://app.posthog.com/insights?events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22math%22%3Anull%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22https%3A%2F%2Fapp.posthog.com%2Fsignup%22%2C%22operator%22%3A%22icontains%22%7D%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A%22user%20signed%20up%22%2C%22math%22%3Anull%2C%22name%22%3A%22user%20signed%20up%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%5D&display=FunnelViz&insight=FUNNELS&interval=day&date_from=-7d&funnel_viz_type=steps

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

### PR DESCRIPTION
**Pull request by samwinslow**
## Changes

Closes #5251. On Safari, bars that were supposed to fill 100% of the available space were not rendering properly because of differences in how flexbox is rendered on different browsers. This PR replaces percentage widths/heights with flex basis values.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

File: frontend/src/scenes/funnels/FunnelBarGraph.tsx [hunk 1]
```diff
@@ -323,7 +323,6 @@ export function FunnelBarGraph({ filters, dashboardItemId, color = 'white' }: Om
                             <div className="funnel-bar-wrapper">
                                 {Array.isArray(step.nested_breakdown) && step.nested_breakdown?.length ? (
                                     step.nested_breakdown.map((breakdown, index) => {
-                                        const conversionRate = calcPercentage(breakdown.count, basisStep.count)
```
Comment (paolodamico) [inline frontend/src/scenes/funnels/FunnelBarGraph.tsx:326]: Not sure about this change, aren't we breaking the conversion calculation when using breakdowns?

**Review by paolodamico — APPROVED** [review]
One comment on something I'm not sure about, but lgtm otherwise!

**Review by paolodamico — APPROVED** [review]
lgtm!
