### PR TITLE
fix: form validation to link-type surveys questions

### LINKED ISSUE #27812: Surveys: Changes are lost on save when editing a survey that contains errors
## Bug description
When editing a survey that contains errors (e.g link is not https) and clicking “Save”, the app redirects the user back and all unsaved changes to the survey are lost.

This makes it frustrating for users who invest significant time creating surveys, as they must recreate their work from scratch after encountering this type of error.

## How to reproduce

1. Edit an existing survey.
2. Add or edit a link question and enter a link with an invalid format (e.g http://www.google.com)
3. Click "Save"
4. Survey exits edit more, the following error is shown and changes are lost 

```
Update survey failed: Link must be a URL to resource with one of these schemes [https, mailto]
```

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables or https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

### PR DESCRIPTION
**Pull request by lucasheriques**
## Problem

Closes https://github.com/PostHog/posthog/issues/27812

adds form validation to surveys

## Changes

CleanShot 2025-02-15 at 03 04 12@2x

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

yes

## How did you test this code?

checked locally if form validation is working

### CODE REVIEW

File: frontend/src/scenes/surveys/surveyLogic.tsx [hunk 1]
```diff
@@ -1281,6 +1281,15 @@ export const surveyLogic = kea<surveyLogicType>([
                             question: !question.question && 'Please enter a question label.',
                         }
 
+                        if (question.type === SurveyQuestionType.Link) {
+                            if (!question.link?.startsWith('https://') && !question.link?.startsWith('mailto:')) {
```
Comment (marandaneto) [inline frontend/src/scenes/surveys/surveyLogic.tsx:1285]: should we rather try to create an instance of URL instead? a non https is still a valid URL.

File: frontend/src/scenes/surveys/surveyLogic.tsx [hunk 2]
```diff
@@ -1281,6 +1281,15 @@ export const surveyLogic = kea<surveyLogicType>([
                             question: !question.question && 'Please enter a question label.',
                         }
 
+                        if (question.type === SurveyQuestionType.Link) {
```
Comment (marandaneto) [inline frontend/src/scenes/surveys/surveyLogic.tsx:1284]: > they must recreate their work from scratch after encountering this type of error.

the `link` question is an example; I wonder if there are more validation types missing or if it was just this one.
Also see https://github.com/PostHog/posthog/issues/18614

File: frontend/src/scenes/surveys/surveyLogic.tsx (hunk 1 above)
Comment (lucasheriques) [reply frontend/src/scenes/surveys/surveyLogic.tsx:1285]: it's a [BE rule to only allow https:// or mailto](https://github.com/PostHog/posthog/blob/master/posthog/api/survey.py#L52)

File: frontend/src/scenes/surveys/surveyLogic.tsx (hunk 2 above)
Comment (lucasheriques) [reply frontend/src/scenes/surveys/surveyLogic.tsx:1284]: yeah I tested a bunch, but didn't see any other validations that failed silently on the BE instead of having it validated in the FE.

for https://github.com/PostHog/posthog/issues/18614, we're already scrolling to the correct section, so the last part that is missing is showing all errors on top of the form, which I'll work on next

File: frontend/src/scenes/surveys/surveyLogic.tsx (hunk 1 above)
Comment (marandaneto) [reply frontend/src/scenes/surveys/surveyLogic.tsx:1285]: Mmm ok, i still think we should create a url which validates if its a valid url, otherwise https://$&12/.89 is a "valid" but its not really

Comment (lucasheriques) [reply frontend/src/scenes/surveys/surveyLogic.tsx]: makes sense, added better validation here: https://github.com/PostHog/posthog/pull/28762/commits/97f1d56c8d7287d60ddfa1cca286b5eaf7297c9b

**Comment by marandaneto** [comment]
Lgtm

**Comment by lucasheriques** [comment]
> Lgtm

@marandaneto you forgot to approve

**Review by marandaneto — APPROVED** [review]
