### PR TITLE
Better Sessions (Deeplinking, filter matching, expand/collapse options, matching highlights)

### LINKED ISSUE #4820: Allow deeplinking to specific sessions, events & recordings in a person page.
Related to #4785 we need to be able to deeplink to:
1. A specific event in a specific session in a person page (where this event/session information comes from a funnel query).
2. A specific session recording for a specific person (see #4818 for API details).

Please review the full [product specs](https://docs.google.com/document/d/1S7fwha7cph-79YaPADfFKHILCnPmBgk4rqaMu-gPZ3g/edit#heading=h.w1yaw9nwtpu) for this. However it's worth noting that when we open a session/event or recording from this deeplink, we need to highlight the relevant portion to the user.

CC @mariusandra ready to assign

### LINKED ISSUE #4924: Session results stay dirty on empty filters
## Bug description

When removing the last filter in the sessions page, there is no way to apply the `[]` empty filter. Usually the user will see a `There are unapplied filters.` warning with an option to apply the new filters, however this doesn't show up because we get rid of the filter panel altogether. This shouldn't happen as there should be a way to return to listing **all** sessions.

https://user-images.githubusercontent.com/13460330/123861036-8d00a800-d8db-11eb-9b22-b4407ad85c86.mov

The below isn't showing when last filter is removed.

Screen Shot 2021-06-29 at 4 12 31 PM

## Expected behavior

When filters become empty, either...

1. the list of sessions should update automatically to show all sessions in that day
2. warning and action button to set new empty filter should be presented to user

## How to reproduce

1. Go to sessions page
2. Add a filter
3. Apply it
4. Remove that filter
5. Observe that session list doesn't update

## Environment

- [X] PostHog Cloud
- [X] self-hosted PostHog, version/commit: _please provide_

### PR DESCRIPTION
**Pull request by alexkim205**
## Changes

Closes #4820

~Looks like Li's (#4839) and my tickets both need backend changes to the `api/action/people` endpoint to attach associated sessions/events data to the payload.~

Keep a separate set of `sessionFilters` that is passed to the Sessions page via url.

### Some bugs I fixed on the way
- Persist backTo url even when switching between events/sessions tabs.
- Fixes #4924 bug where if you remove the last sessions filter, there's no way to apply empty filter state. Results always stay dirty.
- Add page header to sessions table in Persons pages to look similar to events table.
- Kea-fy local `useState` activeTab state and persist in URL
- Remove border right on expand icon column

## Some Context

_In no particular order_

- There is no real "sessions" model in the backend. We determine events that belong in a "session" with a [SessionFilter](https://github.com/PostHog/posthog/blob/100919537af4d0aac7cc3e763b88b341c722110e/posthog/models/filters/sessions_filter.py#L7-L7) defined by a date range and team id.
- Although we don't have session models, we have `global_session_id` unique identifiers which is just the distinct_id concatenated with the timestamp
- When you navigate to the sessions tab of a person, the `api/event/sessions` api is called initially to list all session instances. Events of sessions are only called when you expand the table session row.
- It's an expensive task to query for all events belonging to all sessions and then picking out only the events we're interested in.
- It seems we have some matching happening already in the backend #2954. I wonder if we can use this.

## Implementation A

**Frontend** 

1. Pass filter (containing dates, events, person's distinct_id) from person modal to person->sessions page via url search params.
2. Navigate to sessions page and set corresponding date. 
3. Call `api/event/session` endpoint (already does this) with filter from (1)
4. Receive payload from B2 below. If `highlighted_events` isn't empty expand that session and proceed to highlight events

**Backend**

1. Receive request from F3 above and find all the events that match the deeplink filter.
2. Populate new `highlighted_events` property in the payload and return.

Implementation B (Found Karl's code much later so chose this one)

1. Take advantage of Karl's work with returning `matching_events` in session filter.

## TODO

- [x] Fix some bugginess with filter passing
- [x] e2e testing the deeplink highlights the right sessions/events

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] Frontend/CSS is usable at 320px (iPhone SE) and decent at 360px (most phones)
- [ ] Breaking changes are backwards-compatible. Ensure old/new frontend requests work with new/old backends, and vice versa.

### CODE REVIEW

File: frontend/src/lib/utils.tsx [hunk 1]
```diff
@@ -29,6 +29,17 @@ export function uuid(): string {
...
+    return obj && Object.keys(obj).length === 0 && obj.constructor === Object
+}
+
+// Builds url with base + search params + hash params
+export function buildUrl(base: string, searchParams: Record<string, any>, hashParams: Record<string, any>): string {
+    const search = !isObjectEmpty(searchParams) ? `?${toParams(searchParams)}` : ''
+    const hash = !isObjectEmpty(hashParams) ? `#${toParams(hashParams)}` : ''
+    return `${base.replace(/\/$/, '')}${search}${hash}`
+}
+
```
Comment (mariusandra) [inline frontend/src/lib/utils.tsx:42]: It's better to reuse the `combineUrl` function exported by `kea-router` for this.

File: frontend/src/scenes/events/eventsTableLogic.js [hunk 2]
```diff
@@ -181,12 +181,19 @@ export const eventsTableLogic = kea({
...
         setProperties: () => {
-            return [router.values.location.pathname, values.propertiesForUrl, window.location.hash]
+            return [
+                router.values.location.pathname,
+                {
+                    ...router.values.searchParams,
+                    properties: values.properties,
+                },
+                window.location.hash,
+            ]
```
Comment (mariusandra) [inline frontend/src/scenes/events/eventsTableLogic.js:191]: If this makes `propertiesForUrl` unnecessary, we should remove it.

File: frontend/src/scenes/persons/personsLogic.ts [hunk 3]
```diff
@@ -12,7 +12,7 @@ interface PersonPaginatedResponse {
     results: PersonType[]
 }
 
-const FILTER_WHITELIST: string[] = ['is_identified', 'search', 'cohort']
+const FILTER_ALLOWLIST: string[] = ['is_identified', 'search', 'cohort']
```
Comment (mariusandra) [inline frontend/src/scenes/persons/personsLogic.ts:15]: 👍

File: frontend/src/scenes/persons/personsLogic.ts [hunk 4]
```diff
@@ -182,7 +201,18 @@ export const personsLogic = kea<personsLogicType<PersonPaginatedResponse>>({
...
         },
-        '/person/*': ({ _ }: { _: string }) => {
+        '/person/*': (
+            {
+                _,
+            }: {
+                _: string
+            },
+            _searchParams: Record<string, string>,
+            { activeTab }: Record<string, any>
```
Comment (mariusandra) [inline frontend/src/scenes/persons/personsLogic.ts:211]: I made some improvements to types in kea and these don't need to be manually specified anymore.

**Review by mariusandra — DISMISSED** [review]
Thanks for parsing through this mess that is our frontend linking logic! 🙈 

Found some bugs. This feels broken when opening a person from the insights page. I'm not really sure what is and what should be highlighted here, but it's pretty confusing:


Now on the person and normal sessions pages, I can't expand the rows:



Can you also show in some video how it looks like when you actually click a link that leads to where you should get to? I'm not sure I tested all the possible edge cases here :).

File: frontend/src/lib/utils.tsx (hunk 1 above)
Comment (alexkim205) [reply frontend/src/lib/utils.tsx:42]: Oo nice, I'll be damned if there's something kea can't do 😆

File: frontend/src/scenes/events/eventsTableLogic.js (hunk 2 above)
Comment (alexkim205) [reply frontend/src/scenes/events/eventsTableLogic.js:191]: I don't see anywhere we use the `eventsTableLogic.values.propertiesForUrl` anyways so I think this can be removed.

File: frontend/src/scenes/persons/personsLogic.ts (hunk 4 above)
Comment (alexkim205) [reply frontend/src/scenes/persons/personsLogic.ts:211]: @mariusandra, not too sure what you mean here. Could you explain what I should take out here?

**Comment by alexkim205** [comment]
Thanks for the review!

> Found some bugs. This feels broken when opening a person from the insights page. I'm not really sure what is and what should be highlighted here, but it's pretty confusing:

Here I'm trying to visualize matching events and sessions that contain matching events by highlighting rows. However I can see how this might be confusing/feel broken when the events are still loading. Talking with @clarkus about this more—

> Now on the person and normal sessions pages, I can't expand the rows:

Edit: Fixed!

> Can you also show in some video how it looks like when you actually click a link that leads to where you should get to? I'm not sure I tested all the possible edge cases here :).

Good catch! Fix incoming. Also need to catch some of these edge cases with tests which I'll include in the next rev.

Edit: Fixed!

---

Talked about it with Chris more and the easiest win here would be not to expand matching sessions. We also discussed removing highlighting/coloring altogether or augmenting it with some clearer language ("matching" icon).

**Comment by clarkus** [comment]
@alexkim205 and I caught up for a quick working session on this change. When filters are applied, only matching sessions should be shown, so highlighting a session feels unnecessary. I think a simple improvement would be to collapse the matching sessions by default. This would better enable a user to scroll through the list and look for the primary identifiers in the table - email address, duration, etc. Then once the user finds what session they're looking for, they can opt to expand and see the full list of events with highlighted matches. 

What if we could summarize the count of matching events from the session adjacent to the session email address? This would quickly quantify which sessions were the best matches for the event filters applied. If we have the ability to sort, filter, or otherwise modify the list of events within a session, this could be expanded to trigger an alternate view that only shows matching events. This same treatment could be repeated for each matching event to reinforce what highlights / icons mean in this context. Thoughts?

Screen Shot 2021-06-28 at 2 57 04 PM

**Comment by alexkim205** [comment]
> @alexkim205 and I caught up for a quick working session on this change. When filters are applied, only matching sessions should be shown, so highlighting a session feels unnecessary. I think a simple improvement would be to collapse the matching sessions by default. This would better enable a user to scroll through the list and look for the primary identifiers in the table - email address, duration, etc. Then once the user finds what session they're looking for, they can opt to expand and see the full list of events with highlighted matches.

100% agree. Love how native the events count icon and the popover feel.

>
> What if we could summarize the count of matching events from the session adjacent to the session email address? This would quickly quantify which sessions were the best matches for the event filters applied. If we have the ability to sort, filter, or otherwise modify the list of events within a session, this could be expanded to trigger an alternate view that only shows matching events. 

Today we don't support sorting/filtering, because long lists of events will be returned in paginated portions. These operations require backend changes that might take a few cycles. However I love the idea of an option we could place above the table to toggle between matching and all events. This seems like a simpler change that I can take under the scope of this PR. Having our tables be dynamic like this would also be more consistent with how we treat our insight tables as well, so this seems like a win-win we'd want to implement in the future.

> This same treatment could be repeated for each matching event to reinforce what highlights / icons mean in this context. Thoughts?

@paolodamico had a cool mockup [here](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=1086%3A9766) where we kind of do something similar using a mix of icons and highlights. I think theres elements from here that we could take, especially the event highlighting because color could make items in a list easier to scan than labels + icons. Another reason this could be more practical is it'd be difficult to display icons/labels if there are many matching event properties. The mockup below is a frankenstein of yours and paolo's mockups which captures the gist of what I'm thinking about. What do you think?

Screen Shot 2021-06-28 at 10 10 18 PM

**Comment by alexkim205** [comment]
Made some progress on this new design and wanted to give an update:

https://user-images.githubusercontent.com/13460330/123751788-f4cbda00-d86c-11eb-96a3-c9af514bf9db.mov

Things still to do:
- [x] e2e deeplink test
- [x] matched vs all events toggle option

**Comment by paolodamico** [comment]
This is looking awesome @alexkim205! Some feedback from your video (but do lmk if you'd like a more thorough review).

1. It'd be super useful if when you open the sessions page you automatically scroll the user to the relevant part of the page.
2. I'm thinking it might be worth to get rid of some columns in the sessions page, having too many just makes it impossible to read (maybe drop event count & end time?)
3. I would consider adding an "Expand all sessions" button to make it easy to look at the whole list of relevant events.
4. One big problem we have today with sessions is that we only show sessions on a given day (def worth checking with Core Analytics if there's something we can do to improve this). What are the plans for how to show these when the time range is larger than a day?
5. Related to the above (and might be worth involving someone from Core Analytics), consider for example a last 7 days funnel, when you click on it, how will we make sure we show you the relevant session where this actually happened?
6. Tangential, but it'd be great if we use the PropertyValue component in the event list so "$pageview" becomes "Pageview".

**Comment by alexkim205** [comment]
Thanks for the quick feedback 💥!

1. 👍 done!
2. 👍 done! I think event count would still be important information. Perhaps a good compromise would be to remove this column and move this information into the tooltip when hovering over the matching events icon - `2 out of 20 events are matching`. I'm also open to different wording here... maybe `2 matching out of 20 total events`?
3. 👍 done!
4. I think the work you mention here belongs in a separate PR, and could benefit from a deeper discussion w/ the core analytics team. It would make sense to replace the single day selector at the top of sessions page to a date filter that is more consistent with what we have for our insight graphs. @paolodamico could you create this issue?
5. In addition to the above, sessions filtering by date ranges should work in tandem with how date range filtering works on insights (i.e., 7day funnels should deeplink to week range session filters). 
6.  Hm not sure what you mean here. Are you referring to this `<PropertyValue/>` and if so how would we be able to use that?

**Comment by paolodamico** [comment]
This is great, thanks @alexkim205! Will take a full look at this today. Re 4 & 5, I believe we already have an issue around this and discussion on #4884 might actually change this. In the meantime I'm just curious as to what the behavior will be with the current functionality.

Re 6, my bad, the component I meant is `<PropertyKeyInfo />`

**Comment by alexkim205** [comment]
> Can you also show in some video how it looks like when you actually click a link that leads to where you should get to? I'm not sure I tested all the possible edge cases here :).

Here ya go @mariusandra! Added an e2e test as well

**Deep Link Auto Scroll**


https://user-images.githubusercontent.com/13460330/123977153-99384400-d973-11eb-9d36-b66aecdc0f7b.mov

**Navigating from Non-Insights Page = No Auto Scroll**


https://user-images.githubusercontent.com/13460330/123977326-bf5de400-d973-11eb-8a8c-0f27be45029a.mov



**Expand All and Show Only Matches Toggles**


https://user-images.githubusercontent.com/13460330/123976872-5d04e380-d973-11eb-8f26-eff9e3c0900b.mov



**Empty Filters Edge Case**

https://user-images.githubusercontent.com/13460330/123976783-48c0e680-d973-11eb-8983-5769272495c6.mov

File: frontend/src/lib/components/ExpandIcon.tsx [hunk 5]
```diff
@@ -0,0 +1,40 @@
...
+    children?: JSX.Element
+}
+
+function ExpandIcon({ prefixCls, onExpand, record, expanded, expandable, children }: ExpandIconProps): JSX.Element {
+    const iconPrefix = `${prefixCls}-row-expand-icon`
+    return (
+        <div
+            style={{ display: 'flex', alignItems: 'center' }}
+            onClick={(e) => {
+                onExpand(record, e!)
```
Comment (mariusandra) [inline frontend/src/lib/components/ExpandIcon.tsx:22]: Let's remove the `!`, it doesn't make a difference anyway. For added plus points, let's convert this eslint rule from `warn` to `error`. We've been eliminating all `!`s anyway, since they produce warnings that add noise in github... and these `!`s should be at least warnings I think :).

File: frontend/src/scenes/persons/PersonsTable.tsx [hunk 6]
```diff
@@ -34,14 +37,20 @@ export function PersonsTable({
...
+    const deepLinkToPersonSessions = (person: PersonType): string =>
+        combineUrl(
+            `/person/${encodeURIComponent(person.distinct_ids[0])}`,
+            { filters: sessionsFilters, date },
+            {
+                backTo,
+                backToURL: window.location.pathname + window.location.search + window.location.hash,
+                activeTab: backTo === 'Insights' ? PersonsTabType.SESSIONS : PersonsTabType.EVENTS,
+            }
+        ).url
```
Comment (mariusandra) [inline frontend/src/scenes/persons/PersonsTable.tsx:53]: For later, but relevant: we should gather all different ways we can link between pages and all the extension logic into some utils folder. This could definitely go there.

I did some early work on this, but from a different angle here: https://github.com/PostHog/posthog/pull/4656 -- these two could be merged somehow?

File: frontend/src/scenes/persons/personsLogic.ts (hunk 4 above)
Comment (mariusandra) [reply frontend/src/scenes/persons/personsLogic.ts:211]: Some TS errors are now reported on this logic.

Basically there's no need to specify any types in this line. So it could be just:
```
        '/person/*': ({ _: person }, _searchParams, { activeTab }) => { ... }
```

File: frontend/src/scenes/trends/PersonModal.tsx [hunk 7]
```diff
@@ -1,14 +1,32 @@
 import React from 'react'
```
Comment (mariusandra) [inline frontend/src/scenes/trends/PersonModal.tsx:1]: Bunch of TS errors reported in this file. Possibly due to changes that got merged in with https://github.com/PostHog/posthog/pull/4839

**Review by mariusandra — APPROVED** [review]
Went through it once more. Looking very good! Still some very tiny things though:

- The frontend code quality (typescript linting) test is failing
- Tiny bug here, but that was already there before. Might be easy enough to get fixed but no problem to hold off.
image
- I'm actually not that big of a fan of the scrolling on the "Deep Link Auto Scroll" video. My first reaction is "huh? why did it go there now?". Could be just me...

Approved otherwise, but the types at least need to be fixed before merging this in!

File: frontend/src/scenes/persons/PersonsTable.tsx (hunk 6 above)
Comment (alexkim205) [reply frontend/src/scenes/persons/PersonsTable.tsx:53]: Interesting thats a good point. Yea this definitely felt hacky but my changes is a slight upgrade from what we had originally. It'd be nice to bring this under your sceneLogic once your PR is merged.

File: frontend/src/scenes/persons/personsLogic.ts (hunk 4 above)
Comment (alexkim205) [reply frontend/src/scenes/persons/personsLogic.ts:211]: I think my kea version in `node_modules` was stale or something because typescript kept complaining when I took these types out. Note to self - clear `node_modules` and run `yarn install` when dependencies are updated

File: frontend/src/scenes/trends/PersonModal.tsx (hunk 7 above)
Comment (alexkim205) [reply frontend/src/scenes/trends/PersonModal.tsx:1]: ah you're right I think generalizing `ActionFilter` to `ActionFilter | 'sessions'` broke some things

**Comment by alexkim205** [comment]
1. Fixed all typescript errors!
2. Quick fix

Screen Shot 2021-06-30 at 10 02 59 PM


3. Hm I'm kind of impartial to the scroll to behavior but I think I'll keep it in here for now unless it proves to be too jarring 🤷

**Comment by alexkim205** [comment]
failing tests seem unrelated
