### PR TITLE
No login flash

### LINKED ISSUE #3868: Redirect for authenticated users is not smooth
## Bug description

Going to app.posthog.com gives me the login screen for a significant amount of time before taking me over to `/insights`:

https://user-images.githubusercontent.com/38760734/113567105-7d840280-95fd-11eb-9327-6e07db45c985.mov

## Expected behavior

A lot less flashing, either with better routing, or by adding a loader while we make a decision.

## How to reproduce

1. Go to app.posthog.com
2. Watch it flicker
3.

## Environment

This happens on Cloud, but locally I get a different type of flicker: large logo on white page before scene render. 

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Finally fixes https://github.com/PostHog/posthog/issues/3868
- Moves all the URL override logic (e.g. redirect to /login if not logged in) into `sceneLogic`, away from the component and useEffect. This makes everything smoother, as we don't have to render the pre-set scene before doing the redirection.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] Frontend/CSS is usable at 320px (iPhone SE) and decent at 360px (most phones)

### CODE REVIEW

**Comment by mariusandra** [comment]
This also fixes the `/login/?next=/events` system that seems to have broken at some point. Now if you open any page, but are logged out, you will be redirected to it when you log in.

File: frontend/src/scenes/sceneLogic.ts [hunk 1]
```diff
@@ -207,8 +208,13 @@ export const routes: Record<string, Scene> = {
 
 export const sceneLogic = kea<sceneLogicType<Scene, Params, LoadedScene, SceneConfig>>({
     actions: {
+        // 1. Start opening the scene, yet the listener may override and do something else (calls loadScene)
+        openScene: (scene: Scene, params: Params) => ({ scene, params }),
+        // 2. Start loading the scene JavaScript and mount any logic, then call setScene
```
Comment (paolodamico) [inline frontend/src/scenes/sceneLogic.ts]: Kudos on these comments to help anyone understand this! 🎉

File: frontend/src/scenes/sceneLogic.ts [hunk 2]
```diff
@@ -296,6 +303,54 @@ export const sceneLogic = kea<sceneLogicType<Scene, Params, LoadedScene, SceneCo
...
+                // If user is on an initiated self-hosted instance, redirect away from signup
+                router.actions.replace('/login')
+                return
+            }
+
+            if (user) {
+                // If user is already logged in, redirect away from unauthenticated-only routes like signup
+                if (sceneConfig.onlyUnauthenticated) {
+                    if (scene === Scene.Login && router.values.searchParams['next']) {
+                        router.actions.replace(router.values.searchParams['next'])
```
Comment (paolodamico) [inline frontend/src/scenes/sceneLogic.ts:322]: https://github.com/PostHog/posthog/blob/2b4290959108dd6401449e9a7c1251e2dbcb980e/frontend/src/scenes/authentication/loginLogic.ts#L41 already handles this redirection, and further I think it might be better to do a hard reload here in case we don't properly handle reloading everything?

**Review by paolodamico — APPROVED** [review]
Just one thing I'm not sure about, but 🚢 otherwise!

File: frontend/src/scenes/sceneLogic.ts (hunk 2 above)
Comment (mariusandra) [reply frontend/src/scenes/sceneLogic.ts:322]: This only applies if you just log in. If while logged in you end up on the URL https://app.posthog.com/login?next=/events (e.g. you reload the login page), there would have been no redirection. It's there now.

Comment (mariusandra) [reply frontend/src/scenes/sceneLogic.ts]: That said, I [consolidated](https://github.com/PostHog/posthog/pull/4642/commits/65865fc8f5de1153150080d07eee7b81f38fe6d1) the logic and added `afterLoginRedirect(): string` that gives both logics the url to open after the user has logged in.
