### PR TITLE
fix: insights table total sum display

### LINKED ISSUE #11965: Total count (sum) on tabular data showing as 0
## Bug description

All tabular data referring to page view when summed is showing as 0.  This was fine a few days ago, but for the last couple of days, it has been broken.

## How to reproduce

1. Create an insight with pageview even and show as total count.
2. View as chart type: table

## Environment

**- [ X ] PostHog Cloud**
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

I've added screenshots:

1. Shows dashboard

2. Show query and tabular data

3. To prove there are values, changed to chart type: graph so you can see the values

### PR DESCRIPTION
**Pull request by liyiy**
## Problem

https://github.com/PostHog/posthog/pull/11953 broke the insights table total sum display 

Closes https://github.com/PostHog/posthog/issues/11965

https://posthogusers.slack.com/archives/C01GLBKHKQT/p1664136571545369

## Changes

Sometimes the correct number is under `aggregated_value` rather than `count`. The API returns values for both though so it's hard to know which is correct number to display 

before:

Screen Shot 2022-09-26 at 3 31 22 PM

after:

Screen Shot 2022-09-26 at 3 10 48 PM
 

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

File: frontend/src/scenes/insights/views/InsightsTable/InsightsTable.tsx [hunk 1]
```diff
@@ -271,6 +271,9 @@ export function InsightsTable({
                 let value: number | undefined = undefined
                 if (calcColumnState === 'total' || isDisplayModeNonTimeSeries) {
                     value = item.count ?? item.aggregated_value
+                    if (item.aggregated_value > item.count) {
+                        value = item.aggregated_value
+                    }
```
Comment (Twixes) [inline frontend/src/scenes/insights/views/InsightsTable/InsightsTable.tsx:276]: Ah, perhaps we should be using here `NON_TIME_SERIES_DISPLAY_TYPES`. Display types in that list use `aggregated_value`, while the others depend on `count` AFAIK. Though it's hard to be certain without test coverage – clearly there's none here…

Comment (liyiy) [reply frontend/src/scenes/insights/views/InsightsTable/InsightsTable.tsx:276]: Let's get this fix in for our users first and look at a longer term solution afterwards 😃
