### PR TITLE
Fix sessions indefinite loading users bug

### LINKED ISSUE #3985: Clicking on session datapoint doesn't return people
## Bug description

*Please describe.*  
- For sessions in insights, clicking on a datapoint doesn't return people
*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior
- the modal should return people

## How to reproduce

1. Go to sessions under insights
2. Click on a datapoint on the trend graph
3. Loading spinner forever

### PR DESCRIPTION
**Pull request by liyiy**
## Changes

Closes #3985 

Going to **insights -> sessions -> graph data point** would load indefinitely
The API call was expecting entity values which weren't being set properly in the trends logic

https://user-images.githubusercontent.com/25164963/115620384-1637a500-a2c3-11eb-9dda-2aa645deb77d.mov

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious

### CODE REVIEW

File: frontend/src/scenes/trends/trendsLogic.ts [hunk 1]
```diff
@@ -100,8 +100,8 @@ function parsePeopleParams(peopleParams: PeopleParamType, filters: Partial<Filte
     const { action, date_from, date_to, breakdown_value, ...restParams } = peopleParams
     const params = filterClientSideParams({
         ...filters,
-        entity_id: action.id,
-        entity_type: action.type,
+        entity_id: action.id || filters?.events?.[0].id,
```
Comment (EDsCODE) [inline frontend/src/scenes/trends/trendsLogic.ts:103]: I think you can chain a third condition here for `filters?.actions?.[0].id`. Events work now but if an action is selected the datapoint still will fall over

**Review by EDsCODE — APPROVED** [review]
LGTM
