### PR TITLE
fix(surveys): fix broken NPS survey results

### LINKED ISSUE #21255: Survey throws `There was a problem completing this query` when launching it
## Bug description

Creating an NPS survey throws an error when launching it:
`There was a problem completing this query`
image

Query ID: 367a948a-e8f2-45c1-bcc8-7becd0eaad0e

## How to reproduce
1. Create NPS
2. Press "Launch"

## Environment
- [x] PostHog Cloud EU, project ID: 18057

### PR DESCRIPTION
**Pull request by dmarticus**
## Problem

 We had an issue where users were unable to see a summary of their NPS survey results; instead of data, they saw a screen like this. 
 
image

Ooof.

This issue was being caused by a mismatch in types. The problem was this:
- `$survey_response`s were being incorrectly collected and ingested into clickhouse as floats instead of strings.
- our NPS insight was querying clickhouse with a collection of floats to compose the insight (a visualization that mapped respondents into detractors, passives, and promoters), which was confusing because...
- the underlying clickhouse query that collected all of the events necessary to visualize this insight expected that all `$survey_response`s were strings (even though these responses were floats), so the API call itself was failing with an error like this

```
CHQueryErrorNoCommonType
DB::Exception: There is no supertype for types String, Float64 because some of them are String/FixedString and some of them are not: while executing 'FUNCTION equals(nullIf(nullIf(mat_$survey_response, ''), 'null') : 28, 7. : 16) -> equals(nullIf(nullIf(mat_$survey_response, ''), 'null'), 7.) Nullable(UInt8) : 32'. Stack trace:
```

[sentry link](https://posthog.sentry.io/issues/5386785821/?query=is:unresolved&sort=date&statsPeriod=14d&stream_index=2)

 

Furthermore, fixing the frontend query to use strings instead of floats fixed the API call from failing, but then displayed no data, since all of the `$survey_response`s were floats, and didn't match the values being passed in from the query.

## Changes

So, to fix this, we needed to do the following:

- modify the frontend query to call clickhouse with a collection of strings instead of floats
- modify the survey response ingestion code to cast all survey responses to strings upon collection
- write a postgres migration to change all old survey response property_types to strings so that existing data can be visualized correctly.

Now, the data looks like this!

image

This PR closes https://github.com/PostHog/posthog/issues/21255

## Does this work well for both Cloud and self-hosted?

Yes

## How did you test this code?

- Manually tested the UI by filling out my test NPS survey and observing the data appearing correctly in the UI
- Wrote automated tests for the `$survey_response` data being ingested with the correct types

### CODE REVIEW

File: frontend/src/scenes/surveys/surveyLogic.tsx [hunk 1]
```diff
@@ -279,6 +279,8 @@ export const surveyLogic = kea<surveyLogicType>([
                     `,
                 }
                 const responseJSON = await api.query(query)
+                // TODO:Dylan - I don't like how we lose our types here
```
Comment (dmarticus) [inline frontend/src/scenes/surveys/surveyLogic.tsx:282]: I need to link this to an issue and chuck it in our backlog; it's not high-priority, but it would be lovely to have principled parsing here – it would've fixed the bug I resolve a few lines later.

File: frontend/src/scenes/surveys/surveyLogic.tsx [hunk 2]
```diff
@@ -722,11 +724,19 @@ export const surveyLogic = kea<surveyLogicType>([
...
+                    // Context: https://posthog.slack.com/archives/C034XD440RK/p1717193765035719
+                    if (questionResults.total === 0) {
+                        return 'No data available'
+                    }
+
+                    const data: number[] = questionResults.data
+                    if (data.length === 11) {
+                        const promoters = data.slice(9, 11).reduce((a, b) => a + b, 0)
+                        const passives = data.slice(7, 9).reduce((a, b) => a + b, 0)
+                        const detractors = data.slice(0, 7).reduce((a, b) => a + b, 0)
```
Comment (dmarticus) [inline frontend/src/scenes/surveys/surveyLogic.tsx:739]: this fixes a bug I called out [in slack](https://posthog.slack.com/archives/C034XD440RK/p1717193765035719) where we were incorrectly trying to cast `undefined` to a string, which resulted in NaN
image

With my fix, we now get a screen like this
image

File: posthog/hogql_queries/query_runner.py [hunk 3]
```diff
@@ -1,14 +1,14 @@
 from abc import ABC, abstractmethod
```
Comment (dmarticus) [inline posthog/hogql_queries/query_runner.py:1]: NB: changes in this file are all no-op and come from an auto-formatter I have installed in my editor.  Perhaps it's something I should turn off.

File: posthog/migrations/0420_set_all_survey_responses_to_be_strings.py [hunk 4]
```diff
@@ -0,0 +1,25 @@
...
+    dependencies = [
+        ("posthog", "0419_remove_organization_available_features"),
+    ]
+
+    operations = [
+        migrations.RunSQL(
+            sql="""
+        update posthog_propertydefinition
+        set property_type = 'String', is_numerical=False
+        where name LIKE '%$survey_response%' and property_type = 'Numeric'
```
Comment (neilkakkar) [inline posthog/migrations/0420_set_all_survey_responses_to_be_strings.py:16]:
```suggestion
        where name LIKE '$survey_response%' and property_type = 'Numeric'
```

File: posthog/migrations/0420_set_all_survey_responses_to_be_strings.py [hunk 5]
```diff
@@ -0,0 +1,25 @@
...
+            """,
+            reverse_sql="""
```
Comment (neilkakkar) [inline posthog/migrations/0420_set_all_survey_responses_to_be_strings.py:18]: definitely don't want this to run ;) - you can no-op the reverse sql!

File: posthog/migrations/0420_set_all_survey_responses_to_be_strings.py (hunk 4 above)
Comment (neilkakkar) [reply posthog/migrations/0420_set_all_survey_responses_to_be_strings.py:16]: a test for the migration would be nice, to ensure it does the right thing!

Comment (neilkakkar) [reply posthog/migrations/0420_set_all_survey_responses_to_be_strings.py:16]: with a `custom_$survey_response` key in the propertydefinition table xD

Comment (dmarticus) [reply posthog/migrations/0420_set_all_survey_responses_to_be_strings.py:16]: cool, I just tested it by running locally and inspecting with Django's ORM, but a test would be better!

File: posthog/migrations/0420_set_all_survey_responses_to_be_strings.py [hunk 6]
```diff
@@ -0,0 +1,21 @@
...
+    dependencies = [
+        ("posthog", "0419_remove_organization_available_features"),
+    ]
+
+    operations = [
+        migrations.RunSQL(
+            sql="""
+        update posthog_propertydefinition
+        set property_type = 'String', is_numerical=False
+        where name LIKE '$survey_response%' and property_type = 'Numeric'
```
Comment (neilkakkar) [inline posthog/migrations/0420_set_all_survey_responses_to_be_strings.py:16]: oh found a small problem here, we have some old survey properties on persons called `$survey_response/<surveyID>`  (instead of the new `$survey_responded/<surveyID>`). In this case, to be safer, we should only update event properties

```suggestion
        where name LIKE '$survey_response%' and property_type = 'Numeric' and type = 1
```

Comment (neilkakkar) [reply posthog/migrations/0420_set_all_survey_responses_to_be_strings.py:16]: (can you add this to the test case as well please 😅 )

**Review by neilkakkar — APPROVED** [review]
(one comment), otherwise looks good, great job fixing! 💪

File: posthog/test/test_migration_0420.py [hunk 7]
```diff
@@ -0,0 +1,92 @@
+from typing import Any
+
+from posthog.test.base import NonAtomicTestMigrations
+
+
+class UpdateSurveyResponseMigrationTest(NonAtomicTestMigrations):
+    migrate_from = "0419_remove_organization_available_features"
+    migrate_to = "0420_set_all_survey_responses_to_be_strings"
```
Comment (neilkakkar) [inline posthog/test/test_migration_0420.py:8]: oh, so you're writing migration no 420, is it? 😏 😂

File: posthog/migrations/0420_set_all_survey_responses_to_be_strings.py (hunk 6 above)
Comment (dmarticus) [reply posthog/migrations/0420_set_all_survey_responses_to_be_strings.py:16]: ooooh good shout!  Thank you!  I'll change this and add it to the tests :)

File: posthog/test/test_migration_0420.py (hunk 7 above)
Comment (dmarticus) [reply posthog/test/test_migration_0420.py]: ugh I WISH
