### PR TITLE
fix(flags): switch feature flags taxonomic filter loading to be async + search like insights

### LINKED ISSUE #27310: Cannot find feature flag in early access selector
## Bug description

The feature flag selector uses the value of the `featureFlagsLogic` via the taxonomic selector. This limits queries to 100 meaning not all flags are loaded in a large account like ours. 

If you search on the feature flags page the returned results are persisted and reused in the selector if you visit the early access creation page without reloading. I used this as a hack to select the flag I needed.

## How to reproduce

flag-selector-not-paginating

### Debug info

_No response_

### PR DESCRIPTION
**Pull request by havenbarnes**
## Problem

Closes https://github.com/PostHog/posthog/issues/27310

## Changes

Before: https://www.loom.com/share/7d7dfd6a62af42e5af2544f7f40f8893

After: https://www.loom.com/share/1da44e6a185147d99fdad10320ab3027

## Does this work well for both Cloud and self-hosted?

Yes

## How did you test this code?

See looms above

### CODE REVIEW

File: frontend/src/lib/components/TaxonomicFilter/taxonomicFilterLogic.tsx [hunk 1]
```diff
@@ -442,8 +441,7 @@ export const taxonomicFilterLogic = kea<taxonomicFilterLogicType>([
                         name: 'Feature Flags',
                         searchPlaceholder: 'feature flags',
                         type: TaxonomicFilterGroupType.FeatureFlags,
-                        logic: featureFlagsLogic,
-                        value: 'featureFlags',
+                        endpoint: combineUrl(`api/projects/${teamId}/feature_flags/`).url,
```
Comment (dmarticus) [inline frontend/src/lib/components/TaxonomicFilter/taxonomicFilterLogic.tsx:444]: this is really nice

File: frontend/src/lib/components/TaxonomicFilter/taxonomicFilterLogic.tsx [hunk 2]
```diff
@@ -442,8 +441,7 @@ export const taxonomicFilterLogic = kea<taxonomicFilterLogicType>([
                         name: 'Feature Flags',
                         searchPlaceholder: 'feature flags',
                         type: TaxonomicFilterGroupType.FeatureFlags,
-                        logic: featureFlagsLogic,
```
Comment (dmarticus) [inline frontend/src/lib/components/TaxonomicFilter/taxonomicFilterLogic.tsx:445]: did you test this somewhere with 100+ flags, or did you inspect the network responses, or something else? curious how you verified it.

**Review by dmarticus — APPROVED** [review]
one comment, non-blocking

File: frontend/src/lib/components/TaxonomicFilter/taxonomicFilterLogic.tsx (hunk 2 above)
Comment (havenbarnes) [reply frontend/src/lib/components/TaxonomicFilter/taxonomicFilterLogic.tsx:445]: Yep, the Loom above is using a project with 128 flags

Comment (havenbarnes) [reply frontend/src/lib/components/TaxonomicFilter/taxonomicFilterLogic.tsx:445]: And I specifically was looking for a flag that was on the second page of results

Comment (dmarticus) [reply frontend/src/lib/components/TaxonomicFilter/taxonomicFilterLogic.tsx:445]: derp, didn't read.
