### PR TITLE
fix: Site app url for early access

### LINKED ISSUE #24100: Implement public opt in link is broken
## Bug description
image
image

https://eu.posthog.com/project/27328/early_access_features/0191086e-10c2-0000-9fc0-44a78672979b

The early access features UI seems to include a link to /apps/ which I think is deprecated? The link inside the modal to the posthog provided UI doesn't work (as a result?).

## How to reproduce

1. Go to posthog cloud
2. Create a feature flag
3. Create an opt in feature flag
4. Use the opt in feature flag's UI to click through to the Implement Public Opt In button
5. Find that the URL linked in that dialog doesn't work.

### Debug info

```shell
- [x] PostHog Cloud, Debug information: https://eu.posthog.com/project/27328/early_access_features/0191086e-10c2-0000-9fc0-44a78672979b
```

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem

The url was wrong

Fixes https://github.com/PostHog/posthog/issues/24100

## Changes

* Repairs the url and accounts for regions

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

### CODE REVIEW

File: frontend/src/scenes/early-access-features/InstructionsModal.tsx [hunk 1]
```diff
@@ -25,7 +26,15 @@ export function InstructionsModal({ onClose, visible, flag }: InstructionsModalP
                     header: 'Option 1: Widget Site App',
                     content: (
                         <div>
-                            Give your users a <Link to="https://app.posthog.com/project/apps/574">prebuilt widget</Link>{' '}
+                            Give your users a{' '}
+                            <Link
+                                to={urls.pipelineNodeNew(
+                                    PipelineStage.SiteApp,
+                                    preflight?.region === Region.EU ? 332 : 574
```
Comment (dmarticus) [inline frontend/src/scenes/early-access-features/InstructionsModal.tsx:33]: image

**Review by dmarticus — APPROVED** [review]
thanks for doing this!
