### PR TITLE
Fix #3747

### LINKED ISSUE #3747: Unable to Open Events Page - Cannot read property 'distinct_id'
## Bug description

The /events page shows a white screen when navigating to it.

The console shows multiple of the following error:
```
instrument.js:109 TypeError: Cannot read property 'distinct_id' of null
    at render (EventsTable.js:104)
    at R (index.js:63)
    at $i (react-dom.production.min.js:153)
    at To (react-dom.production.min.js:173)
    at mc (react-dom.production.min.js:265)
    at us (react-dom.production.min.js:246)
    at cs (react-dom.production.min.js:246)
    at Jc (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Da (react-dom.production.min.js:122)
    at Ka (react-dom.production.min.js:123)
    at Wa (react-dom.production.min.js:122)
    at es (react-dom.production.min.js:240)
    at Object.notify (Subscription.js:19)
    at e.t.notifyNestedSubs (Subscription.js:90)
    at e.t.handleChangeWrapper (Subscription.js:95)
    at m (redux.js:221)
    at Object.dispatch (index.esm.js:1176)
    at Object.keys.forEach.e.actions.<computed> [as fetchEventsSuccess] (index.esm.js:287)
    at eventsTableLogic.js:227
    at u (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at n (asyncToGenerator.js:3)
    at c (asyncToGenerator.js:25)
```

I'm not sure how it's possible that I could have got an event into the database without a distinct ID as I'm assuming the API would reject any submissions should it be blank / empty.

## Expected behavior

I would see a list of all of the events

## How to reproduce

1.  Login
2.  Go to Events page
3. (Possibly try to delete and merge some sessions) - heard from marketing team member.

## Environment

- [ x ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context
This did occur after a member of our marketing team tried to delete / merge a particular user from the sessions page but I don't know the exact process they went though.  Would appreciate the help.

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

See related issue for context. Closes #3747.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

**Review by macobo — APPROVED** [review]

File: frontend/src/scenes/events/EventsTable.js [hunk 1]
```diff
@@ -101,8 +101,8 @@ export function EventsTable({ fixedFilters, filtersEnabled = true, pageKey }) {
                 if (!event) {
                     return { props: { colSpan: 0 } }
                 }
-                return showLinkToPerson && event.person.distinct_id ? (
-                    <Link to={`/person/${encodeURIComponent(event.person.distinct_id)}`} className="ph-no-capture">
+                return showLinkToPerson && event.person?.distinct_ids?.length ? (
+                    <Link to={`/person/${encodeURIComponent(event.person.distinct_ids[0])}`}>
```
Comment (macobo) [inline frontend/src/scenes/events/EventsTable.js:105]: Q: Why remove the classname?

**Comment by paolodamico** [comment]
Thanks for the quick review @macobo !

File: frontend/src/scenes/events/EventsTable.js (hunk 1 above)
Comment (paolodamico) [reply frontend/src/scenes/events/EventsTable.js:105]: Because `PersonHeader` component already adds that class.
