### PR TITLE
fix(annotations): Fix annotations crashing with "Compare previous"

### LINKED ISSUE #11680: Annotations modal is broken for non-US languages
## Bug description

The parsing of the date for an annotation is based on the label text which is different depending on your browser language (i think).

## How to reproduce

1. With a browser language that formats dates as such:
Screenshot 2022-09-06 at 14 22 13
2. Click to add an annotation
3. It fails

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem

Closes https://github.com/PostHog/posthog/issues/11680

## Changes

Use the provided labels rather than the localized ones

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

File: frontend/src/scenes/insights/views/LineGraph/LineGraph.tsx [hunk 1]
```diff
@@ -547,7 +547,12 @@ export function LineGraph_({
                         insightNumericId: insight.id || 'new',
                     }}
                 >
-                    <AnnotationsOverlay chart={myLineChart} chartWidth={chartWidth} chartHeight={chartHeight} />
+                    <AnnotationsOverlay
+                        chart={myLineChart}
+                        chartWidth={chartWidth}
+                        chartHeight={chartHeight}
+                        dates={datasets[0]?.days || []}
```
Comment (Twixes) [inline frontend/src/scenes/insights/views/LineGraph/LineGraph.tsx:554]: The issue with this, if we use `datasets[0]?.days` outright, then all the dates are represented in annotations, but for dense graphs the annotations overlay becomes infamously much wider than the graph, because annotations are positioned the same as _ticks_ – and on a dense graph there's a many-to-one relationship between dates and ticks (so that the graph is readable).
This means we instead need to group those dates based on ticks. Currently on dense graphs some annotations are possibly omitted – the upside however is that there's no sizing weirdness, which seems better for the _average_ user. To ensure a 100% smooth experience I plan to implement the full fix, but it'll be a bit more complex than this.

**Review by Twixes — CHANGES_REQUESTED** [review]

**Review by Twixes — APPROVED** [review]
Made some tweaks to handle dense graphs, should be good now!
