### PR TITLE
fix(workflows): destinations not showing up

### LINKED ISSUE #42031: Pagination and search for destinations
### Bug Description

We need to paginate results properly as some of the destinations are never returned. For team two try to search for this [here](https://us.posthog.com/project/2/functions/01921ee7-5498-0000-4436-e1bd645897be) and you will never find it. Ideally we also have a proper search endpoint where you can search for a specific destination so we dont need to load all of them.

### PR DESCRIPTION
**Pull request by meikelmosby**
## Problem

We had several complaints that folks could not find their hogfunctions. We did not specify a limit in our api queries and therefore hit djangos limit of 100 hogfunctions. Meaning folks thought they saw all their functions but that was not the case. 
Also the search looked through the internal state to find the hog-function instead of using the api.

closes [#42031](https://github.com/PostHog/posthog/issues/42031)

## Changes

- introduced proper server side pagination 
- search uses the api now to find functions 
- separated the tables out for active and paused functions

## How did you test this code?

- local dev

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

### CODE REVIEW

File: frontend/src/scenes/hog-functions/list/HogFunctionsList.tsx [hunk 1]
```diff
@@ -208,65 +217,147 @@ export function HogFunctionList({
         }
 
         return columns
-    }, [props.type, humanizedType, toggleEnabled, deleteHogFunction, isManualFunction]) // oxlint-disable-line react-hooks/exhaustive-deps
+    }, [props.type, toggleEnabled, deleteHogFunction, isManualFunction, setReorderModalOpen])
+
+    const activeColumns = buildColumns
+    const pausedColumns = buildColumns
```
Comment (havenbarnes) [inline frontend/src/scenes/hog-functions/list/HogFunctionsList.tsx]: Doesn't seem like we're doing anything different with these two that requires these separate variables

**Review by havenbarnes — APPROVED** [review]
