### PR TITLE
fix: separate filters for surveys logic

### LINKED ISSUE #27729: When filtering survey responses, the charts are not updated
## Bug description

If I filter the survey results down to a specific response, the charts are not updated.

Image

Expected behavior: filter is also applied to the charts' data

## How to reproduce

1. Go on a survey with responses
2. Filter by an specific answer
3. Notice how the charts are not updated

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables or https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

### PR DESCRIPTION
**Pull request by lucasheriques**
## Problem

Closes https://github.com/PostHog/posthog/issues/27729

Filters were only being applied to the DataTableQuery on the SurveyResults page.

Now they're applied to all survey visualizations.

## Changes

[Loom demo](https://www.loom.com/share/c9df215b539e43b49b5ad61bf9e28b8d)

Store the PropertyFilter values inside `surveyLogic`.

Pass it down to the other queries as well.

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

Yes

## How did you test this code?

[Unit tests with the logic filters](https://github.com/PostHog/posthog/pull/28570/commits/d7bb3f64cb1713d4885fa2e595146abc806adb91)

Manual tests to see if filters are working for all charts

### CODE REVIEW

File: frontend/src/scenes/surveys/surveyLogic.tsx [hunk 1]
```diff
@@ -337,15 +341,18 @@ export const surveyLogic = kea<surveyLogicType>([
...
                         GROUP BY survey_response
                     `,
+                    filters: {
+                        properties: values.propertyFilters,
+                    },
                 }
+
                 const responseJSON = await api.query(query)
-                // TODO:Dylan - I don't like how we lose our types here
-                // would be cool if we could parse this in a more type-safe way
```
Comment (marandaneto) [inline frontend/src/scenes/surveys/surveyLogic.tsx:348]: is this fixed now?

File: frontend/src/scenes/surveys/surveyLogic.tsx [hunk 2]
```diff
@@ -655,6 +679,23 @@ export const surveyLogic = kea<surveyLogicType>([
                 5
             )
         },
+        setPropertyFilters: () => {
+            // Reload all survey data when filters change
+            if (values.survey.questions) {
+                values.survey.questions.forEach((question, index) => {
+                    if (question.type === SurveyQuestionType.Rating) {
```
Comment (marandaneto) [inline frontend/src/scenes/surveys/surveyLogic.tsx:686]: nit: I think a `switch` here would make the code more readable.

File: frontend/src/scenes/surveys/surveyLogic.tsx [hunk 3]
```diff
@@ -1006,13 +1052,14 @@ export const surveyLogic = kea<surveyLogicType>([
...
                             },
+                            ...propertyFilters,
                         ],
                     },
                     propertiesViaUrl: true,
                     showExport: true,
                     showReload: true,
                     showEventFilter: false,
-                    showPropertyFilter: true,
+                    showPropertyFilter: false,
```
Comment (marandaneto) [inline frontend/src/scenes/surveys/surveyLogic.tsx:1062]: is that intentional?

File: frontend/src/scenes/surveys/surveyLogic.tsx [hunk 4]
```diff
@@ -280,21 +281,28 @@ export const surveyLogic = kea<surveyLogicType>([
                                 WHERE event = 'survey shown'
                                     AND properties.$survey_id = ${props.id}
                                     AND timestamp >= ${startDate}
-                                    AND timestamp <= ${endDate}),
+                                    AND timestamp <= ${endDate}
+                                    AND {filters}),
```
Comment (marandaneto) [inline frontend/src/scenes/surveys/surveyLogic.tsx:285]: is there a world where `filters` is empty/null? if so, the SQL will break

File: frontend/src/scenes/surveys/surveyLogic.tsx (hunk 3 above)
Comment (lucasheriques) [reply frontend/src/scenes/surveys/surveyLogic.tsx:1062]: yes, to not show the events filters directly on the `<Query>` component, as we moved it directly to the Survey component

File: frontend/src/scenes/surveys/surveyLogic.tsx (hunk 1 above)
Comment (lucasheriques) [reply frontend/src/scenes/surveys/surveyLogic.tsx]: oops it's not, just readded the comment

File: frontend/src/scenes/surveys/surveyLogic.tsx (hunk 2 above)
Comment (lucasheriques) [reply frontend/src/scenes/surveys/surveyLogic.tsx:688]: i agree, will fix that on https://github.com/PostHog/posthog/pull/28466, which is the PR on top of this, as this logic already changed a little bit

File: frontend/src/scenes/surveys/surveyLogic.tsx (hunk 4 above)
Comment (marandaneto) [reply frontend/src/scenes/surveys/surveyLogic.tsx:285]: so the hogql will ignore empty filters and we don't have to do anything here?

**Review by marandaneto — APPROVED** [review]

File: frontend/src/scenes/surveys/surveyLogic.tsx (hunk 4 above)
Comment (lucasheriques) [reply frontend/src/scenes/surveys/surveyLogic.tsx:285]: yes
