### PR TITLE
Tweak sessions filter UI and use PropertyKeyInfo

### LINKED ISSUE #3384: Slightly confusing UX for session filters
## Bug description
Screenshot 2021-02-18 at 15 38 23

My very first reaction on using this was I found the 'filter sessions by users, actions, events, ...' bar confusing, because it isn't a dropdown and looks like a text search (obviously it's a text search _within_ the dropdown)

## Expected behavior

* An icon on the right of the filter bar to indicate it's a dropdown
* The filter bar to be narrower so it feels more like a dropdown than a text search

ie so it's consistent with our insights filtering, which is what I was looking for as a first reaction:
Screenshot 2021-02-18 at 15 40 38

### PR DESCRIPTION
**Pull request by samwinslow**
## Changes

Fixes #3384 — though there is a lot more do be done with filter UX overall 😄 

Before:

Screen Shot 2021-04-28 at 4 49 57 PM

After:

Screen Shot 2021-04-28 at 4 49 30 PM

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious

### CODE REVIEW

File: frontend/src/scenes/sessions/filters/EditFiltersPanel.tsx [hunk 1]
```diff
@@ -173,8 +175,8 @@ export function EditFiltersPanel({ onSubmit }: Props): JSX.Element | null {
                                         }}
                                         data-attr="edit-session-filter"
                                     >
-                                        <strong>{item.label}</strong>
-                                        <DownOutlined style={{ fontSize: 12, color: 'rgba(0,0,0,0.5)' }} />
+                                        <PropertyKeyInfo value={item.label || 'Property'} />
```
Comment (liyiy) [inline frontend/src/scenes/sessions/filters/EditFiltersPanel.tsx:178]: How come we're passing in 'Property' here? 😮

File: frontend/src/lib/components/SelectDownIcon.tsx [hunk 2]
```diff
@@ -0,0 +1,16 @@
+import React from 'react'
+import { DownOutlined } from '@ant-design/icons'
+
+export const SelectDownIcon = (props: React.HTMLAttributes<HTMLSpanElement>): JSX.Element => {
```
Comment (paolodamico) [inline frontend/src/lib/components/SelectDownIcon.tsx:4]: Think it would be useful to clarify this component (i.e. add a short description) for future reference.

File: frontend/src/scenes/sessions/filters/EditFiltersPanel.tsx (hunk 1 above)
Comment (samwinslow) [reply frontend/src/scenes/sessions/filters/EditFiltersPanel.tsx:178]: Label is possibly undefined & needs a backup value... could also be empty string instead

Comment (paolodamico) [reply frontend/src/scenes/sessions/filters/EditFiltersPanel.tsx:178]: I believe this is a TS thing right? `label` can be `undefined`, not sure if it's better to pass an empty string? Or update the `PropertyKeyInfo` to expect undefined attributes?

**Review by paolodamico — APPROVED** [review]
great improvement! CC @corywatilo this is the type of filter that we have to standardize with the filters in the rest of the app

**Review by liyiy — APPROVED** [review]
