### PR TITLE
fix(llma): fix span input/output state not rendering in conversation view

### LINKED ISSUE #43477: bug(llma): $ai_input_state and $ai_output_state not displayed in Conversation view for spans
## Bug Description

Span events (`$ai_span`) with `$ai_input_state` and `$ai_output_state` properties show "null" in the Conversation view tab, but the same data renders correctly in the Text view tab.

### How to reproduce

1. Navigate to LLM Analytics traces
2. Select a trace containing `$ai_span` events that have `$ai_input_state` properties
3. Click on a span event to view details
4. Observe that Conversation view shows "null" for input/output
5. Switch to Text view - the same data renders correctly

### Additional context

This was reported internally. The data exists in ClickHouse and is accessible via the text_repr API, but direct property access in the frontend returns undefined.

---

### Confirmed facts

1. **Data exists in ClickHouse** - Verified via direct queries that `$ai_input_state` exists in the properties column for affected events
2. **Text view works** - The TextViewDisplay component successfully renders the data by sending the entire event object to the backend `/api/environments/{team_id}/llm_analytics/text_repr/` endpoint
3. **Conversation view fails** - The EventContentDisplayAsync component accesses `event.properties.$ai_input_state` directly and gets undefined

### Data flow analysis

**Text view (works):**
- `TextViewDisplay.tsx` passes entire `event` object to `textViewLogic.ts`
- Logic serializes event as `data: props.event` in API request
- Backend `span_formatter.py` accesses `props.get("$ai_input_state")` successfully

**Conversation view (broken):**
- `LLMAnalyticsTraceScene.tsx` line ~870: `rawInput={event.properties.$ai_input_state}`
- This direct property access returns undefined
- `EventContentDisplayAsync` receives undefined and renders "null"

### Key files involved

- `products/llm_analytics/frontend/LLMAnalyticsTraceScene.tsx` - Main scene, accesses properties directly
- `products/llm_analytics/frontend/components/EventContentWithAsyncData.tsx` - Renders undefined as "null"
- `products/llm_analytics/frontend/text-view/textViewLogic.ts` - Text view API call (works)
- `posthog/hogql_queries/ai/trace_query_runner.py` - Backend query, `_map_event` parses properties with orjson

### Possible causes to investigate

1. **Property not included in API response** - The HogQL query selects `properties` as raw JSON string, then `_map_event` parses it with `orjson.loads()`. Need to verify the parsed dict contains `$ai_input_state`.

2. **Serialization issue** - Something in the Django REST framework or Pydantic serialization might be filtering/truncating properties before they reach the frontend.

3. **Property key format** - The `$` prefix in property names might require special handling in JavaScript object access.

### Next steps

1. Add console logging to frontend to inspect what `event.properties` actually contains at render time
2. Check if other `$ai_*` properties work (like `$ai_model`, `$ai_latency`) - these appear to work
3. Investigate if there is a size threshold causing truncation of large property values

---

## Debug info

- PostHog development environment (localhost)
- Affects LLM Analytics product, Trace viewer feature

### PR DESCRIPTION
**Pull request by andrewm4894**
## Problem

Span events (`$ai_span`) were not displaying their `$ai_input_state` and `$ai_output_state` properties in the LLM Analytics Conversation view. The Text view worked correctly, but the Conversation view showed null for both input and output.

Closes #43477

## Changes

The root cause was a cache poisoning issue in `LLMAnalyticsTraceScene.tsx`. The `useAIData` hook was being called for ALL LLM events with generation-specific properties (`$ai_input`, `$ai_output_choices`). For span events, these properties are undefined, which cached `{ input: undefined, output: undefined }` for the event ID. When `EventContentDisplayAsync` later tried to load span-specific properties (`$ai_input_state`, `$ai_output_state`), the cache already had undefined values.

Fix: Changed the condition from `event && isLLMEvent(event)` to just `isGenerationEvent` so that only generation events pre-load with generation-specific properties. Span events now correctly load their own properties.

This also fixes the same issue for `$ai_embedding` events, which were getting their static output message overwritten by the cached undefined value.

Regression introduced in #43207 - the refactor removed a safeguard that prevented cache loading when both input and output were undefined.

## How did you test this code?

Tested manually by:
1. Opening LLM Analytics trace view for span events
2. Verified `$ai_input_state` and `$ai_output_state` now render correctly in Conversation view
3. Verified generation events still work correctly

## Changelog: (features only) Is this feature complete?

No - this is a bug fix.

### CODE REVIEW

**Review by carlos-marchal-ph — APPROVED** [review]
This is not going to work, it bypasses the async loading alltogether which will be enabled for all LLMA events. Approving to get a fix out there, but could you change the comment to something like: `TODO: Figure out why spans can't load properties async` and I'll take a look later?

File: products/llm_analytics/frontend/LLMAnalyticsTraceScene.tsx [hunk 1]
```diff
@@ -685,15 +685,15 @@ const EventContent = React.memo(
...
-        const eventData =
-            event && isLLMEvent(event)
-                ? {
-                      uuid: event.id,
-                      input: event.properties.$ai_input,
-                      output: event.properties.$ai_output_choices,
-                  }
-                : undefined
+        // Only pre-load for generation events ($ai_input/$ai_output_choices).
+        // Span/embedding events use different properties and load via EventContentDisplayAsync.
```
Comment (andrewm4894) [inline products/llm_analytics/frontend/LLMAnalyticsTraceScene.tsx]:
```suggestion
        // TODO: Figure out why spans can't load properties async
```
