### PR TITLE
fix(action-matching): Match on nulls properly

### LINKED ISSUE #12893: Webhook sends notifications on actions that don't meet the filter.
## Bug description

We have an action that is defined on an event and has two filters.
1. X event property is set.
2. X event != null.

The action is defined to _Post to webhook when this action is triggered_.

The bug is that PostHog wrongfully sends notification when the action is not triggered.
I thing this happens because only **one of the filters match but not both**.
Needless to say that the filters are defined with an AND operator.
In addition to that, I don't see any events under the _Matching events_ section below within the action's page.

Could you please make the webhook trigger only when the action is matched on both filters?
Thanks a lot.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

### PR DESCRIPTION
**Pull request by neilkakkar**
## Problem

Fixes https://github.com/PostHog/posthog/issues/12893

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

File: plugin-server/src/worker/ingestion/action-matcher.ts [hunk 1]
```diff
@@ -52,6 +52,25 @@ export function castingCompare(
     b: any,
     operator: PropertyOperator.Exact | PropertyOperator.IsNot | PropertyOperator.LessThan | PropertyOperator.GreaterThan
 ): boolean {
+    // Check null case first
```
Comment (Twixes) [inline plugin-server/src/worker/ingestion/action-matcher.ts:55]: Can you add the rationale from https://github.com/PostHog/posthog/issues/12893#issuecomment-1323645354 here? Would greatly help future travelers

File: plugin-server/src/worker/ingestion/action-matcher.ts [hunk 2]
```diff
@@ -52,6 +52,25 @@ export function castingCompare(
...
+    if (a === null || b === null) {
```
Comment (Twixes) [inline plugin-server/src/worker/ingestion/action-matcher.ts:56]: I suppose this should be in the `if (typeof a !== typeof b)` block, since this `"null"` vs. `null` comparison only is relevant when one of the values is a string, and the other is a null.

**Review by Twixes — CHANGES_REQUESTED** [review]

File: plugin-server/src/worker/ingestion/action-matcher.ts (hunk 1 above)
Comment (neilkakkar) [reply plugin-server/src/worker/ingestion/action-matcher.ts:55]: Makes sense!

File: plugin-server/src/worker/ingestion/action-matcher.ts (hunk 2 above)
Comment (neilkakkar) [reply plugin-server/src/worker/ingestion/action-matcher.ts:56]: That doesn't work, since the `a != b` in the basic check short circuits first, as `"null" != null` 😬

Comment (Twixes) [reply plugin-server/src/worker/ingestion/action-matcher.ts:59]: Ohh, right, so maybe we should do `if (a === null) a = "null"; if (b === null) b = "null"`? Trying to somehow reduce the line count here 😅

**Review by Twixes — APPROVED** [review]

**Comment by elongl** [comment]
Thanks a lot for resolving the issue.
When will this affect in production (PostHog Cloud)?
@Twixes @neilkakkar

**Comment by Twixes** [comment]
The fix will be live within 15 minutes. :) @elongl
