### PR TITLE
Return correct chart tooltip date

### LINKED ISSUE #5131: Incorrect funnel trends dates display
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

funnels -> select two steps for the funnel -> historical view

This is because we're not passing in a year to dayjs so it defaults to 2001

Screen Shot 2021-07-14 at 1 39 47 PM

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

### PR DESCRIPTION
**Pull request by liyiy**
## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.* 
closes #5131 

For the date of Thursday, June 24th: 

before: 
Screen Shot 2021-07-14 at 4 12 36 PM
 
after:
Screen Shot 2021-07-14 at 4 11 06 PM

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

File: frontend/src/lib/components/DateDisplay/index.tsx [hunk 1]
```diff
@@ -34,11 +34,15 @@ const dateHighlight = (parsedDate: dayjs.Dayjs, interval: IntervalType): string
     }
 }
 
+const checkDateYear = (date: Dayjs): Dayjs => {
+    return date.get('year') === 2001 ? date.set('year', dayjs().year()) : date
```
Comment (liyiy) [inline frontend/src/lib/components/DateDisplay/index.tsx:38]: dayjs defaults to year 2001 if a year isn't passed in

**Comment by mariusandra** [comment]
Can't we somehow fix the issue higher up? As in, what if for some reason I actually want to look at some historic data in 2001. This feels like a very hacky fix... :)

**Comment by liyiy** [comment]
> Can't we somehow fix the issue higher up? As in, what if for some reason I actually want to look at some historic data in 2001. This feels like a very hacky fix... :)

Sure! Let me see if there's a reason we aren't passing the years in the date results

File: ee/clickhouse/queries/funnels/funnel_trends.py [hunk 2]
```diff
@@ -145,16 +145,21 @@ def _summarize_data(self, results):
...
+    def _format_results(self, summary):
         count = len(summary)
         data = []
         days = []
         labels = []
 
         for row in summary:
             data.append(row["conversion_rate"])
-            days.append(row["timestamp"].strftime(HUMAN_READABLE_TIMESTAMP_FORMAT))
+            days.append(
```
Comment (liyiy) [inline ee/clickhouse/queries/funnels/funnel_trends.py:156]: This was returning `days":["Wed. 7 Jul","Thu. 8 Jul","Fri. 9 Jul",` when it should've been like `"days":["2021-07-07","2021-07-08","2021-07-09","2021-07-10"`

Comment (mariusandra) [reply ee/clickhouse/queries/funnels/funnel_trends.py:156]: Wow, could there have been some reason or something dependent on this? Is this something that's easy to add a test for as well? Also, we should use f-strings instead of `format`.

Comment (liyiy) [reply ee/clickhouse/queries/funnels/funnel_trends.py:156]: i don't think so, but perhaps @Twixes or @EDsCODE would know better if there was a dependent reason?

Comment (Twixes) [reply ee/clickhouse/queries/funnels/funnel_trends.py:156]: 1. Easy to add a test, though for tech debt reasons our current tests test `_exec_query` instead of `run`.
2. I think this was added by @EDsCODE when he built the MVP of funnel trends, but I don't think there was a particular reason besides preferring to format labels in the backend instead of the frontend. Definitely makes sense to return more raw data from the backend so that the frontend can do nicer things though.

File: ee/clickhouse/queries/funnels/test/test_funnel_trends.py [hunk 3]
```diff
@@ -93,8 +93,11 @@ def test_no_event_in_period(self):
 
         funnel_trends = ClickhouseFunnelTrends(filter, self.team, ClickhouseFunnel)
         results = funnel_trends._exec_query()
+        formatted_results = funnel_trends._format_results(funnel_trends._summarize_data(results))
 
         self.assertEqual(len(results), 7)
+        print(formatted_results)
```
Comment (paolodamico) [inline ee/clickhouse/queries/funnels/test/test_funnel_trends.py:99]: FYI stale print statement

Comment (paolodamico) [reply ee/clickhouse/queries/funnels/test/test_funnel_trends.py:99]: It actually looks like the test is WIP so let me know when we can take a look

Comment (liyiy) [reply ee/clickhouse/queries/funnels/test/test_funnel_trends.py:99]: heh yeah, how do I run clickhouse backend tests again? 😅 Do I need clickhouse locally?

Comment (paolodamico) [reply ee/clickhouse/queries/funnels/test/test_funnel_trends.py:99]: Yes, usually I'll run clickhouse, zookeeper & kafka with Docker compose and run the tests in the virtualenv. If you want the print to show you need to add the `-s` flag to the `pytest` command.

Comment (liyiy) [reply ee/clickhouse/queries/funnels/test/test_funnel_trends.py]: ok it's ready for review!!

**Review by paolodamico — APPROVED** [review]
lgtm!
