### PR TITLE
fix(survey): Check for question errors and navigate to page when survey form fails

### LINKED ISSUE #41797: bug(surveys): When creating a survey, leaving question label empty and trying to create draft leads to confusing UX
### Bug Description

https://github.com/user-attachments/assets/0d99e497-9204-4c8c-aab9-4793857105a6

When we intentionally want the label to be empty, we do not get any UI feedback when we remove the label:

https://github.com/user-attachments/assets/da098775-03ec-4a3a-9e5a-09c57ffdf376

Once we move on to the other steps and click `Save as draft`, the customisation section opens instead of the steps section. 

## How to reproduce

1. Go to the creation screen for custom survey with no templates
2. Remove the label of the first question
3. Navigate to `Completion conditions`
4. Click on `Save as draft`
5. Notice that the `Customization` section will open.

The expected outcome could be:
1) The steps section expands itself so that I can see the label's error
2) Allow me to save as draft

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables or https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

### PR DESCRIPTION
**Pull request by lshaowei18**
## Problem
Closes https://github.com/PostHog/posthog/issues/41797

## Changes

New survey:

https://github.com/user-attachments/assets/58a65e3a-e458-4ce6-96f4-1d22344af14a

Existing survey:

https://github.com/user-attachments/assets/7a7171d1-5fb1-4e11-bdc6-08e685ff1024

## How did you test this code?

1) Go to survey creation
2) Click on `start from scratch with a blank survey`
3) Create a new question
4) Clear the question label, make sure its empty
5) Go to confirmation or any other section
6) Try to `save as draft`, you should see that the selected section becomes `Steps` and the question that has the empty label is shown

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

### CODE REVIEW

File: frontend/src/scenes/surveys/surveyLogic.tsx [hunk 1]
```diff
@@ -1040,6 +1040,15 @@ export const surveyLogic = kea<surveyLogicType>([
                 // When errors occur, scroll to the error, but wait for errors to be set in the DOM first
                 if (hasFormErrors(values.flagPropertyErrors) || values.urlMatchTypeValidationError) {
                     actions.setSelectedSection(SurveyEditSection.DisplayConditions)
+                } else if (
+                    values.surveyErrors.questions != null &&
+                    !values.surveyErrors.questions.every((q) => q.question === false)
```
Comment (adboio) [inline frontend/src/scenes/surveys/surveyLogic.tsx:1045]: do we need both of these checks? or would just the nullish check on surveyErrors.questions be enough?

**Review by adboio — APPROVED** [review]
curious on the conditions but otherwise looks good, this is a real pain point for our customers. thank you!!

File: frontend/src/scenes/surveys/surveyLogic.tsx (hunk 1 above)
Comment (lshaowei18) [reply frontend/src/scenes/surveys/surveyLogic.tsx:1045]: Hmmmm so while i was testing i noticed that surveyErrors.question can look something like that:

Screenshot 2025-12-12 at 3 21 44 PM

In the case where there are two questions and one of them have errors, it looks like this:

Screenshot 2025-12-12 at 3 22 43 PM

You can test this out by `console.log(values.surveyErrors.questions)` when the survey submit fails!

**Review by adboio — APPROVED** [review]
:ship: thank you!!

**Comment by lshaowei18** [comment]
Hi @adboio , could you help me merge? Thanks!!

**Review by adboio — APPROVED** [review]
