### PR TITLE
Fix bug with date range filters on dashboards

### LINKED ISSUE #4444: Dashboard date range can get into a broken state
## Bug description

If you play around with intervals in dashboard, you can get into a state where metrics from the last day are not displayed.

## Expected behavior

Date range picking should not have side-effects.

## How to reproduce

1. Create a dashboard
2. Set time range last 24 hours, all ok
3. Set time range to yesterday, also ok
4. Set time range to last 24 hours, hours after midnight are missing

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog, version/commit: master

### PR DESCRIPTION
**Pull request by macobo**
Closes https://github.com/PostHog/posthog/issues/4444

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious

### CODE REVIEW

File: frontend/src/lib/utils.tsx [hunk 1]
```diff
@@ -511,16 +511,16 @@ export const dateMapping: Record<string, string[]> = {
...
 ): string {
     if (dayjs.isDayjs(dateFrom) && dayjs.isDayjs(dateTo)) {
         return `${dateFrom.format('YYYY-MM-DD')} - ${dateTo.format('YYYY-MM-DD')}`
     }
-    dateFrom = dateFrom as string
-    dateTo = dateTo as string
-    if (isDate.test(dateFrom) && isDate.test(dateTo)) {
+    dateFrom = (dateFrom || undefined) as string | undefined
+    dateTo = (dateTo || undefined) as string | undefined
+    if (isDate.test(dateFrom || '') && isDate.test(dateTo || '')) {
```
Comment (liyiy) [inline frontend/src/lib/utils.tsx:523]: How come we don't set the dateFrom/dateTo variables to `dateFrom || ''` and  `dateTo || ''` on line 521 and 522 respectively instead of when we pass it in here?

Comment (macobo) [reply frontend/src/lib/utils.tsx:523]: It might mess with iteration on lines 529-535.

However, don't think this matters that much. :)

**Review by liyiy — APPROVED** [review]
