### PR TITLE
fix: Support legacy URL for individual recordings

### LINKED ISSUE #13822: Wrong PostHog-Recording-URL displayed in Sentry
## Bug description

I integrated PostHog with Sentry and I get the wrong URL for `PostHog-Recording-URL` in Sentry. 

Screenshot 2023-01-19 at 15 40 55

Current
```https://eu.posthog.com/recordings/#sessionRecordingId=<ID>```

Expected
```https://eu.posthog.com/home#sessionRecordingId=<ID>```

Is the issue on your side or I should write to Sentry?

## How to reproduce

1. Integrate PostHog with Sentry
2. Every issue in Sentry should contain broken link

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem

Fixes https://github.com/PostHog/posthog/issues/13822
Correction of URL is here https://github.com/PostHog/posthog-js/pull/507

## Changes

* Adds redirect support for old recordings urls

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

Manually

### CODE REVIEW

File: frontend/src/scenes/scenes.ts [hunk 1]
```diff
@@ -259,6 +262,13 @@ export const redirects: Record<string, string | ((params: Params) => string)> =
     '/events/stats/:id': ({ id }) => urls.eventDefinition(id),
     '/events/properties': urls.eventPropertyDefinitions(),
     '/events/properties/:id': ({ id }) => urls.eventPropertyDefinition(id),
+    '/recordings': (_params, _searchParams, hashParams) => {
+        if (hashParams.sessionRecordingId) {
+            // Previous URLs for an individual recording where like: /recordings/#sessionRecordingId=foobar
```
Comment (pauldambra) [inline frontend/src/scenes/scenes.ts:267]:
```suggestion
            // Previous URLs for an individual recording were like: /recordings/#sessionRecordingId=foobar
```

**Review by pauldambra — APPROVED** [review]

**Review by mariusandra — APPROVED** [review]
