### PR TITLE
fix: dashboards last refresh not updating until page refresh

### LINKED ISSUE #11635: Last updated on dashboard is slow to update
## Bug description

When i update all charts on a dashboard the "Last Updated" thingy does not itself actually update. Often i refresh all charts - jump around and maybe end up back and original dashboard where last updated might still say 3 days ago - even though i just updated it. I get confused then and just press to update again (im not sure then if i can trust that the actual charts are based on the updated data i just did - i think they are). This can then be slow if im needlessly updating a dash with like 20 charts. 

image

## How to reproduce

1. go to a medium sized dashboard you use regulalry
2. update it
3. see if the last updated changes

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

When refreshing dashboard insights, the API call is against the Insight API.

This was returning the correct last_refresh date but that wasn't being copied into the dashboard tile, and so the dashboard didn't see the last refresh dates change until something in the UI (or a page refresh) reloaded tiles from the API.

before

## Changes

Sends a signal through the dashboards model action to let the appropriate dashboard update tile last refresh and show users the correct value

after

closes #11635

## How did you test this code?

running it locally and seeing it work

### CODE REVIEW

File: frontend/src/scenes/dashboard/dashboardLogic.tsx [hunk 1]
```diff
@@ -521,17 +527,10 @@ export const dashboardLogic = kea<dashboardLogicType>({
...
-                        (itemLastRefreshed && itemLastRefreshed.isBefore(oldestLastRefreshed))
-                    ) {
-                        oldestLastRefreshed = itemLastRefreshed
-                    }
-                }
-                return oldestLastRefreshed
+                const oldest = [...insightTiles.map((i) => i.last_refresh)].sort((a, b) =>
+                    dayjs(a).isAfter(dayjs(b)) ? 1 : -1
+                )
+                return oldest ? dayjs(oldest[0]) : null
```
Comment (Twixes) [inline frontend/src/scenes/dashboard/dashboardLogic.tsx:533]:
```suggestion
                return oldest.length > 0 ? dayjs(oldest[0]) : null
```

**Comment by pauldambra** [comment]
Am going to go ahead and merge since the last change was your suggestion so it'd be weird not to approve 🤣

**Comment by Twixes** [comment]
:shipit:
