### PR TITLE
fix(homepage): Don't load dashboard twice

### LINKED ISSUE #12999: Home page: dashboard logic is mounted twice, causing excessive API load
## Bug description

PostHog home page contains a home dashboard. However when checking the network tab, all requests are made twice

## How to reproduce

1. Reload a dashboard
2. Check network tab
3. See multiple requests to load dashboard

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

I added console.logs to `afterMount` and `beforeUnmount` - issue seems to stem from the logic getting mounted and immediately unmounted and then mounted again - all with the same props. Something something kea?

### PR DESCRIPTION
**Pull request by Twixes**
## Problem

Should resolve #12999.

## Changes

Building and mounting a logic within a logic is prone to weird problems, and that's what we were doing in `projectHomePageLogic`, resulting in the homepage dashboard being fetched twice on load. Instead it's much more reliable to mount logics at the React level, and only build props in the logic.

## How did you test this code?

Added a Cypress test.

### CODE REVIEW

**Review by macobo — APPROVED** [review]

File: cypress/e2e/projectHomepage.js [hunk 1]
```diff
@@ -0,0 +1,12 @@
+describe('Project Homepage', () => {
+    beforeEach(() => {
+        cy.intercept('GET', /\/api\/projects\/\d+\/dashboards\/\d+\//).as('getDashboard')
+        cy.clickNavMenu('projecthomepage')
+    })
+
+    it('Shows home dashboard on load', () => {
+        cy.wait('@getDashboard').its('response.statusCode').should('eq', 200)
+        cy.verifyCallCount(`getDashboard`, 1) // Only loads once
```
Comment (pauldambra) [inline cypress/e2e/projectHomepage.js:9]: 👨‍🍳 👌

**Review by pauldambra — APPROVED** [review]
