### PR TITLE
fix(flags): render # of affected users for conditions sets that have no conditions

### LINKED ISSUE #18181: Calculate release size even if no conditions are added (surveys/flags)
I would like to control to how many users a survey is rolled out to. I can add a release condition set and add a %, but this only calculates a user size number once I add a release condition.

I would like this to be calculated once I add a percentage, so that I know how many people this is being rolled out to.

Screenshot 2023-10-25 at 13 50 51

### PR DESCRIPTION
**Pull request by havenbarnes**
## Problem

Closes https://github.com/PostHog/posthog/issues/18181

When rendering blast radius text, we are skipping the /user_blast_radius call when no property conditions are set

## Changes

Screenshot 2024-11-11 at 3 15 55 PM

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## How did you test this code?

https://www.loom.com/share/1b2105bb111847c6860f7395e2df53ff
https://www.loom.com/share/ff21a38c93ed4adc93fdbdd56bed79fa

### CODE REVIEW

File: frontend/src/scenes/feature-flags/FeatureFlagReleaseConditionsLogic.ts [hunk 1]
```diff
@@ -183,9 +183,20 @@ export const featureFlagReleaseConditionsLogic = kea<featureFlagReleaseCondition
...
-                if (!properties || properties?.length === 0 || properties.some(isEmptyProperty)) {
-                    // don't compute for full rollouts or empty conditions
+                if (!properties || properties.some(isEmptyProperty)) {
+                    // don't compute for incomplete conditions
                     usersAffected.push(Promise.resolve({ users_affected: -1, total_users: -1 }))
+                } else if (properties.length === 0) {
+                    // Request total users for empty condition sets
+                    const responsePromise = api.create(
+                        `api/projects/${values.currentTeamId}/feature_flags/user_blast_radius`,
+                        {
```
Comment (dmarticus) [inline frontend/src/scenes/feature-flags/FeatureFlagReleaseConditionsLogic.ts:193]: yeah, you probably know this too, but if we don't have any properties in this request we just pull a value off the `Team` object on the backend and use that, rather than querying Postgres again.  Seems like a safe function to reuse.  I like it!

**Review by dmarticus — APPROVED** [review]
beasted it

File: frontend/src/scenes/feature-flags/FeatureFlagReleaseConditionsLogic.ts (hunk 1 above)
Comment (havenbarnes) [reply frontend/src/scenes/feature-flags/FeatureFlagReleaseConditionsLogic.ts:193]: Yep I did take a look at how expensive the extra queries were, not too bad considering!
