### PR TITLE
Nail funnels on dashboards

### LINKED ISSUE #5171: New Funnels UI not legible on dashboard
## Bug description

Funnels UI is not optimized for a small container.

Screen Shot 2021-07-16 at 11 52 09 AM

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

This PR:
- Fixes new funnels display in dashboards (including colored items and both vertical/horizontal layout), i.e. closes #5171
- The funnel layout (horizontal, vertical) is now set in the global insight filters (i.e. in the URL) and is now stored when saving insights (plus relevant backend tests).

**Default**

**Colored dashboards**

**Large funnels (overflow)**
image

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

File: frontend/src/lib/colors.ts [hunk 1]
```diff
@@ -82,7 +82,7 @@ export const dashboardColorHSL = {
     blue: [212, 63, 40],
     purple: [249, 46, 51],
     green: [145, 60, 34],
-    black: [0, 0, 0],
+    black: [0, 0, 18],
```
Comment (mariusandra) [inline frontend/src/lib/colors.ts:85]: Too dark? :D

**Review by mariusandra — APPROVED** [review]
Looks good! Few tweaks I added:
1) There was a default "33" `average_conversion_time` hardcoded in one place. Removed that
2) Added a hotfix to prevent the funnel "time to convert" view from being horizontal (e.g. change the default funnel view to horizontal and click to the histogram view, it'll be borked)
3) I've said it many times, but we should always enable scrollbars on a mac. Otherwise you would have fixed this :). I'll fix it and then merge the PR. 
image

There's an issue that the "BackTo" value is not saved on funnels when opening from a dashboard, but that should be fixed with a patch to passthrough `hashParams` in `actionToUrl` in `funnelLogic` in https://github.com/PostHog/posthog/pull/5236

**Comment by mariusandra** [comment]
A flakey python 3.7 test, others all passed. Merging to move along.

File: frontend/src/lib/colors.ts (hunk 1 above)
Comment (paolodamico) [reply frontend/src/lib/colors.ts:85]: Hahaha [this](https://news.mit.edu/2019/blackest-black-material-cnt-0913) is too dark. Just reflecting the new designs, do think it looks a lot better. Also remember [reading this](https://blog.superhuman.com/how-to-design-delightful-dark-themes/) where it suggest never to use pure white/black to avoid eye strain.

**Comment by paolodamico** [comment]
Thanks for the fixes @mariusandra!
