### PR TITLE
fix if window doesn't exist

### LINKED ISSUE #291: Posthog-js seems to be broken when launching the toolbar
Within the latest release (1.13.13) it appears that the toolbar is no longer loading correctly. Errors within the console show:

```
react-dom.production.min.js:209 TypeError: Cannot read properties of undefined (reading 'onFeatureFlags')
    at Object.afterMount (featureFlagsLogic.ts:105)
    at q (index.esm.js:1531)
    at Object.mount (index.esm.js:1658)
    at st (index.esm.js:2026)
    at rt (index.esm.js:1976)
    at lT (DraggableButton.tsx:32)
    at Ko (react-dom.production.min.js:153)
    at gl (react-dom.production.min.js:261)
    at cs (react-dom.production.min.js:246)
    at ls (react-dom.production.min.js:246)
tl @ react-dom.production.min.js:209
n.callback @ react-dom.production.min.js:226
po @ react-dom.production.min.js:131
ol @ react-dom.production.min.js:212
fs @ react-dom.production.min.js:255
e.unstable_runWithPriority @ scheduler.production.min.js:19
Va @ react-dom.production.min.js:122
ds @ react-dom.production.min.js:248
Jl @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
e.unstable_runWithPriority @ scheduler.production.min.js:19
Va @ react-dom.production.min.js:122
qa @ react-dom.production.min.js:123
Wa @ react-dom.production.min.js:122
Kl @ react-dom.production.min.js:230
hi @ react-dom.production.min.js:163
(anonymous) @ useSecondRender.js:8
i.<computed> @ polyfills-es2015.71bcb99730ef64387c73.js:1
invokeTask @ polyfills-es2015.71bcb99730ef64387c73.js:1
runTask @ polyfills-es2015.71bcb99730ef64387c73.js:1
invokeTask @ polyfills-es2015.71bcb99730ef64387c73.js:1
invoke @ polyfills-es2015.71bcb99730ef64387c73.js:1
n.args.<computed> @ polyfills-es2015.71bcb99730ef64387c73.js:1
polyfills-es2015.71bcb99730ef64387c73.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'onFeatureFlags')
    at Object.afterMount (featureFlagsLogic.ts:105)
    at q (index.esm.js:1531)
    at Object.mount (index.esm.js:1658)
    at st (index.esm.js:2026)
    at rt (index.esm.js:1976)
    at lT (DraggableButton.tsx:32)
    at Ko (react-dom.production.min.js:153)
    at gl (react-dom.production.min.js:261)
    at cs (react-dom.production.min.js:246)
```

### PR DESCRIPTION
**Pull request by timgl**
## Changes

Closes https://github.com/PostHog/posthog-js/issues/291

## How did you test this code?

I will test it on the review app

### CODE REVIEW

File: frontend/src/toolbar/flags/featureFlagsLogic.ts [hunk 1]
```diff
@@ -102,14 +102,18 @@ export const featureFlagsLogic = kea<featureFlagsLogicType>({
     events: ({ actions }) => ({
         afterMount: () => {
             actions.getUserFlags()
-            ;(window['posthog'] as PostHog).onFeatureFlags((_, variants) => {
-                if (variants) {
-                    toolbarLogic.actions.updateFeatureFlags(variants)
+            if (window) {
+                ;(window['posthog'] as PostHog).onFeatureFlags((_, variants) => {
```
Comment (jredl-va) [inline frontend/src/toolbar/flags/featureFlagsLogic.ts:106]: This will result in the same error. We need to test `window['posthog']`

**Review by jredl-va — CHANGES_REQUESTED** [review]
I don't believe this is the right test. The window object exists but posthog does not.

File: frontend/src/toolbar/flags/featureFlagsLogic.ts (hunk 1 above)
Comment (timgl) [reply frontend/src/toolbar/flags/featureFlagsLogic.ts:106]: Yep good catch, thank you!

**Review by jredl-va — APPROVED** [review]

**Review by alexkim205 — APPROVED** [review]
