### PR TITLE
No name override

### LINKED ISSUE #7119: White page loading a dashboard: Can not find path "models.propertyDefinitionsModel" in the store
## Bug description

Try to open https://app.posthog.com/dashboard/20201?highlightInsightId=507967 

The following error pops up:

```
instrument.ts:129 Error: [KEA] Can not find path "models.propertyDefinitionsModel" in the store.
    at /static/chunk-54TPR5DD.js:6
    at Array.reduce (<anonymous>)
    at OGe (/static/chunk-54TPR5DD.js:6)
    at e.reducer.e.selector (/static/chunk-54TPR5DD.js:6)
    at /static/chunk-54TPR5DD.js:5
    at Object.propertyStorage (/static/chunk-54TPR5DD.js:5)
    at Object.get [as propertyStorage] (/static/chunk-54TPR5DD.js:6)
```

## Expected behavior

Page loads

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

cc @mariusandra

### LINKED ISSUE #7120: Changing insight name resets graph incorrectly
## Bug description

https://user-images.githubusercontent.com/148820/141796043-29991fa0-d469-4d2e-8835-60cd5cf789a6.mp4

## Expected behavior

Graph does not change after changing its name

## How to reproduce

See video
1. Open an insight
2. Change time range
3. Change name

Expected:
- Only name changes

Actual:
- Name changes, graph is reset to step 1 incorrectly

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

cc @mariusandra

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

First batch of fixes to the bugs you've been reporting ❤️ 

- Fixes https://github.com/PostHog/posthog/issues/7120
- Fixes https://github.com/PostHog/posthog/issues/7119
  - The error `[KEA] Can not find path "models.propertyDefinitionsModel" in the store.` happened because we were reading a value after the logic had unmounted. Adding a `breakpoint` solved that. The logic had unmounted since react had crashed earlier on, hopefully by the "dayjs().utc is undefined" import order error that I also fixed here.
- Adds a missing path to a logic that was merged to master.

## How did you test this code?

*Please describe.*

### CODE REVIEW

File: frontend/src/layout/navigation/navigationLogic.ts [hunk 1]
```diff
@@ -149,7 +149,7 @@ export const navigationLogic = kea<navigationLogicType<WarningType>>({
             },
         ],
     },
-    loaders: {
+    loaders: () => ({
```
Comment (macobo) [inline frontend/src/layout/navigation/navigationLogic.ts:152]: Q: What does this change? The dayjs invocation is inside another function already, hence it should be lazy or...?

Comment (mariusandra) [reply frontend/src/layout/navigation/navigationLogic.ts]: 🤦 , I think that's right. Removed

**Review by macobo — APPROVED** [review]
