### PR TITLE
Fix various funnels empty state UX postgres

### LINKED ISSUE #5298: Funnel calculation bug on Postgres / empty state
While testing other PRs, I noticed two unexpected behaviors in funnels.

1. When the state of the funnel is changed in Postgres, we no longer show an indicator asking you to recalculate, which leads to confusion. Something like what Metabase does, adding a blurry overlay with a huge calculate button could be an option. An alternative would be to show some banner instructing the user to recalculate. CC @clarkus for input.

image

2. Empty state is maintained when the funnel has 1+ steps, but no action/event selector. While having an "empty"/error state is helpful for this case, the message is not useful.

### PR DESCRIPTION
**Pull request by alexkim205**
## Changes

Fixes #5298.

Changes 
- [x] Auto calculate if leaving empty funnel state
- [x] Add recalculate tooltip nudge
- [x] Hide people table if filters aren't valid (<2 steps)
- [x] Disable calculate button if filters aren't valid

https://user-images.githubusercontent.com/13460330/126726960-5a983126-e378-4a1b-9f95-463bf089ef1a.mov

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

File: frontend/src/scenes/insights/InsightTabs/FunnelTab/FunnelTab.tsx [hunk 1]
```diff
@@ -35,6 +43,8 @@ export function FunnelTab(): JSX.Element {
         closeModal()
     }
 
+    console.log('FILTERS DIRTY', filtersDirty, lastAppliedFilters, filters)
```
Comment (liyiy) [inline frontend/src/scenes/insights/InsightTabs/FunnelTab/FunnelTab.tsx:46]: console log 🧹

File: frontend/src/scenes/funnels/funnelLogic.ts [hunk 2]
```diff
@@ -325,6 +333,10 @@ export const funnelLogic = kea<funnelLogicType>({
                 return false
             },
         ],
+        filtersDirty: [
```
Comment (liyiy) [inline frontend/src/scenes/funnels/funnelLogic.ts:336]: is this used to compare previous to current filters? kinda nit but `filtersDirty` confuses me a little 🤔 can we rename it to something more specific? Like `areNewFilters` or whatever if I'm understanding the selector correctly

**Review by clarkus — CHANGES_REQUESTED** [review]
That tooltip definitely makes you notice the button, but I think it's going to get annoying if it keeps popping up. Maybe we can figure out some threshold for triggering it. Maybe we delay the display if the user hasn't completed any significant events on the page (especially hit calculate) for a 7 seconds or so? That's a completely arbitrary number, but it would make that tooltip less intrusive for users who know to hit calculate. And we'd maintain that state management aspect where it only shows when the query definition has changed since the last calculation.

Edit - maybe just a simple delay is enough without complicating it further. We'd need to try a few delay duration values to see what feels right.

**Comment by mariusandra** [comment]
I'm not convinced of the tooltip either. For me it gets stuck when I add/remove many steps. I tried replacing this antd Popover with the popper tooltips (lib/components/Popup), but same case.



Instead I re-implemented this as a horribly misplaced ugly yellow alert:



> While blocking out the screen with an overlay would no doubt get the user's attention, it feels a bit too intrusive for this case.

Now we really only block the page titles from view, the rest of the funnel is there. 

Alternatively, I tried putting the alert above the funnel (so no overlay), but that jumpy behaviour felt weird, and it also felt weird to then either make or not make the funnel graph semi-transparent. So I kept it as it now is.

I'm going to merge this in to unblock the release. I'd be happy to improve this in a follow up PR though.
