### PR TITLE
fix(llma): include reasoning tokens in cost for gemini 3 models

### LINKED ISSUE #3160: $ai_reasoning_tokens calls is ignored for llm cost calculation
## Bug description
`ai_reasoning_tokens` is not included in `ai_output_tokens`, so our cost calculation currently ignores thinking tokens.

_Please describe._

## How to reproduce

1. Using `posthog@7.6.1`, `posthog-node@5.24.4` and `ai-sdk@5`, wrap the `@ai-sdk/google-vertex` model into the `withTracing`.
2. This is the raw trace 
```
{
  "createdAt": "2026-02-26T18:42:50.188000+00:00",
  "event": "$ai_generation",
  "id": "019c9b42-c331-73d0-a846-9b9bb1c804d5",
  "properties": {
    "$ai_http_status": 200,
    "$ai_model": "gemini-3-flash-preview",
    "$ai_input": [
      {
        "content": [
          {
            "text": "Say hello in one word.",
            "type": "text"
          }
        ],
        "role": "user"
      }
    ],
    "$ai_output_tokens": 2,
    "$ai_framework_version": "5",
    "$ai_lib": "posthog-ai",
    "$ai_output_choices": [
      {
        "content": [
          {
            "text": "**Defining greetings succinctly**\n\n\\n\\n\n\nI've considered several options for a one-word greeting, focusing on directness. \"Hello\" appears the most straightforward, but I've also noted alternatives like \"Hola\" and \"Bonjour\" for wider cultural relevance. I'm leaning toward \"Hello\" for its immediate recognition.\n\n\n",
            "type": "reasoning"
          },
          {
            "text": "Hello.",
            "type": "text"
          }
        ],
        "role": "assistant"
      }
    ],
    "$ai_framework": "vercel",
    "$ai_lib_version": "7.6.1",
    "$ai_reasoning_tokens": 77,
    "$ai_model_parameters": {},
    "$lib": "posthog-node",
    "$ai_trace_name": "version-test",
    "$ai_input_tokens": 6,
    "$ai_latency": 4.006,
    "$ai_trace_id": "b28e4b46-045c-4aab-9ccc-99fdd33eefd9",
    "$lib_version": "5.24.4",
    "$geoip_disable": true,
    "$ai_base_url": "",
    "$ai_provider": "google",
    "$ip": "37.154.135.44",
    "$sent_at": "2026-02-26T18:42:49.777Z",
    "$transformations_succeeded": [
      "GeoIP (0194fe9e-d0cd-0000-da18-b3d7b5a92f9c)"
    ],
    "$ai_text_output_tokens": 2,
    "$ai_input_cost_usd": 0.000003,
    "$ai_output_cost_usd": 0.000006,
    "$ai_request_cost_usd": 0,
    "$ai_web_search_cost_usd": 0,
    "$ai_total_cost_usd": 0.000009,
    "$ai_model_cost_used": "google/gemini-3-flash-preview",
    "$ai_cost_model_source": "openrouter",
    "$ai_cost_model_provider": "google-ai-studio"
  }
}
```

## Related sub-libraries

- [ ] All of them
- [ ] posthog-js (web)
- [ ] posthog-js-lite (web lite)
- [x] posthog-node
- [ ] posthog-react-native
- [ ] @posthog/react
- [x] @posthog/ai
- [ ] @posthog/convex
- [ ] @posthog/nextjs-config
- [ ] @posthog/nuxt
- [ ] @posthog/rollup-plugin
- [ ] @posthog/webpack-plugin

### PR DESCRIPTION
**Pull request by richardsolomou**
## Problem

Events for Gemini 3.x models report `$ai_reasoning_tokens` separately from `$ai_output_tokens` (unlike OpenAI o-series and Anthropic thinking, where reasoning tokens are already inside output tokens). The server-side cost calculator was only adding reasoning tokens to the output cost for Gemini 2.5, so Gemini 3 reports came out undercounted by the reasoning-token multiplier.

Reported in https://github.com/PostHog/posthog-js/issues/3160 with a `gemini-3-flash-preview` event that had 2 output tokens and 77 reasoning tokens — the 77 reasoning tokens were silently dropped from `$ai_output_cost_usd`. The fix lives here because cost calculation runs in the Node.js ingestion pipeline, not in the SDK.

Closes PostHog/posthog-js#3160

## Changes

- `nodejs/src/ingestion/ai/costs/output-costs.ts`: extend `REASONING_COST_MODELS` from `/^gemini-2.5-/` to `[/^gemini-2\.5-/, /^gemini-3(\.\d+)?-/]`. Covers all 6 Gemini 3.x variants currently present in `llm-costs.json` (`gemini-3-flash-preview`, `gemini-3-pro-image-preview`, `gemini-3.1-flash-image-preview`, `gemini-3.1-flash-lite-preview`, `gemini-3.1-pro-preview`, `gemini-3.1-pro-preview-customtools`). Also escaped the dot in the existing 2.5 pattern.
- `nodejs/src/ingestion/ai/costs/output-costs.test.ts`: parameterized regression tests for `gemini-3-flash-preview` (explicitly referencing the issue) and `gemini-3.1-pro-preview`.

Non-goal: the same file has an `internal_reasoning` rate on the Perplexity `sonar-deep-research` model that's still unused by the calculator — separate issue, not touched here.

## How did you test this code?

Agent-authored PR — tested only via the unit test suite (`nodejs/src/ingestion/ai/costs/output-costs.test.ts`, all 34 tests pass, including the 2 new Gemini 3 cases). No manual reproduction against a live Gemini 3 model.

## Publish to changelog?

no

## Docs update

No docs change needed.

## 🤖 LLM context

Authored by PostHog Code agent. Verified the fix path by tracing the reported event through `costs/index.ts`: `$ai_cost_model_source: "openrouter"` in the reporter's trace confirms `setCostsOnEvent` → `calculateOutputCost` ran server-side rather than passing through SDK-computed values, so the Node-side fix is the right place. Numerical check on the reported trace: completion rate 3e-6/token → current `2 × 3e-6 = 0.000006` (matches reported `$ai_output_cost_usd`); after fix `(2 + 77) × 3e-6 = 0.000237`. Also confirmed OpenAI/Anthropic/DeepSeek reasoning models have no `internal_reasoning` pricing entry (because their reasoning tokens are already inside output tokens), so the Gemini-scoped whitelist remains correct to avoid double-counting.

---
*Created with [PostHog Code](https://posthog.com/code?ref=pr)*

### CODE REVIEW

File: nodejs/src/ingestion/ai/costs/output-costs.ts [hunk 1]
```diff
@@ -4,7 +4,7 @@ import { PluginEvent } from '~/plugin-scaffold'
 
 import { ResolvedModelCost } from './providers/types'
 
-const REASONING_COST_MODELS = [/^gemini-2.5-/]
+const REASONING_COST_MODELS = [/^gemini-2\.5-/, /^gemini-3(\.\d+)?-/]
```
Comment (carlos-marchal-ph) [inline nodejs/src/ingestion/ai/costs/output-costs.ts:7]: A bare `gemini-3` (no suffix) or a multi-segment minor like `gemini-3.1.0-…` wouldn't match this regex. Probably never going to land, but worth bearing in mind when the next variant arrives.

File: nodejs/src/ingestion/ai/costs/output-costs.test.ts [hunk 2]
```diff
@@ -172,6 +172,43 @@ describe('calculateOutputCost()', () => {
...
+                $ai_model: modelName,
+                $ai_output_tokens: outputTokens,
+                $ai_reasoning_tokens: reasoningTokens,
+            })
+
+            const result = calculateOutputCost(event, modelRow)
+
+            expectCost(result, expectedCost, 7)
+        })
+    })
```
Comment (carlos-marchal-ph) [inline nodejs/src/ingestion/ai/costs/output-costs.test.ts:211]: The two new cases only hit the standard path. `gemini-3-pro-image-preview` and `gemini-3.1-flash-image-preview` both have `image_output` pricing in `llm-costs.json` and would take the `hasImageTokens && hasImagePricing` branch. Worth mirroring the existing gemini-2.5-flash-image test at line 367 for a Gemini 3 image model so the other half of the patched behaviour is guarded?

File: nodejs/src/ingestion/ai/costs/output-costs.test.ts [hunk 3]
```diff
@@ -172,6 +172,43 @@ describe('calculateOutputCost()', () => {
         })
     })
 
+    describe('gemini 3 models - reasoning token handling', () => {
+        const gemini3FlashModel = createModel('gemini-3-flash-preview', 'google', 0.0000003, 0.0000025)
```
Comment (carlos-marchal-ph) [inline nodejs/src/ingestion/ai/costs/output-costs.test.ts]: The test uses `completion_token=2.5e-6` but the real rate in `llm-costs.json` (and the figure in the PR description) is `3e-6`. Consistent with how the Gemini 2.5 tests already work so not a bug, just flagging in case you'd rather the numbers line up with the issue trace.

File: nodejs/src/ingestion/ai/costs/output-costs.test.ts [hunk 4]
```diff
@@ -172,6 +172,43 @@ describe('calculateOutputCost()', () => {
...
+            const event = createAIEvent({
+                $ai_provider: 'google',
+                $ai_model: modelName,
+                $ai_output_tokens: outputTokens,
+                $ai_reasoning_tokens: reasoningTokens,
+            })
+
+            const result = calculateOutputCost(event, modelRow)
+
+            expectCost(result, expectedCost, 7)
```
Comment (carlos-marchal-ph) [inline nodejs/src/ingestion/ai/costs/output-costs.test.ts]: Any reason for the bespoke precision of 7 here when the Gemini 2.5 cases use the default 6? Reading it in isolation it's not obvious why.

File: nodejs/src/ingestion/ai/costs/output-costs.ts
Comment (carlos-marchal-ph) [inline nodejs/src/ingestion/ai/costs/output-costs.ts]: This comment no longer reflects the widened scope. Could we drop the version and describe the invariant instead, something like "Add reasoning tokens for models where they are reported separately from output tokens"?

**Review by carlos-marchal-ph — APPROVED** [review]

File: nodejs/src/ingestion/ai/costs/output-costs.ts (hunk 1 above)
Comment (richardsolomou) [reply nodejs/src/ingestion/ai/costs/output-costs.ts:7]: Good catch. No such variants exist today and llm-costs.json doesn't list any, but I'll keep an eye out for the next shape of 'gemini-N' — happy to widen the regex (e.g. to `/^gemini-[3-9](\.\d+)*-?/`) when one lands that needs it.

File: nodejs/src/ingestion/ai/costs/output-costs.test.ts (hunk 2 above)
Comment (richardsolomou) [reply nodejs/src/ingestion/ai/costs/output-costs.test.ts:211]: Good call, added in ed49a5996a — mirrored the gemini-2.5-flash-image test against `gemini-3-pro-image-preview` (same shape: image + reasoning tokens, uses real rates from llm-costs.json).

File: nodejs/src/ingestion/ai/costs/output-costs.test.ts (hunk 3 above)
Comment (richardsolomou) [reply nodejs/src/ingestion/ai/costs/output-costs.test.ts]: Updated in ed49a5996a — rates now match llm-costs.json (5e-7 / 3e-6 for gemini-3-flash, 2e-6 / 1.2e-5 for gemini-3.1-pro), so the numerics line up with the issue trace.

File: nodejs/src/ingestion/ai/costs/output-costs.test.ts (hunk 4 above)
Comment (richardsolomou) [reply nodejs/src/ingestion/ai/costs/output-costs.test.ts]: No good reason — just habit. Dropped in ed49a5996a, now uses the default 6 consistent with the Gemini 2.5 cases.

File: nodejs/src/ingestion/ai/costs/output-costs.ts
Comment (richardsolomou) [reply nodejs/src/ingestion/ai/costs/output-costs.ts]: Agreed — fixed in c7d3524287. Went with "Add reasoning tokens to text tokens for Gemini models that report them separately", which matches your suggested framing.
