### PR TITLE
fix: create experiment dashboard failing for ExperimentMetric.

### LINKED ISSUE #32735: Create Dashboard from Experiment fails with validation error
### Bug Description

> [!NOTE]
> From Ticket: https://posthoghelp.zendesk.com/agent/tickets/31496

We are getting this issue when trying to create a dashboard from the experiments page

> Could not create dashboard: parse_error: 1 validation error for QuerySchemaRoot InsightVizNode.source Field required [type=missing, input_value={'kind': 'InsightVizNode'}, input_type=dict] For further information visit https://errors.pydantic.dev/2.10/v/missing

| Error Message |
| - |
| Image |

## How to reproduce

1. Navigate to an Experiment
2. Click _Create dashboard_

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables or https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

### PR DESCRIPTION
**Pull request by rodrigoi**
> [!IMPORTANT]
> 👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

> [!NOTE]
> Closes #32735
> ZenDesk Ticket: https://posthoghelp.zendesk.com/agent/tickets/31496 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/33231)

## Problem

The experiment's _Create dashboard_ feature is working only for _legacy_ metrics. Any new `ExperimentMetric` fails.

## Changes

We've refactored the conversion functions between queries and insight sources to support the _legacy_ experiment metrics and the new ExperimentMetric.

### Before

https://github.com/user-attachments/assets/deedd7a4-4866-4be9-91c9-ad9a8bf1cd59

### After

https://github.com/user-attachments/assets/41468d92-ed16-4026-9fc5-88708b9251de

## Did you write or update any docs for this change?

- [ ] I've added or updated the docs
- [ ] I've reached out for help from the docs team
- [x] No docs needed for this change

## How did you test this code?

cat-type-small

### CODE REVIEW

File: frontend/src/scenes/experiments/experimentLogic.tsx [hunk 1]
```diff
@@ -1247,13 +1246,12 @@ export const experimentLogic = kea<experimentLogicType>([
                         ...singleMetrics,
                         ...sharedMetrics.map((m) => ({ name: m.name, ...m.query })),
                     ].reverse()
+
+                    // debugger
```
Comment (andehen) [inline frontend/src/scenes/experiments/experimentLogic.tsx:1250]: forgot to remove a comment

**Review by andehen — APPROVED** [review]
Nice, this fixes the error 👍 

That said, we need to modify the funnel query. We currently just re-use the preview query, but that includes a placeholder for experiment exposure (pageview). For this query, it should be replaced with the actual exposure criteria. We should also break it down by feature flag value.

I can create an issue for that!
Screenshot 2025-05-28 at 13 11 58
