### PR TITLE
3072 retention person modal fix

### LINKED ISSUE #3072: Certain user profiles don't load from the retention broken out view of users
## Bug description

If I look at our own retention table in our AARRR dashboard, I wanted to have a glance at the *specific* users that were churning or not churning. However, on clicking a point on the graph to load the users list, many of their profiles then won't load on clicking again into them.

## How to reproduce

1. Go to our internal retention table dashboard
2. Click to view all users
3. Some users just appear blank on clicking their profile
Screenshot 2021-01-25 at 11 55 31

NB. This seems to affect *all* churned user profiles, that didn't come back in subsequent weeks after the first one:

Screenshot 2021-01-25 at 11 57 39

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

### LINKED ISSUE #3078: Retention people dates are shifted
## Bug description

*Please describe.*  
- if you have period weekly on a retention table, clicking on the row will show a date that's shifted by a week

## Expected behavior
The date should be correct

## How to reproduce

1. Go to internal dashboard
2. click on a row

### PR DESCRIPTION
**Pull request by EDsCODE**
## Changes

*Please describe.*  
- dates were formatted improperly
- use personserializer instead of clickhouse serializer for uniformity and be able to click on person id

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

File: frontend/src/scenes/retention/RetentionTable.tsx [hunk 1]
```diff
@@ -98,7 +98,7 @@ export function RetentionTable({ dashboardItemId = null }: { dashboardItemId?: s
                         minWidth: results[selectedRow]?.values[0]?.count === 0 ? '10%' : '90%',
                         fontSize: 16,
                     }}
-                    title={results[selectedRow] ? moment(results[selectedRow].date).format('MMMM d, YYYY') : ''}
+                    title={results[selectedRow] ? moment.utc(results[selectedRow].date).format('MMMM D, YYYY') : ''}
```
Comment (macobo) [inline frontend/src/scenes/retention/RetentionTable.tsx:101]: Sort of related to this PR:

Noticed yesterday that retention table has almost no typing (e.g. results is an array of any). Would it make sense to improve this as part of this refactoring? Since the types might make it easier to catch something being wrong.

File: ee/clickhouse/queries/clickhouse_retention.py [hunk 2]
```diff
@@ -235,12 +239,11 @@ def _retrieve_people_in_period(self, filter: RetentionFilter, team: Team):
             },
         )
         people_dict = {}
-        all_people = sync_execute(
-            "SELECT * FROM person WHERE id IN %(uuids)s", {"uuids": [val[0] for val in query_result]}
```
Comment (macobo) [inline ee/clickhouse/queries/clickhouse_retention.py:239]: Wonder if https://github.com/PostHog/posthog/issues/3085 would have caught this :thinking:

File: frontend/src/scenes/retention/RetentionTable.tsx (hunk 1 above)
Comment (EDsCODE) [reply frontend/src/scenes/retention/RetentionTable.tsx:101]: yeah i was looking at another error and noticed this too. giving it an update right now!

Comment (EDsCODE) [reply frontend/src/scenes/retention/RetentionTable.tsx:101]: Put those changes in #3091

File: ee/clickhouse/queries/clickhouse_retention.py (hunk 2 above)
Comment (EDsCODE) [reply ee/clickhouse/queries/clickhouse_retention.py:239]: probably? although I removed this query here not because of performance but because it's more consistent to pull the person from postgres so the frontend handling will be exactly the same
