### PR TITLE
fix: new survey position for feedback button

### LINKED ISSUE #29773: Bug report: custom feedback button survey does not obey positioning customisation
### Bug Description

Created a survey based on a custom feedback button and customised the positioning to be "Center". However, in practice, the survey is sticking to the left. More information (including call recording with screenshots) in [this Slack message](https://posthog.slack.com/archives/C07QD3LT8U9/p1741370931708519)

Image

## Additional context

The feedback button is implemented in a VSCode plugin. The feedback button is not in the plugin page, instead it is on top of the plugin page – i.e. there is no physical button on the page where a class name can be added to PostHog. So the customer created an invisible button that gets 'clicked on' when user generates "feedback button clicked" event.

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables or https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

### PR DESCRIPTION
**Pull request by lucasheriques**
## Problem

needs https://github.com/PostHog/posthog-js/pull/1885

closes https://github.com/PostHog/posthog/issues/29773

## Changes

add a new position type for Feedback Button surveyt: `next to feedback button`

this way the survey will be rendered next to the button on the screen that triggered it.

only available for surveys where the `widgetType == selector` and `surveyType == Widget/FeedbackButton`

## Does this work well for both Cloud and self-hosted?

yes

## How did you test this code?

tested with the SDK

### CODE REVIEW

File: frontend/src/scenes/surveys/SurveyCustomization.tsx [hunk 1]
```diff
@@ -74,12 +86,31 @@ export function Customization({
                     {validationErrors?.borderColor && <LemonField.Error error={validationErrors?.borderColor} />}
                 </LemonField.Pure>
                 <>
-                    <LemonField.Pure className="mt-2" label="Position">
+                    <LemonField.Pure
+                        className="mt-2"
+                        label="Position"
+                        info={
+                            isWidgetSurveyWithSelectorWidgetType
+                                ? 'The "next to trigger" option requires posthog.js version TODO_BEFORE_MERGE or higher.'
```
Comment (marandaneto) [inline frontend/src/scenes/surveys/SurveyCustomization.tsx:94]: is 'next to trigger' obvious for a reader? if they set a selector, should we say something like next to the chosen widget's (or component) selector or something?

File: frontend/src/scenes/surveys/SurveyCustomization.tsx [hunk 2]
```diff
@@ -74,12 +86,31 @@ export function Customization({
...
+                                    !isWidgetSurveyWithSelectorWidgetType
+                                ) {
+                                    return null
+                                }
                                 return (
                                     <LemonButton
                                         key={position}
+                                        tooltip={
+                                            position === SurveyPosition.NextToTrigger
+                                                ? 'This option is only available for widget surveys. The survey will be displayed next to the trigger button.'
```
Comment (marandaneto) [inline frontend/src/scenes/surveys/SurveyCustomization.tsx:111]: i think widget should not be used here since the survey presentation name is feedback button right?

Comment (marandaneto) [reply frontend/src/scenes/surveys/SurveyCustomization.tsx:111]: yep, if there's any more UI labels with 'widget' i'd just replace it.
if our case survey type is widget (looking at the code), that's fine, we can just add a comment for it

File: frontend/src/scenes/surveys/SurveyCustomization.tsx (hunk 1 above)
Comment (lucasheriques) [reply frontend/src/scenes/surveys/SurveyCustomization.tsx]: changed to `This option is only available for feedback button surveys. The survey will be displayed next to the chosen feedback button, based on the CSS selector you provided`

**Review by marandaneto — APPROVED** [review]
