### PR TITLE
fix: modal stacking was hard to increment

### LINKED ISSUE #25486: Bug: Viewing replays from a funnel, replay modal opened behind persons modal.
## Bug description

When opening the person's modal from a funnel, e.g. a dropoff step, and clicking to watch a replay, the replay modal is opened behind the person's modal. 

image

## How to reproduce

1. Open a funnel based on persons with replays active
2. Click through to view persons who dropped off
3. Open a replay 

## Additional context

https://posthoghelp.zendesk.com/agent/tickets/19111

### Debug info

_No response_

### PR DESCRIPTION
**Pull request by pauldambra**
closes https://github.com/PostHog/posthog/issues/25486

the lemon modal could be at its default z-index or forced to the top of the stack

this doesn't help when 

* you open the actor modal 
* from there you open the replay modal
* from there you open the sharing modal

(that chain isn't actually possible at the moment because the replay modal would be behind the actor modal - but it should be possible)

We don't _need_ the modal component to know about why it is being given a z-index and there are already gaps in the reserved z-indices in `vars.scss` 

so we can let the LemonModal accept one of a short list of z-index overrides for circumstances where you need a little more control

|before|after|
|-|-|
|||

fly-by the close button doesn't display correctly on the replay modal. you can click outside or hit escape to close it, so let's not have one

### CODE REVIEW

File: frontend/src/lib/lemon-ui/LemonModal/LemonModal.tsx [hunk 1]
```diff
@@ -46,6 +46,11 @@ export interface LemonModalProps {
     contentRef?: React.RefCallback<HTMLDivElement>
     overlayRef?: React.RefCallback<HTMLDivElement>
     'data-attr'?: string
+    /**
+     * some components need more fine control of the z-index
+     * they can push a specific value to control their position in the stacking order
+     */
+    zIndex?: '1061' | '1062' | '1066' | '1067' | '1068' | '1069'
```
Comment (pauldambra) [inline frontend/src/lib/lemon-ui/LemonModal/LemonModal.tsx:53]: if we ever do get to the point where a single set of interactions needs more than 5 additional z-indices then we can make the modal component handle this internally on our behalf (or redesign to not stack so much)

**Review by richard-better — APPROVED** [review]
