### PR TITLE
Org/projects UX enhancements

### LINKED ISSUE #2169: Leaving last organization
## Bug description

#1562 introduces the possibility of removing yourself from an organization (and an admin **removing** you from an organization). This leads to a orphan user that belongs to no organization. This should be fine, however if you log in with a user that has this characteristic (and particularly happens to after you leave the organization yourself), the app just fails to load, showing just a white screen.

## Expected behavior

If I'm logged in as a user that has no organizations I would just see a page saying I have no organizations and therefore cannot interact with PostHog. The page should probably give me 2 CTAs,
1. Permanently delete my account altogether.
1. Creating a new organization.

## How to reproduce

1. Create a test user.
2. Leave all organizations.

## Environment

Cloud and self-hosted.

## Additional context

No additional context.

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

Some org/projects UX enhancements:
1. [x] Member level change
    - Added organization ownership
2. [x] Project deletion
    - Q: Can we delete data from ClickHouse on project/org deletion? Do we want to?
A: We want to but apparently difficult with ClickHouse. Unsure how to proceed with this aspect.
3. [x] Improved handling of leaving/deleting org/project (prompts to create a new one)

## Checklist

- [x] All querysets/queries filter by Organization, Team, and User (if this PR affects ANY querysets/queries).
- [x] Django backend tests (if this PR affects the backend).
- [ ] Cypress end-to-end tests (if this PR affects the frontend).

### CODE REVIEW

**Comment by Twixes** [comment]
Solved the redirect problem we talked about @timgl. Also added organization ownership.
The only issue remaining is that `User.organization` and `User.team` are now `Optional` which causes lots of typing errors and is an issue generally. I honestly have a hard time addressing this: because `mypy` decided to crap out for me locally, only returning `error: syntax error in type comment` instead of actual type checks. 🤔 So I'll leave the typing as it is until I get that issue sorted, but feel free to try taking up this typing issue as well.

File: frontend/src/scenes/App.tsx [hunk 1]
```diff
@@ -77,6 +93,8 @@ function _App(): JSX.Element {
         )
     }
 
+    if (!currentOrganization?.id || !currentTeam?.id) return null
```
Comment (macobo) [inline frontend/src/scenes/App.tsx:96]: So when is this the case? Do we really want to show a blank page then or do we always redirect the user somewhere?

File: frontend/src/scenes/App.tsx [hunk 2]
```diff
@@ -27,48 +28,63 @@ const darkerScenes: Record<string, boolean> = {
...
     const { location } = useValues(router)
     const { replace } = useActions(router)
-    const [sidebarCollapsed, setSidebarCollapsed] = useState(typeof window !== 'undefined' && window.innerWidth <= 991) // used for legacy navigation [Sidebar.js]
+    // used for legacy navigation [Sidebar.js]
+    const [sidebarCollapsed, setSidebarCollapsed] = useState(typeof window !== 'undefined' && window.innerWidth <= 991)
     const { featureFlags } = useValues(featureFlagLogic)
 
     const Scene = loadedScenes[scene]?.component || (() => <SceneLoading />)
 
     useEffect(() => {
```
Comment (macobo) [inline frontend/src/scenes/App.tsx:51]: This logic is quite heavy for the core <App /> component - can we extract it somewhere where it makes more semantic sense?

E.g. create a hook in `scenes/organization/hooks.ts` named `useCheckAuthentication`?

File: frontend/src/scenes/organization/CreateOrganizationModal.tsx [hunk 3]
```diff
@@ -9,23 +9,28 @@ export function CreateOrganizationModal({
...
     const { createOrganization } = useActions(organizationLogic)
     const [errorMessage, setErrorMessage] = useState<string | null>(null)
     const inputRef = useRef<Input | null>(null)
 
-    const closeModal: () => void = useCallback(() => {
-        setErrorMessage(null)
-        setIsVisible(false)
-        if (inputRef.current) inputRef.current.setValue('')
-    }, [inputRef, setIsVisible])
+    const closeModal: () => void = useCallback(
```
Comment (macobo) [inline frontend/src/scenes/organization/CreateOrganizationModal.tsx:18]: What is this trying to achieve? This seems way too complex and possibly broken from how I understand `useCallback` works, so wondering what's going on here.

File: frontend/src/scenes/organization/CreateOrganizationModal.tsx [hunk 4]
```diff
@@ -9,23 +9,28 @@ export function CreateOrganizationModal({
...
+              },
+        [inputRef, setIsVisible]
+    )
 
     return (
         <Modal
             title="Creating an Organization"
             okText="Create Organization"
-            cancelText="Cancel"
+            cancelButtonProps={!setIsVisible ? { style: { display: 'none' } } : undefined}
```
Comment (macobo) [inline frontend/src/scenes/organization/CreateOrganizationModal.tsx:33]: Double negations are hard to read.

`setIsVisible ? undefined : { style: { display: 'none' } }`

File: frontend/src/scenes/organization/Invites/CreateOrgInviteModal.tsx [hunk 5]
```diff
@@ -47,7 +47,7 @@ export function CreateOrgInviteModalWithButton({ type = 'button' }: { type?: 'bu
                         setIsVisible(true)
                     }}
                 >
-                    Invite Team Member
+                    Invite Teammate
```
Comment (macobo) [inline frontend/src/scenes/organization/Invites/CreateOrgInviteModal.tsx:50]: Note: Ideally this rename could have been split out into a separate short-lived PR - since there's 21 days worth of commits here, can we be sure no-one added any other `Team member` calls in a different PR.

File: frontend/src/scenes/organization/Members/index.tsx [hunk 6]
```diff
@@ -1,56 +1,147 @@
...
 function _Members({ user }: MembersProps): JSX.Element {
+    const { currentOrganization } = useValues(organizationLogic)
     const { members, membersLoading } = useValues(membersLogic)
-    const { removeMember } = useActions(membersLogic)
+    const { removeMember, changeMemberAccessLevel } = useActions(membersLogic)
     const { confirm } = Modal
 
+    const currentMembershipLevel = currentOrganization?.membership_level ?? -1
+
+    const LevelComponent = useCallback(
```
Comment (macobo) [inline frontend/src/scenes/organization/Members/index.tsx:36]: This could just be a separate component it seems. Why use `useCallback` here?

File: frontend/src/scenes/organization/Members/index.tsx [hunk 7]
```diff
@@ -1,56 +1,147 @@
...
 
             return (
                 <div>
-                    <a className="text-danger" onClick={handleClick}>
-                        {member.user_id !== user.id ? (
-                            <DeleteOutlined title="Remove Member" />
-                        ) : (
-                            <LogoutOutlined title="Leave Organization" />
+                    {member.level !== OrganizationMembershipLevel.Owner &&
+                        (member.level < currentMembershipLevel || member.user_id === user.id) && (
```
Comment (macobo) [inline frontend/src/scenes/organization/Members/index.tsx:132]: Extract function here, give it a name, extract it to a file.

e.g. `canDeleteOrganizationMember(member, user)` - this is way too complicated to do inline this way.

This applies to other direct access of `currentMembershipLevel` in this file as well as when a programmer is reading this component they don't want to be thinking about access levels, but whether user has permission to do this/that.

This way there's less chance as the semantics of team membership change we'll forget to update a random component here-or-there.

File: frontend/src/lib/constants.ts [hunk 8]
```diff
@@ -16,11 +16,13 @@ export const PIE_CHART_LABEL = 'Pie'
 export enum OrganizationMembershipLevel {
     Member = 1,
     Admin = 8,
+    Owner = 15,
 }
 
 export const organizationMembershipLevelToName = new Map<number, string>([
```
Comment (macobo) [inline frontend/src/lib/constants.ts:22]: lib/constants are super generic.

I wonder if this + OrganizationMembershipLevel makes more sense under `src/scenes/organization/levels.ts` since it keeps all orgs-related code under `scenes/organizations`

File: frontend/src/lib/utils.tsx [hunk 9]
```diff
@@ -559,11 +559,11 @@ export function someParentMatchesSelector(element: HTMLElement, selector: string
...
 
 /** Convert camelCase to Title Case. Useful for generating page title from internal scene name. */
-export function camelCaseToTitle(camelCase: string): string {
+export function camelCaseToTitle(camelCase: string | number): string {
     const words: string[] = []
     let currentWord: string = ''
-    for (const character of camelCase.trim()) {
-        if (character == character.toLowerCase() && character != character.toUpperCase()) {
+    for (const character of String(camelCase).trim()) {
+        if (character === character.toLowerCase()) {
```
Comment (macobo) [inline frontend/src/lib/utils.tsx:566]: Q: Not sure why the previous code was like that, do you know? 

Would be great if this code had any tests.

File: frontend/src/scenes/userLogic.tsx [hunk 10]
```diff
@@ -111,11 +119,12 @@ export const userLogic = kea<userLogicType<UserType, EventProperty, UserUpdateTy
...
                         posthog.register({
                             posthog_version: user.posthog_version,
-                            has_slack_webhook: !!user.team.slack_incoming_webhook,
+                            has_slack_webhook: !!user.team?.slack_incoming_webhook,
                         })
                     }
                 }
-            } catch {
+            } catch (e) {
+                console.error(e)
```
Comment (macobo) [inline frontend/src/scenes/userLogic.tsx:127]: ?

File: frontend/src/scenes/userLogic.tsx [hunk 11]
```diff
@@ -111,11 +119,12 @@ export const userLogic = kea<userLogicType<UserType, EventProperty, UserUpdateTy
 
                         posthog.register({
                             posthog_version: user.posthog_version,
-                            has_slack_webhook: !!user.team.slack_incoming_webhook,
+                            has_slack_webhook: !!user.team?.slack_incoming_webhook,
```
Comment (macobo) [inline frontend/src/scenes/userLogic.tsx:122]: Note: this will cause conflicts with your other PR

File: posthog/api/organization.py [hunk 12]
```diff
@@ -16,24 +17,25 @@ class PremiumMultiorganizationPermissions(permissions.BasePermission):
 
     def has_permission(self, request: request.Request, view) -> bool:
         if (
+            # make multiple orgs only premium on self-hosted, since enforcement of this is not possible on Cloud
             not getattr(settings, "MULTI_TENANCY", False)
             and request.method in CREATE_METHODS
-            and not request.user.organization.is_feature_available("organizations_projects")
+            and (
+                request.user.organization is None
+                or not request.user.organization.is_feature_available("organizations_projects")
```
Comment (macobo) [inline posthog/api/organization.py:25]: Note (in general): the naming of this is sort of bad, because it really looks like a feature flag call though it isn't.

File: posthog/models/organization.py [hunk 13]
```diff
@@ -113,7 +114,10 @@ class Level(models.IntegerChoices):
 
     class Meta:
         constraints = [
-            models.UniqueConstraint(fields=["organization_id", "user_id"], name="unique_organization_membership")
+            models.UniqueConstraint(fields=["organization_id", "user_id"], name="unique_organization_membership"),
+            models.UniqueConstraint(
+                fields=["organization_id"], condition=models.Q(level=15), name="only_one_owner_per_organization"
```
Comment (macobo) [inline posthog/models/organization.py:119]: Why?

File: posthog/migrations/0101_org_owners.py [hunk 14]
```diff
@@ -0,0 +1,41 @@
+# Generated by Django 3.0.6 on 2020-11-19 06:04
+
+from django.db import migrations, models
+
+
+def make_first_administrators_owners(apps, schema_editor):
+    Organization = apps.get_model("posthog", "Organization")
+    for organization in Organization.objects.all():
+        first_admin = organization.memberships.filter(level=8).first()
```
Comment (macobo) [inline posthog/migrations/0101_org_owners.py:9]: Should we add a created_at filter here?

File: posthog/api/user.py [hunk 15]
```diff
@@ -32,16 +33,16 @@ class Meta:
 # TODO: remake these endpoints with DRF!
 @authenticate_secondarily
 def user(request):
-    organization = request.user.organization
+    organization: Optional[Organization] = request.user.organization
     organizations = list(request.user.organizations.order_by("-created_at").values("name", "id"))
-    team = request.user.team
+    team: Optional[Team] = request.user.team
```
Comment (macobo) [inline posthog/api/user.py:38]:
```
⟩ grep 'request.user.team' **/*.py | wc -l
65
⟩ grep 'request.user.org' **/*.py | wc -l                   
15
```

A lot of these will now raise 500-s when called. This seems like an issue that will start plaguing us long-term.

Thoughts of what we can do here?

File: posthog/api/organization_member.py [hunk 16]
```diff
@@ -38,6 +39,38 @@ class Meta:
...
 
+    def update(self, updated_membership, validated_data):
+        updated_membership = cast(OrganizationMembership, updated_membership)
+        raise_errors_on_nested_writes("update", self, validated_data)
+        requesting_membership: OrganizationMembership = OrganizationMembership.objects.get(
+            organization=updated_membership.organization, user=self.context["request"].user
+        )
+        new_level = validated_data.get("level")
+        with transaction.atomic():
+            if new_level is not None:
```
Comment (macobo) [inline posthog/api/organization_member.py:50]: Suggestion: Extract all the validation to separate method called `validate_level_change`, test fully.

File: posthog/api/organization.py [hunk 17]
```diff
@@ -69,15 +76,16 @@ def destroy(self, request, *args, **kwargs):
...
         filter_kwargs = {self.lookup_field: lookup_value}
-        obj = get_object_or_404(queryset, **filter_kwargs)
-        self.check_object_permissions(self.request, obj)
-        return obj
-
-    def get_queryset(self) -> QuerySet:
-        return self.request.user.organizations.all()
+        organization = get_object_or_404(queryset, **filter_kwargs)
+        self.check_object_permissions(self.request, organization)
+        print(organization)
```
Comment (macobo) [inline posthog/api/organization.py:90]: debug code

File: posthog/api/organization.py [hunk 18]
```diff
@@ -42,10 +44,15 @@ class Meta:
...
     def create(self, validated_data: Dict, *args: Any, **kwargs: Any) -> Organization:
         serializers.raise_errors_on_nested_writes("create", self, validated_data)
-        request = self.context["request"]
-        organization, _, _ = Organization.objects.bootstrap(request.user, **validated_data)
+        organization, _, _ = Organization.objects.bootstrap(self.context["request"].user, **validated_data)
         return organization
 
+    def get_membership_level(self, organization: Organization) -> Optional[OrganizationMembership.Level]:
+        membership = OrganizationMembership.objects.filter(
+            organization=organization, user=self.context["request"].user
```
Comment (macobo) [inline posthog/api/organization.py:52]: Rather than using request here let's pass user as parameter - this way this can be tested properly?

**Review by macobo — COMMENTED** [review]
Same comment as last time - this PR is way too large to effectively review, but tried to. It is really hard in this PR to get a sense for both _why_ some changes were made as well as if they were tested properly.

My suggestion for how to handle PRs like this: Split it along backend/frontend lines, separate PR for the 'no team' behavior.

File: posthog/api/organization.py (hunk 18 above)
Comment (Twixes) [reply posthog/api/organization.py:52]: Not sure what you meant, since this is a serializer method fieldd?

File: posthog/api/user.py (hunk 15 above)
Comment (Twixes) [reply posthog/api/user.py:38]: Added permission class `ProjectMembershipNecessaryPermissions` to endpoints where this could be a problem, which allows for still asserting `request.user.team is not None` and `request.user.organization is not None` in the API.

File: posthog/migrations/0101_org_owners.py (hunk 14 above)
Comment (Twixes) [reply posthog/migrations/0101_org_owners.py:9]: Maybe not a `created_at` one, but a `level=15` one.

File: frontend/src/scenes/App.tsx (hunk 1 above)
Comment (Twixes) [reply frontend/src/scenes/App.tsx:96]: We do redirect, but inside this same `_App` component, but with `useEffect`.

File: frontend/src/lib/utils.tsx (hunk 9 above)
Comment (Twixes) [reply frontend/src/lib/utils.tsx:566]: It was like that because I just copied it from SO :) but it had a problem with numbers that way.

File: frontend/src/lib/constants.ts (hunk 8 above)
Comment (Twixes) [reply frontend/src/lib/constants.ts:22]: I'll keep it where it now.

File: frontend/src/scenes/userLogic.tsx (hunk 10 above)
Comment (Twixes) [reply frontend/src/scenes/userLogic.tsx:127]: This is intentional, it was hard to debug this since the error was just eaten up, I'd rather it went to the console in addition to being handled by logic.

File: frontend/src/scenes/userLogic.tsx (hunk 11 above)
Comment (Twixes) [reply frontend/src/scenes/userLogic.tsx:122]: Well well wouldn't it be convenient to just do both things in one huge PR which would avoid that conflict… no, actually not, this is how I end up with overly large PRs.

File: posthog/api/organization.py (hunk 12 above)
Comment (Twixes) [reply posthog/api/organization.py:25]: Hm, I see, you can make an issue about this if you want.

File: posthog/models/organization.py (hunk 13 above)
Comment (Twixes) [reply posthog/models/organization.py:119]: This is to ensure there are no multiple owners at the same time. Originally I thought about adding foreign key `owner` to `Organization`, but decided that using the existing `OrganizationMembership` with a constraint will work better.

File: frontend/src/scenes/organization/Invites/CreateOrgInviteModal.tsx (hunk 5 above)
Comment (Twixes) [reply frontend/src/scenes/organization/Invites/CreateOrgInviteModal.tsx:50]: That's true

File: frontend/src/scenes/organization/CreateOrganizationModal.tsx (hunk 3 above)
Comment (Twixes) [reply frontend/src/scenes/organization/CreateOrganizationModal.tsx:18]: Yeah, better to just have `if (setIsVisible)` inside the function instead of using some no-op.

File: frontend/src/scenes/App.tsx (hunk 2 above)
Comment (Twixes) [reply frontend/src/scenes/App.tsx:51]: I'd keep it in the same place at the moment, since it's already been here forever.

File: frontend/src/scenes/UpgradeModal.tsx [hunk 19]
```diff
@@ -29,10 +29,23 @@ export function guardPremiumFeature(
     showUpgradeModal: (featureName: string) => void,
     key: string,
     name: string,
-    callback?: () => void
+    featureAvailableCallback?: () => void,
+    premiumEnvironments: {
```
[the remark this answers is not in the document]
Comment (Twixes) [reply frontend/src/scenes/UpgradeModal.tsx:33]: Renamed to `guardOn`.

[the remark this answers is not in the document]
Comment (Twixes) [reply frontend/src/scenes/UpgradeModal.tsx:33]: Hm, it's not always passed?

File: frontend/src/scenes/UpgradeModal.tsx [hunk 20]
```diff
@@ -29,10 +29,23 @@ export function guardPremiumFeature(
     showUpgradeModal: (featureName: string) => void,
     key: string,
     name: string,
-    callback?: () => void
+    featureAvailableCallback?: () => void,
```
[the remark this answers is not in the document]
Comment (Twixes) [reply frontend/src/scenes/UpgradeModal.tsx:32]: I'd actually say it is, since you will practically always want to use `featureAvailableCallback`, but not necessarily disable guard on self-hosted/cloud. Well, this wouldn't be an issue if JS had named parameters.
