### PR TITLE
Preliminary Cleanup for Insight Tooltips

### LINKED ISSUE #7370: Insight tooltips are painful
## Bug description

When hovering over a data point in an insight graph, tooltips are clunky. They don't show up unless you move the mouse around and are laggy.

## Expected behavior

Tooltips should feel very natural and intuitive.

## How to reproduce

1. Create any graph and play around with hovering near data points.

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [x] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context
- Should be tackled together with #5473, #5698 & #7369.

### PR DESCRIPTION
**Pull request by alexkim205**
## Changes

Preliminary cleanup for #7370. 

- [ ] Clean up `EntityPropertyFilter` and `InsightLabel` to get custom names, breakdown labels, and compare labels working again throughout the app.
- [ ] Introduce new `InsightTooltip` component behind FF `insight-tooltips`. Does not work yet, but wanted to get the FF and component out.

## How did you test this code?

- Manual QA for entity filters.
- Observe that old tooltip is used without new FF.

### CODE REVIEW

File: frontend/src/scenes/insights/InsightTabs/FunnelTab/FunnelStepsPicker.tsx [hunk 1]
```diff
@@ -33,7 +33,7 @@ export function FunnelStepsPicker(): JSX.Element | null {
                 <Select.Option key={stepIndex} value={stepIndex} label={`Step ${stepIndex + 1}`}>
                     <div style={{ display: 'flex', flexDirection: 'row' }}>
                         Step {stepIndex + 1} (
-                        <EntityFilterInfo filter={stepFilter as EntityFilter} showSubTitle={false} />)
```
Comment (rcmarron) [inline frontend/src/scenes/insights/InsightTabs/FunnelTab/FunnelStepsPicker.tsx:36]: Do we want to leave this as it? It looks a bit wonky with the 2 sets of parenthesis - don't feel that strongly though
image

File: frontend/src/lib/components/InsightLabel/index.tsx [hunk 2]
```diff
@@ -34,10 +35,8 @@ interface InsightsLabelProps {
     hasMultipleSeries?: boolean // Whether the graph has multiple discrete series (not breakdown values)
     showCountedByTag?: boolean // Force 'counted by' tag to show (always shown when action.math is set)
     allowWrap?: boolean // Allow wrapping to multiple lines (useful for long values like URLs)
-    useCustomName?: boolean // Whether to show new custom name. `{custom_name} ({id})`.
-    hideSeriesSubtitle?: boolean // Whether to show the base event/action name (if a custom name is set) in the insight label
+    hideCustomName?: boolean // Whether to show the base event/action name (if a custom name is set) in the insight label
```
Comment (rcmarron) [inline frontend/src/lib/components/InsightLabel/index.tsx:38]: I might be missing it, but I don't think we ever set this to true. Maybe we can simplify by just removing it?

File: frontend/src/lib/components/InsightLabel/index.tsx [hunk 3]
```diff
@@ -34,10 +35,8 @@ interface InsightsLabelProps {
...
     onLabelClick?: () => void // Click handler for inner label
-    swapTitleAndSubtitle?: boolean // If true, emphases on subtitle and title are switched.
```
Comment (rcmarron) [inline frontend/src/lib/components/InsightLabel/index.tsx:40]: Love the cleanup of these props

File: frontend/src/scenes/insights/InsightTooltip/InsightTooltip.tsx [hunk 4]
```diff
@@ -1,60 +1,50 @@
...
-            {bodyLines?.length > 0 && (
-                <ul>
-                    {bodyLines.map((line, index) => (
-                        <li key={line.id ?? index}>{line.component}</li>
-                    ))}
-                </ul>
-            )}
+        <div>
+            {!hideHeader && <div>{title}</div>}
+            {bodyLines.map(({ id, component }) => (
```
Comment (rcmarron) [inline frontend/src/scenes/insights/InsightTooltip/InsightTooltip.tsx:43]: Nit: `bodyLines` seems like a weird word here. It looks like it might have meaning inside LineGraph, but seems out of place in the context of this component. I wonder if something like `seriesInfo` could be more appropriate?

**Review by rcmarron — DISMISSED** [review]
Overall, a really great cleanup! A 2 smaller thoughts:

* I think the styling on the new tooltip might be a bit off.
image

* I don't have full context on the insights table, but my 2c is that it looks better if we remove the "Compare" column and instead use the "current"/"previous" pill on the `InsightLabel`. I think that would let us remove the `hideCompare` prop too.

**Comment by alexkim205** [comment]
Thanks for the quick review!

> * I think the styling on the new tooltip might be a bit off.

This ugliness was intentional for now. I just threw in all the data there for now and I'll make everything pretty later. I just wanted to get this new component in under a FF so that the next PR isn't deceptively large.

> * I don't have full context on the insights table, but my 2c is that it looks better if we remove the "Compare" column and instead use the "current"/"previous" pill on the `InsightLabel`. I think that would let us remove the `hideCompare` prop too.

Sure can do 👍

File: frontend/src/scenes/insights/InsightTabs/FunnelTab/FunnelStepsPicker.tsx (hunk 1 above)
Comment (alexkim205) [reply frontend/src/scenes/insights/InsightTabs/FunnelTab/FunnelStepsPicker.tsx:36]: Hm good find, I think it'd be best if we hide the custom name here. Maybe that prop _will_ come in handy after all!

File: frontend/src/scenes/insights/InsightTooltip/InsightTooltip.tsx (hunk 4 above)
Comment (alexkim205) [reply frontend/src/scenes/insights/InsightTooltip/InsightTooltip.tsx:43]: yup i like that a lot better

**Review by rcmarron — APPROVED** [review]
LGTM - one last small thought. On the `FunnelStepsPicker.tsx`, what if we just removed the parenthesis around the name? Maybe we replace it with a colon, so it would be 'Step 1: CustomName (Pageview)'. That way it's consistent with other labels, and we can remove the `hideCustomName` prop too.

**Comment by rcmarron** [comment]
Also, I'm guessing the 1.31.0 label isn't supposed to be on this?

**Comment by alexkim205** [comment]
> LGTM - one last small thought. On the `FunnelStepsPicker.tsx`, what if we just removed the parenthesis around the name? Maybe we replace it with a colon, so it would be 'Step 1: CustomName (Pageview)'. That way it's consistent with other labels, and we can remove the `hideCustomName` prop too.

good idea! This is how it looks like now


Screen Shot 2021-12-17 at 3 54 34 PM
