### PR TITLE
Preload chunks when loading scenes

### LINKED ISSUE #6821: Slowness loading pages with new esbuild
## In what situation are you experiencing subpar performance?

App navigation now feels noticeably slower when loading new pages for the first time. One time it even took more than 6s, and because there's no loader, it feels like something is broken. A recording that doesn't look too drastic:

image

## How to reproduce

See recording above.

## Environment

- [X] PostHog Cloud

## Additional context
Originally posted on https://github.com/PostHog/product-internal/issues/220. Moving here.

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Fixes https://github.com/PostHog/posthog/issues/6821
- Caches information on what chunks each scene (and the index) needs
- Loads all the chunks when loading any scene, instead of waiting for the scene's index to load, and only then loading the rest of the chunks.

## How did you test this code?

- Tried building locally, and saw that both the initial chunks, and the loaded scenes load all files together:

Screenshot 2021-11-08 at 12 53 36

Screenshot 2021-11-08 at 12 54 24

### CODE REVIEW

**Comment by mariusandra** [comment]
This also fixes the "esbuild fails when any of the initial chunks are missing" error. Now "index.js" is always loaded with the current timestamp, so always redownloaded. It's a small ~10kb file, so we'll survive. The chunk metadata might get out of sync, but then the page will just be a little bit slower, no big deal.

File: frontend/utils.mjs [hunk 1]
```diff
@@ -48,18 +48,37 @@ export function copyPublicFolder() {
...
+export function copyIndexHtml(from = 'src/index.html', to = 'dist/index.html', entry = 'index', chunks = {}) {
     const timestamp = new Date().valueOf()
+
     fse.writeFileSync(
         path.resolve(__dirname, to),
-        fse
-            .readFileSync(path.resolve(__dirname, from), { encoding: 'utf-8' })
-            .replace(
-                '</head>',
-                `<script type="module" src="${isDev ? jsURL : ''}/static/${entry}.js?${timestamp}"></script>\n` +
```
Comment (pauldambra) [inline frontend/utils.mjs:60]: We're serving these assets (and chunks) with `Cache-Control: public, max-age=0`
Screenshot 2021-11-09 at 09 55 19
Screenshot 2021-11-09 at 09 55 10
Screenshot 2021-11-09 at 09 55 27

So, browsers aren't actually caching this. And even though we're serving an e-tag in responses our requests don't have `if-match` or `if-none-match` so we're still downloading the content even though we have it in memory.

I don't think that necessarily blocks this PR but we should be serving these assets with `Cache-Control: max-age=365000000, immutable` so that browsers know they can keep these forever

**Review by pauldambra — APPROVED** [review]
not requesting changes cos the only important thing can follow-up to this (but I'm 99% certain we're not caching these assets - and that 1% has never bit me before :))

File: frontend/utils.mjs (hunk 1 above)
Comment (mariusandra) [reply frontend/utils.mjs:60]: Well, I agree with all of this, but 

1) whatever `localhost:8234` returns is good, since we don't want any cache in the local dev server
2) whatever `localhost:8000` returns might be ignored anyway. Also, is this django after a full build and `collectstatic`, running [in production mode](https://github.com/PostHog/posthog/blob/9a4062e289da1fe5b770e76e968a4183424e6d25/posthog/settings.py#L264)? 

On app.posthog.com, a single reload definitely does not make network requests to fetch these static assets:

image

There's also another issue here. Django's `collectstatic` re-hashes the files, and actually publishes them twice. Once as they are, and once with another `-someotherhash.js` appended to the end... 🤔

File: frontend/utils.mjs [hunk 2]
```diff
@@ -48,18 +48,37 @@ export function copyPublicFolder() {
         }
     })
 }
-
-export function copyIndexHtml(from = 'src/index.html', to = 'dist/index.html', entry = 'index') {
+export function copyIndexHtml(from = 'src/index.html', to = 'dist/index.html', entry = 'index', chunks = {}) {
     const timestamp = new Date().valueOf()
```
[the remark this answers is not in the document]
Comment (mariusandra) [reply frontend/utils.mjs]: sure, changed

File: frontend/build.mjs [hunk 3]
```diff
@@ -27,7 +36,7 @@ await Promise.all([
         format: 'esm',
         outdir: path.resolve(__dirname, 'dist'),
         onBuildStart: pauseServer,
-        onBuildComplete: resumeServer,
+        onBuildComplete: onBuildComplete,
```
[the remark this answers is not in the document]
Comment (mariusandra) [reply frontend/build.mjs:39]: ah... I was going for "aesthetics" here, since every key has a value looks neater than every key except one having a value... 🦀 🤷 🤣

File: frontend/utils.mjs (hunk 1 above)
Comment (pauldambra) [reply frontend/utils.mjs:60]: the-simpsons-homer-simpson
