### PR TITLE
fix(lemon-ui): Update lemon input select to use virtualized list

### LINKED ISSUE #34681: Unable to select time zones other than in Africa and America
### Bug Description

In *Settings > Project > Date & time > Time zone* the drop down menu only contains options for Africa and America. There's nothing for Europe, Asia, or Oceania. I've encountered it using Safari and Chome on macOS and Firefox and Chrome on Android.

This screenshot shows the bottom of the drop down menu.

Image

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/0197e8b9-81ae-70ae-b982-7e22d220f8cf?t=792
Admin: http://go/adminOrgUS/0195e7f4-ce22-0000-d2f9-2fe68432f768 (project ID 142336)
```

### PR DESCRIPTION
**Pull request by lshaowei18**
> [!IMPORTANT]
> 👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Problem

Closes #34681

The timezones that are shown was limited to 100 due to a quick fix as it was getting slower after about ~10k rows. 

## Changes

Made the rendering of `visibleOptions` a virtualized list:

https://github.com/user-attachments/assets/57d1731e-dc63-4d9e-8542-ec95325c5363

This is my first time using this virtualized library, so please do point out any things that can be improved!

## Did you write or update any docs for this change?
- [x] No docs needed for this change

## How did you test this code?

Locally. I did a test where i loaded `visibleOptions` with > 10k options, it didn't slow down the performance. However if you navigate too fast with the scrollbar the items might not appear.

### CODE REVIEW

File: frontend/src/lib/lemon-ui/LemonInputSelect/LemonInputSelect.tsx [hunk 1]
```diff
@@ -472,57 +469,84 @@ export function LemonInputSelect({
...
+                                                    }
+                                                >
+                                                    <span className="whitespace-nowrap ph-no-capture truncate">
+                                                        {!option.__isInput
+                                                            ? option.labelComponent ?? option.label // Regular option
+                                                            : mode === 'multiple'
+                                                            ? `Add "${option.key}"` // Input-based option
+                                                            : option.key}
+                                                    </span>
+                                                </LemonButton>
```
[the remark this answers is not in the document]
Comment (lshaowei18) [reply frontend/src/lib/lemon-ui/LemonInputSelect/LemonInputSelect.tsx]: Hmmmm I don't think this is true; although it might be a possibility that `LemonButton` does not include the `style` prop. (I checked, it does include)

File: frontend/src/lib/lemon-ui/LemonInputSelect/LemonInputSelect.tsx [hunk 2]
```diff
@@ -472,57 +469,84 @@ export function LemonInputSelect({
...
-                                        {!option.__isInput
-                                            ? option.labelComponent ?? option.label // Regular option
-                                            : mode === 'multiple'
-                                            ? `Add "${option.key}"` // Input-based option
-                                            : option.key}
-                                    </span>
-                                </LemonButton>
-                            )
-                        })
+                        <div className="min-h-[420px]">
```
Comment (Twixes) [inline frontend/src/lib/lemon-ui/LemonInputSelect/LemonInputSelect.tsx]: This min height is new. What happens now when the select has just a couple items?

**Review by Twixes — COMMENTED** [review]
Makes sense at a glance for me (left a height comment), but will let @PostHog/devex ultimately approve, as I'm not on the component library side of things anymore much

File: frontend/src/lib/lemon-ui/LemonInputSelect/LemonInputSelect.tsx (hunk 2 above)
Comment (lshaowei18) [reply frontend/src/lib/lemon-ui/LemonInputSelect/LemonInputSelect.tsx]: Hey @Twixes, thanks for the review. Shouldn't have blindly copied the value from another component, my bad. 

You made a good point, I have now updated the component to calculate dynamically based on the number of items in the select.

Screenshot 2025-07-11 at 9 57 34 AM

**Comment by lshaowei18** [comment]
Hi @mariusandra , I have updated the following:

1) The virtualized item's height is now set to `33`, which i believe is the same as the button size small.
2) I have added an optional prop `virtualized`

Great feedback, appreciate it; i definitely think this is way safer.

**Review by adamleithp — APPROVED** [review]

**Comment by adamleithp** [comment]
Well done looks great
