### PR TITLE
Fix feature flag edit page load

### LINKED ISSUE #7066: Feature flags - the detail page doesn't show any details
## Bug description
When editing a feature flag the data/fields are not populated. If you then navigate back to the list page and edit again the second time around the fields are populated. It also happens when refreshing on the edit page as well as when navigating to the page via a direct URL.

https://user-images.githubusercontent.com/4038041/141303819-2c8d32a7-3ec7-46d0-a1ed-6aedf33e9e3e.mov

This issue seems to be present in both the old and new design.

## Expected behavior
The feature flag data/fields are populated when I open the page

## How to reproduce

1. Create a feature flag with a name and a description
1. Open the URL pointing to it (e.g. https://app.posthog.com/feature_flags/1234)

## Environment

- [X] PostHog Cloud
- [X] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context
See [this thread](https://posthogusers.slack.com/archives/C01PPBY3G6Q/p1636566908068000) in Slack

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Simpler verison of https://github.com/PostHog/posthog/pull/7070 (closes https://github.com/PostHog/posthog/pull/7070)
- Closes https://github.com/PostHog/posthog/issues/7066

## How did you test this code?

- Hitting reload started to work

### CODE REVIEW

File: frontend/src/scenes/feature-flags/featureFlagLogic.tsx [hunk 1]
```diff
@@ -294,10 +294,12 @@ export const featureFlagLogic = kea<featureFlagLogicType>({
                     ?.values.featureFlags.find((flag) => flag.id === parsedId)
                 if (foundFlag) {
                     actions.setFeatureFlag(foundFlag)
-                    actions.loadFeatureFlag() // reload cache
                 } else {
                     actions.setFeatureFlag(NEW_FLAG)
                 }
+                if (id !== 'new') {
+                    actions.loadFeatureFlag()
+                }
```
Comment (Twixes) [inline frontend/src/scenes/feature-flags/featureFlagLogic.tsx:302]: Doesn't this remove the turboness just like #7070?

**Review by Twixes — APPROVED** [review]
