### PR TITLE
Fix retention "load more" people

### LINKED ISSUE #3071: Load More People under retention list of users doesn't work
## How to reproduce

1. Go to our [internal retention dashboard](https://app.posthog.com/dashboard/501)
2. Scroll to bottom
3.Click Load More People
4. Error in console:
Screenshot 2021-01-25 at 11 53 57

Either there are no more people in which case the button shouldn't appear, or there are more people and there's a problem retrieving them.

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

### PR DESCRIPTION
**Pull request by macobo**
- Fix retention `loadMore`, #3071
- Retention table to tsx

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

File: frontend/src/scenes/retention/RetentionTable.tsx [hunk 1]
```diff
@@ -60,10 +61,12 @@ export function RetentionTable({ dashboardItemId = null }) {
         })
     }
 
-    function dismissModal() {
+    function dismissModal(): void {
         setModalVisible(false)
     }
 
+    console.log(people)
```
Comment (EDsCODE) [inline frontend/src/scenes/retention/RetentionTable.tsx:68]: 🖨

**Review by EDsCODE — APPROVED** [review]
thanks for the catch
