### PR TITLE
fix: replay timestamps

### LINKED ISSUE #21834: In Session Replay, Incorrect time shown when displayed in Local Timezone
## Bug description

In Session Replay, there is an option to click on the Timestamp shown below the recording. The clicking action changes the display to, first UTC, then the Local Timezone.

But, currently, the timestamp shown for the Local Timezone is incorrect. Even though the GMT difference gets suffixed to the timestamp, the value shown is that of UTC.

https://github.com/PostHog/posthog/assets/64059154/60753aa3-74b8-43d0-87e4-418626e7bc45

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018f12e8-cdb3-7189-8c68-eea16cdbfe66?t=86 (at https://us.posthog.com/project/25014/replay/recent?simpleFilters=%7B%22events%22%3A%5B%5D%2C%22properties%22%3A%5B%5D%7D&advancedFilters=%7B%22session_recording_duration%22%3A%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A1%2C%22operator%22%3A%22gt%22%7D%2C%22properties%22%3A%5B%5D%2C%22events%22%3A%5B%5D%2C%22actions%22%3A%5B%5D%2C%22date_from%22%3A%22-7d%22%2C%22date_to%22%3Anull%2C%22console_logs%22%3A%5B%5D%2C%22console_search_query%22%3A%22%22%7D&sessionRecordingId=018f1063-0e80-7dbd-bc07-14a5f2fbb8dc#panel=support%3Asupport%3A%3A)
Admin: http://go/adminOrgUS/0187b702-5209-0000-78da-31578b9ab4b0 (Project: 25014)
Sentry: http://go/sentryUS/25014
```

### PR DESCRIPTION
**Pull request by daibhin**
## Problem

Closes https://github.com/PostHog/posthog/issues/21834
Addresses https://posthog.slack.com/archives/C03PB072FMJ/p1714032531933589

## Changes

Switch button to use monospaced font to stop jumping

----

On top of the issue called out by the customer the inspector timestamps did not match the player toggle

|Before|After|
|----|----|
| Screenshot 2024-04-29 at 18 00 37 | Screenshot 2024-04-29 at 18 04 04 |

----

Also fixes a performance issue given the `TZLabel` assumes that the timestamp is always changing which means unnecessary intervals being computed every second. And recomputes the timezone every second, for every timestamp on the page:

timer

Luckily for us the inspector is a virtualized list or the number of intervals would be much greater.

You can see the blips in CPU every second as these timers are processed (even when the recording is paused). Afterwards the CPU line looks flat.
|Before|After|
|----|----|
| Screenshot 2024-04-29 at 17 42 47 | Screenshot 2024-04-29 at 18 06 08 |

(Fix for the `TZLabel` component coming in a future PR)

### CODE REVIEW

File: frontend/src/scenes/session-recordings/player/utils/timestamp.ts [hunk 1]
```diff
@@ -0,0 +1,5 @@
+import { dayjs } from 'lib/dayjs'
+
+export const formattedTimestamp = (currentTimestamp: dayjs.Dayjs): string => {
```
Comment (pauldambra) [inline frontend/src/scenes/session-recordings/player/utils/timestamp.ts:3]: this isn't being called?

**Review by pauldambra — APPROVED** [review]
assuming we delete or call the new formattedTimestamp method

File: frontend/src/scenes/session-recordings/player/utils/timestamp.ts (hunk 1 above)
Comment (daibhin) [reply frontend/src/scenes/session-recordings/player/utils/timestamp.ts]: Sorry, hang over from trying to share logic before I realized the two timestamps were similar but different in what they needed. Gone now
