### PR TITLE
fix: Funnel persons

### LINKED ISSUE #10691: Persons modal scoped when it shouldn't when in funnel breakdown
## Bug description

Clicking any of the succeeded or dropped off persons (for all data) opens a modal with a specific value applied:

Somewhat related: it's not obvious that there are more than 5 possible breakdown values.

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem

Couple of bugs in new PersonsModal (and old one)
Closes https://github.com/PostHog/posthog/issues/10691

## Changes

* Don't make the first dropped off step clickable (it will always have 0 persons)
* Set the "Completed/Dropped off" and step number text explicitly rather than the implicit way from before
* Correct missing_persons response
* Made sure all modal popups are disabled if viewed in a dashboard

Screenshot 2022-09-05 at 16 41 48

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

Just locally. A bit tricky to add a good test seeing as how nested it is...

### CODE REVIEW

File: frontend/src/scenes/funnels/funnelLogic.ts [hunk 1]
```diff
@@ -1250,9 +1251,8 @@ export const funnelLogic = kea<funnelLogicType>({
         clearFunnel: ({}) => {
             actions.setFilters({ new_entity: values.filters.new_entity }, false, true)
         },
-        openPersonsModalForStep: ({ step, converted }) => {
-            // DEPRECATED
-            if (!values.isModalActive) {
+        openPersonsModalForStep: ({ step, stepIndex, converted }) => {
+            if (!values.isViewedOnDashboard) {
```
Comment (Twixes) [inline frontend/src/scenes/funnels/funnelLogic.ts:1255]: Why would `openPersonsModalForStep` be called if we're on a dashboard though? In that case there should be just no `onClick` handler I'd say

File: frontend/src/scenes/funnels/funnelLogic.ts [hunk 2]
```diff
@@ -1263,10 +1263,9 @@ export const funnelLogic = kea<funnelLogicType>({
                 openPersonsModal({
                     url: converted ? step.converted_people_url : step.dropped_people_url,
                     title: funnelTitle({
-                        step: converted ? step.order : -step.order,
-                        breakdown_value: breakdownValues.isEmpty
-                            ? undefined
-                            : breakdownValues.breakdown_value.join(', '),
+                        converted,
+                        // Note - when in a legend the stepIndex is used instead
+                        step: typeof stepIndex === 'number' ? stepIndex + 1 : step.order + 1,
```
Comment (Twixes) [inline frontend/src/scenes/funnels/funnelLogic.ts:1268]: Why so?

File: frontend/src/scenes/trends/persons-modal/persons-modal-utils.tsx [hunk 3]
```diff
@@ -17,14 +17,15 @@ import { InsightLabel } from 'lib/components/InsightLabel'
 import { getBarColorFromStatus, getSeriesColor } from 'lib/colors'
 
 export const funnelTitle = (props: {
-    step: number
+    converted: boolean
+    step?: number
```
Comment (Twixes) [inline frontend/src/scenes/trends/persons-modal/persons-modal-utils.tsx:21]: In what situation is this undefined?

**Review by Twixes — DISMISSED** [review]

**Comment by Twixes** [comment]
+1 to the fixes, I'm a bit concerned about `isViewedOnDashboard` – it seems this behavior would be more obvious at the component level. Also, there's some logic test failing.

File: frontend/src/scenes/funnels/funnelLogic.ts (hunk 2 above)
Comment (benjackwhite) [reply frontend/src/scenes/funnels/funnelLogic.ts:1268]: I'm not sure but its something to do with the series stuff. It passes in the "baseline" step which for somereason always has an `.order` of 0. So the stepIndex was the cleanest workaround I could find

File: frontend/src/scenes/trends/persons-modal/persons-modal-utils.tsx (hunk 3 above)
Comment (benjackwhite) [reply frontend/src/scenes/trends/persons-modal/persons-modal-utils.tsx]: Hmmm I thought about this a little deeper. I was trying to keep the bad logic of before but now that this function is more "pure" the step can always just be given as it should be. Corrected 👍

File: frontend/src/scenes/funnels/funnelLogic.ts (hunk 1 above)
Comment (benjackwhite) [reply frontend/src/scenes/funnels/funnelLogic.ts]: I think it's just there is a lot of places where it is called so it is cleaner to have it here than in the dozens of places where the click handler is. Isn't that the benefit of a logic 😅 ?

File: frontend/src/scenes/funnels/funnelLogic.ts (hunk 2 above)
Comment (benjackwhite) [reply frontend/src/scenes/funnels/funnelLogic.ts]: Improved the comment (although I still don't know why it is this way...)

File: frontend/src/scenes/funnels/FunnelBarGraph.tsx [hunk 4]
```diff
@@ -279,7 +279,7 @@ export function FunnelBarGraph(props: ChartParams): JSX.Element {
         visibleStepsWithConversionMetrics: steps,
         stepReference,
         aggregationTargetLabel,
-        isModalActive,
+        isViewedOnDashboard,
```
Comment (pauldambra) [inline frontend/src/scenes/funnels/FunnelBarGraph.tsx:282]: nit: is this better as `isInDashboardContext`?

Viewed feels like a report rather than a state

File: frontend/src/scenes/trends/persons-modal/PersonsModalV2.tsx [hunk 5]
```diff
@@ -107,8 +107,8 @@ function PersonsModalV2({ url: _url, urlsIndex, urls, title, onAfterClose }: Per
                             <span>
                                 {actorsResponse?.next ? 'More than ' : ''}
                                 <b>
-                                    {actorsResponse?.total_count} unique{' '}
-                                    {actorsResponse?.total_count === 1 ? actorLabel.singular : actorLabel.plural}
+                                    {actors.length || 'No'} unique{' '}
```
Comment (pauldambra) [inline frontend/src/scenes/trends/persons-modal/PersonsModalV2.tsx:110]: there's a `pluralize` function that could be used here https://github.com/PostHog/posthog/blob/master/frontend/src/lib/utils.tsx#L1132

**Review by pauldambra — APPROVED** [review]
couple of nits but...

File: frontend/src/scenes/funnels/FunnelBarGraph.tsx (hunk 4 above)
Comment (benjackwhite) [reply frontend/src/scenes/funnels/FunnelBarGraph.tsx:282]: Ooh yeah I like that. May as well make the change now

File: frontend/src/scenes/trends/persons-modal/PersonsModalV2.tsx (hunk 5 above)
Comment (benjackwhite) [reply frontend/src/scenes/trends/persons-modal/PersonsModalV2.tsx:110]: I actually wondered about that function... Not sure if it is actually simpler than the more straightforward tertiary but happy to swap it over for now
