### PR TITLE
PEMDAS, Performance Optimization, and a small UI bug

### LINKED ISSUE #5570: Extra request when switching from Left to right / top bottom funnel
## In what situation are you experiencing subpar performance?
When looking at a funnel from left to right, if I switch the view to top to bottom – we make a second request and recalculate the funnel.

I don't think any information changes between what we show for both of these visualizations, so we shouldn't need to send a request to the backend when switching these views.

## How to reproduce

1. Create a funnel 
2. Open network tab
3. Switch funnel to top-bottom, observe a request to /funnels

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context
There might be a good reason we need to do this, but ideally we don't send an extra request. I think we should have all the data on the client already.

### LINKED ISSUE #5575: >> 100% conversion rates
## Bug description

Screen Shot 2021-08-12 at 12 50 14 PM

plus a pesky border left bug in the conversion metrics

## Expected behavior

<= 100% rate expected

## How to reproduce

https://app.posthog.com/insights?insight=FUNNELS&properties=%5B%5D&filter_test_accounts=true&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%5D&actions=%5B%5D&interval=day&new_entity=%5B%5D&funnel_viz_type=time_to_convert&display=FunnelViz

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

### PR DESCRIPTION
**Pull request by alexkim205**
## Changes

Fixes #5570
Fixes #5575

- [x] Don't make separate request when changing funnel step layouts
- [x] Funnel step calculations were >> 100% due to PEMDAS error where we were passing in only numerator to `formatDisplayPercentage`
- [x] Don't show divider if <2 funnel metric labels
- [x] Move breakpoint to right place

Before

Screen Shot 2021-08-12 at 12 50 14 PM

After

Screen Shot 2021-08-12 at 2 22 38 PM

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

**Review by liyiy — APPROVED** [review]

File: frontend/src/scenes/funnels/funnelLogic.ts [hunk 1]
```diff
@@ -187,6 +186,18 @@ export const funnelLogic = kea<funnelLogicType>({
                         return EMPTY_FUNNEL_RESULTS
                     }
 
+                    // Don't load results if layout was the only thing changed
+                    if (
+                        equal(
+                            Object.assign({}, values.filters, { layout: undefined }),
```
Comment (kpthatsme) [inline frontend/src/scenes/funnels/funnelLogic.ts:192]: quick q: why do we need to assign anything to layout at all if we are only comparing filters? does values.filters contain a `layout` key as well?

File: frontend/src/scenes/funnels/FunnelCanvasLabel.tsx [hunk 2]
```diff
@@ -15,44 +15,58 @@ export function FunnelCanvasLabel(): JSX.Element | null {
     const { conversionMetrics, clickhouseFeaturesEnabled } = useValues(funnelLogic)
     const { allFilters } = useValues(insightLogic)
     const { setChartFilter } = useActions(chartFilterLogic)
+    const showTotal = allFilters.funnel_viz_type === FunnelVizType.Steps
+    const showAverage = allFilters.funnel_viz_type !== FunnelVizType.Trends && !allFilters.breakdown
```
Comment (kpthatsme) [inline frontend/src/scenes/funnels/FunnelCanvasLabel.tsx:19]: nit: i feel like parens would make this more readable

File: frontend/src/scenes/funnels/funnelLogic.ts (hunk 1 above)
Comment (alexkim205) [reply frontend/src/scenes/funnels/funnelLogic.ts:192]: Yup, both `values.filters` and `values.lastAppliedFilters` contain layout keys (see param [here](https://github.com/PostHog/posthog/pull/5576/files/e9ab8fdb5b0dca33780174fe85cdd531e5743632#diff-92e32501a6b77e6bdff549cb4f721a309c1b5fd3df14615dc6969315b66041dcL112)). By assigning the layout to undefined, I'm normalizing layouts across both objects so that any layout differences here are canceled out.

**Comment by paolodamico** [comment]
Looks like this was already approved by @liyiy, so skipping review.
