### PR TITLE
fix(insights): Fix breakdown limit saving in trends

### LINKED ISSUE #21311: breakdown limit is not savable
## Bug description

It's not possible to change the breakdown limit permanently

2024-04-03 at 18 59 57

## How to reproduce

1. Create an insight with a breakdown
2. Save the insight
3. Edit the breakdown limit
4. Try to save that change

### PR DESCRIPTION
**Pull request by webjunkie**
## Problem

Fixes #21311

## Changes

- a local default of `25` was used in logic before the value in filter 🤦🏻 
- but even after fixing this, turns out filter conversion did not include the limit 🙃 

## Does this work well for both Cloud and self-hosted?

No

## How did you test this code?

- UI and tests

### CODE REVIEW

File: frontend/src/types.ts [hunk 1]
```diff
@@ -1946,6 +1946,8 @@ export interface FilterType {
     breakdowns?: Breakdown[]
     breakdown_group_type_index?: number | null
     breakdown_hide_other_aggregation?: boolean | null
+    /** @asType integer */
+    breakdown_limit?: number | null
```
Comment (thmsobrmlr) [inline frontend/src/types.ts:1950]:
```suggestion
    breakdown_limit?: integer | null
```
We have a type alias for integers in the schema.

**Review by thmsobrmlr — APPROVED** [review]
Great, thanks!

File: frontend/src/types.ts (hunk 1 above)
Comment (webjunkie) [reply frontend/src/types.ts:1950]: Yeah, but not in the `types.ts` and if I export it, it totally changes all references in the schema.json 🙈  which is not ideal. Hence I just did it like this.

Comment (thmsobrmlr) [reply frontend/src/types.ts:1950]: Ah sorry, didn't see that this is `types.ts`. All good then!
