### PR TITLE
Navigation 1775 improvements & fixes

### LINKED ISSUE #2541: Error on creating a new account
## Bug description

I was creating a new account on PostHog cloud in incognito with these credentials:

Screenshot 2020-11-27 at 10 33 58

I got this error:

Screenshot 2020-11-27 at 10 32 45

## Expected behavior

No error messages on signing up fresh.

### LINKED ISSUE #2545: New navigation doesn't include certain pages
## Bug description

The new navigation is missing a few options: 
- Team members
- Invites
- Licenses
- Annotations

Also because settings is a menu item I was confused about organization settings being top right. That page is also blank.

I've rolled back the rollout of this in the mean time and just turned it on for us.

## How to reproduce

1. 
2. 
3. 

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

- Closes #2541
- Closes #2545.
    - Billing (cloud only) / licenses (self-hosted only) link in the right navigation bar.
    - Org settings now opens team member settings (as there are no other organization settings at this time).
    - Added annotations to the main nav bar.
- Adds the "Back to" links when the new navigation is active.

## Checklist

- [X] All querysets/queries filter by Organization, by Team, and by User
- [X] Django backend tests
- [X] Jest frontend tests
- [X] Cypress end-to-end tests

### CODE REVIEW

File: frontend/src/scenes/instance/SystemStatus/systemStatusLogic.ts [hunk 1]
```diff
@@ -17,6 +18,10 @@ export const systemStatusLogic = kea<systemStatusLogicType<SystemStatus>>({
             [] as SystemStatus[],
             {
                 loadSystemStatus: async () => {
+                    const { user } = userLogic.values
+                    if (user?.is_multi_tenancy && !user.is_staff) {
+                        return []
+                    }
                     return (await api.get('_system_status')).results
```
Comment (macobo) [inline frontend/src/scenes/instance/SystemStatus/systemStatusLogic.ts:25]: Why this change?

If we want to limit access it would make more sense to do this at the api level.

Comment (paolodamico) [reply frontend/src/scenes/instance/SystemStatus/systemStatusLogic.ts:25]: This is what fixes #2541. We already have this limitation in the backend (https://github.com/PostHog/posthog/blob/bf506e3d0b8038c164b70842385040d5037f641e/posthog/views.py#L49), however because we were calling the endpoint, we were showing an unnecessary error.

**Review by macobo — APPROVED** [review]

**Comment by macobo** [comment]
Tested things out, works great!
