### PR TITLE
fix(experiments): Don't rerender on every input change

### LINKED ISSUE #18717: Experiment flag key input rerenders on every keystroke
## Bug description

The title explains it, the inputs rerender on every keystroke.

https://github.com/PostHog/posthog/assets/5406212/91f4c679-1c0c-4ecb-aee0-98bc3ad17671

## How to reproduce

1. Create an experiment
2. Fill in the flag keys
3. After every keystroke, you have to re-focus

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/settings/project-details#variables]
- [x] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

### PR DESCRIPTION
**Pull request by neilkakkar**
## Problem

Fixes https://github.com/PostHog/posthog/issues/18717

For some reason I can't reproduce this locally, but I suspect what's happening is that the key here used to get converted to `[object Object]` so it wouldn't change when the variant key changes.

With the update in https://github.com/PostHog/posthog/pull/18662/files#diff-167e770c0c7fa3176a6e914200d9683f3b2b41ae8233f726eefb3b684cbadf5f to move to new ESLint rules, this bug was exposed, and now the `key` changes every time you input the variant key.

This should ensure we don't re-render.

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

File: frontend/src/scenes/experiments/Experiment.tsx [hunk 1]
```diff
@@ -244,13 +244,13 @@ export function Experiment(): JSX.Element {
...
                                             <div className="variants">
-                                                {experiment.parameters.feature_flag_variants?.map((variant, index) => (
+                                                {experiment.parameters.feature_flag_variants?.map((_, index) => (
                                                     <Group
                                                         key={index}
                                                         name={['parameters', 'feature_flag_variants', index]}
                                                     >
                                                         <div
-                                                            key={`${variant.key}-${index}`}
+                                                            key={`variant-${index}`}
```
Comment (Twixes) [inline frontend/src/scenes/experiments/Experiment.tsx:253]: Yeah, this should fix it.
Though I don't see why there's a key here at all. Normally there shuold be a key on the outermost mapped element, but its children don't need one for anything. So here, `<Group>` should be keyed, but not this inner div. Unless I'm missing something tricky here?

**Review by Twixes — APPROVED** [review]
