### PR TITLE
fix: deleted cohort navigation experience

### LINKED ISSUE #38670: Bug: fix deleted cohort navigation experience
### Bug Description

If a user deletes a cohort, the URL ends up still being valid, and they can navigate back to that cohort by either directly navigating to the URL or by following a link (e.g. clicking the link to the cohort in a feature flag condition). This is confusing UX, since the cohort will be only read-only (any attempts to edit or save it will fail), and there's nothing obvious in the UI that indicates the cohort is even deleted in the first place.

We should either:
- not let users navigate to deleted cohorts (show some sort of obvious UI experience that says the cohort has been deleted). In this situation, we should also handle the original cohort links in the feature flag filters – e.g. either delete the filter when a cohort is deleted, have some indication on the link that it points to a dead cohort, etc.
- keep the linking alive but have some obvious "deleted" UI for the cohort that doesn't let you do any operations except "restore it", or something like that.

## How to reproduce

1. create a cohort
2. create a feature flag that targets this cohort with a release
3. delete the cohort
4. go back to the feature flag, and click the link to the cohort in the release condition

## Additional context

Somewhat related to https://github.com/PostHog/posthog/issues/38610 – the UX around deleted cohorts, _especially_ when they appear in release condition filters for feature flags, is not great atm

also relates to https://posthog.slack.com/archives/C086VJD7708/p1758727941837359

### PR DESCRIPTION
**Pull request by yazan-abu-obaideh**
Closes #38670 

Changes:

- Make it clear on the UI when a cohort has been deleted

Screenshot from 2025-09-27 09-59-59

- Restore button

[Screencast from 2025-09-27 10-40-30.webm](https://github.com/user-attachments/assets/c4fc427e-be44-44dc-97ae-02cc44d8c010)

### CODE REVIEW

File: frontend/src/scenes/cohorts/CohortEdit.tsx [hunk 1]
```diff
@@ -121,6 +122,25 @@ export function CohortEdit({ id }: CohortLogicProps): JSX.Element {
...
+                            restoreCohort()
+                        }}
+                        menuItem
+                    >
+                        <IconRefresh /> Restore
+                    </ButtonPrimitive>
+                </ScenePanel>
+            </div>
+        )
+    }
```
Comment (Twixes) [inline frontend/src/scenes/cohorts/CohortEdit.tsx:152]: @adamleithp @mariusandra Should we introduce a standard "Restore" banner pattern like this, or instead enforce `<NotFound ...` here?

Comment (adamleithp) [reply frontend/src/scenes/cohorts/CohortEdit.tsx:152]: Let me explore this today!

**Review by adamleithp — APPROVED** [review]
nice @yazan-abu-obaideh thanks for this! I will work on a standard banner/other UX that we can apply elsewhere
