### PR TITLE
fix: flagPropertyErrors reducer return undefined

### LINKED ISSUE #27551: Reducer "flagPropertyErrors" returned undefined for action set flag property error
## Bug description

Replay: https://us.posthog.com/project/2/error_tracking/fe2eb461-962d-4670-936c-7206f02dcb15

Potentially related to https://github.com/PostHog/posthog/pull/27139

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables or https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

### PR DESCRIPTION
**Pull request by lucasheriques**
## Problem

this reducer doesn't expect an `undefined`, it expects a `null` instead

Closes https://github.com/PostHog/posthog/issues/27551

## How did you test this code?

Locally tested if error is no longer happening after changing survey's display conditions

### CODE REVIEW

File: frontend/src/scenes/surveys/surveyLogic.tsx [hunk 1]
```diff
@@ -639,7 +639,7 @@ export const surveyLogic = kea<surveyLogicType>([
                 iteration_count: NEW_SURVEY.iteration_count,
                 iteration_frequency_days: NEW_SURVEY.iteration_frequency_days,
             })
-            actions.setFlagPropertyErrors(NEW_SURVEY.targeting_flag_filters)
+            actions.setFlagPropertyErrors(null)
```
Comment (marandaneto) [inline frontend/src/scenes/surveys/surveyLogic.tsx:642]: what if `NEW_SURVEY.targeting_flag_filters` isn't undefined? will that cause another bug?

Comment (lucasheriques) [reply frontend/src/scenes/surveys/surveyLogic.tsx:642]: the problem here is that we're using an `undefined` value for something that expects either an `errors` or `null`

it's also not related to the `targeting_flag_filters` value, because that is defined in the [line above](https://github.com/PostHog/posthog/pull/27705/files/ebfc587bca0fbe9c4d6443002e9a6909dc509ad5#diff-0a051008afcf371e7c0f56a8f251f7d5fd2b20c2c8b491d1b4bd157347e593c9R632)

**Review by marandaneto — APPROVED** [review]
