### PR TITLE
fix: Bad UI when cohort is calculating

### LINKED ISSUE #30813: Bug: Bad edit UX while a cohort is updating
## Bug description

If you make edits to a cohort while it is updating and fail to click save, your edits will be lost when the update finishes.

## How to reproduce

An easy way to reproduce this is
1. Duplicate a cohort and see that it starts to calculate
2. Make some edits - e.g. title description (this is natural to do as sometimes it can take quite a while for a new cohort to calculate)
3. At this point it's not really clear that you should, or even can, save the edits (save is not clicked in the recording below)
4. Don't save the edits and wait for cohort to finish calculating
5. On finish see that your edits are lost and reverted to the original properties

https://github.com/user-attachments/assets/30b11db4-dbfb-4205-8b83-318f09beb35c

## Additional context
From: https://posthoghelp.zendesk.com/agent/tickets/28342

### Debug info

```shell
null
```

### PR DESCRIPTION
**Pull request by hoppybunny**
## Problem

When a cohort is calculating, its full data is refreshed from the backend once the calculation finishes. If a user makes changes to the cohort during this time (e.g., editing the name or description) but hasn’t clicked “Save,” those changes are silently overwritten.

This is because while a cohort is being calculated, the `checkIfFinishedCalculating` function refreshes the entire cohort object from the backend. This replaces all properties of the cohort, including any edits a user might make while it’s mid-calculation.

Closes #30813

## Changes

Disabled the whole form temporarily when the calculation is ongoing so that no edits can be made by the user. Form is enabled again once the calculation is complete. 

Video is taken at slow 3G speed so that the calculation takes a longer time.

https://github.com/user-attachments/assets/7027fc5c-e72b-4ed3-b03c-0d633deeb8ca

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

Yes - this is a purely frontend change that works the same way regardless of deployment type.

## How did you test this code?

Manually tested.

### CODE REVIEW

File: frontend/src/scenes/cohorts/CohortEdit.tsx [hunk 1]
```diff
@@ -49,7 +49,14 @@ export function CohortEdit({ id }: CohortLogicProps): JSX.Element {
...
     return (
         <div className="cohort">
-            <Form id="cohort" logic={cohortEditLogic} props={logicProps} formKey="cohort" enableFormOnSubmit>
+            <Form
+                id="cohort"
+                logic={cohortEditLogic}
+                props={logicProps}
+                formKey="cohort"
+                enableFormOnSubmit
+                className={cohort.is_calculating ? 'pointer-events-none opacity-50' : ''}
```
Comment (haacked) [inline frontend/src/scenes/cohorts/CohortEdit.tsx:58]: This is a clever way of disabling the form visually, but it doesn't actually disable form inputs. For example, screen readers will still see the inputs as enabled. It's possible that keyboard submissions will still work.

What you could do is wrap all the inputs in the form with a `<fieldset disabled={cohort.is_calculating} className="border-0 p-0 m-0 min-w-0 disabled:opacity-50">`. That would ensure all the fields are actually disabled.

**Review by haacked — CHANGES_REQUESTED** [review]

File: frontend/src/scenes/cohorts/CohortEdit.tsx (hunk 1 above)
Comment (hoppybunny) [reply frontend/src/scenes/cohorts/CohortEdit.tsx]: Oh good catch there. Fieldset is a better choice. Done, I've pushed the fixes. Added a tooltip when the form is disabled too. 
image

**Comment by hoppybunny** [comment]
bumping this up if you've missed reviewing this @haacked ! :)

**Comment by haacked** [comment]
Hi @hoppybunny, I talked to some folks and preventing editing would be a bad experience as some cohorts can take up to 10 minutes to calculate.

A colleague suggested that this line might be causing the problem and might be unnecessary: https://github.com/PostHog/posthog/blob/master/frontend/src/scenes/cohorts/cohortEditLogic.ts#L332

If you're still up for investigating, perhaps just try removing that line and see what happens. Is it necessary? Does it fix the problem. If not, I'll take a look later.

**Comment by hoppybunny** [comment]
@haacked Have a look, this should fix it. You can refer to [`CohortType` ](https://github.com/PostHog/posthog/blob/cccbede9ca92636f82dc9700801ea7e9cfb0708f/frontend/src/types.ts#L1371) to see all the possible fields that can be updated there.

**Review by haacked — APPROVED** [review]
Sorry for the delay, but this works perfectly! Thanks!
