### PR TITLE
Fix prop operator not changing

### LINKED ISSUE #2971: Broken property filter
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Property filter does not select correctly (sometimes??)

https://user-images.githubusercontent.com/38760734/104921976-d4702900-5978-11eb-849d-d7034e4a12a5.mov

**EDIT:** Apparently it does indeed set the filter, just doesn't update the UI

## Expected behavior

Clicking something else other than "equals" should work

## How to reproduce

1. Go to create a cohort
2. Try to add a property filter for anything other than "equals"
3. Sometimes (?) it doesn't work

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

### PR DESCRIPTION
**Pull request by EDsCODE**
## Changes

*Please describe.*  
- previous changes caused the prop operator remain stuck on 'exact'

*If this affects the frontend, include screenshots.*  

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

### CODE REVIEW

File: frontend/src/lib/components/PropertyFilters/OperatorValueSelect.tsx [hunk 1]
```diff
@@ -39,7 +39,7 @@ export function OperatorValueSelect({
                             onChange(newOperator, newOperator)
                         } else if (isOperatorFlag(currentOperator || 'exact')) {
                             onChange(newOperator, null)
-                        } else if (value) {
+                        } else {
```
Comment (macobo) [inline frontend/src/lib/components/PropertyFilters/OperatorValueSelect.tsx:42]: :thinking: I think the mistake is on line 34 instead: it should be `currentOperator` over `operator`.

Keeping this keeps PropertyFilter.js simpler - we don't call onChange until the inputs are 'valid'.

File: frontend/src/lib/components/PropertyFilters/PropertyFilter.js [hunk 2]
```diff
@@ -79,8 +79,10 @@ function PropertyPaneContents({
                         operator={operator}
                         value={value}
                         onChange={(newOperator, newValue) => {
-                            onComplete()
                             setThisFilter(propkey, newValue, newOperator, type)
+                            if (newOperator && newValue) {
```
Comment (macobo) [inline frontend/src/lib/components/PropertyFilters/PropertyFilter.js:83]: Q: does this work for flags?

File: frontend/src/lib/components/PropertyFilters/OperatorValueSelect.tsx (hunk 1 above)
Comment (EDsCODE) [reply frontend/src/lib/components/PropertyFilters/OperatorValueSelect.tsx]: yeah let's go with that

File: frontend/src/lib/components/PropertyFilters/PropertyFilter.js (hunk 2 above)
Comment (EDsCODE) [reply frontend/src/lib/components/PropertyFilters/PropertyFilter.js:83]: yup it actually is better now because when you switch from flags to nonflag operator it won't close the selector until you have a value selected

**Review by macobo — APPROVED** [review]
