### PR TITLE
fix(flags): pass paired group identifiers instead of cartesian product

### LINKED ISSUE #49009: feat(flags): Pass paired group identifiers instead of cartesian product in flag evaluation
## Problem

In `rust/feature-flags/src/flags/flag_matching_utils.rs`, the `fetch_and_locally_cache_all_relevant_properties` function receives `group_type_indexes` and `group_keys` as two separate `HashSet`s. Both the SQL and personhog paths then query using a cartesian product of these sets, even though the caller (`prepare_group_data`) has the 1:1 mapping available.

For example, if flags target organizations (type 0) and projects (type 1):
- **Input mapping** (in `prepare_group_data`): `{0 → "org-123", 1 → "proj-456"}`
- **Passed as**: `type_indexes = {0, 1}`, `keys = {"org-123", "proj-456"}`
- **Queried as**: 4 combinations instead of 2 — `(0, "org-123")`, `(0, "proj-456")`, `(1, "org-123")`, `(1, "proj-456")`

The database filters out non-existent pairs, so this is correct but wasteful. With N group types, it queries N² pairs instead of N.

## Suggested fix

1. Add the paired mapping (`HashMap<GroupTypeIndex, String>`) to `GroupData`
2. Thread it through to `fetch_and_locally_cache_all_relevant_properties`
3. SQL: Change `group_type_index = ANY($2) AND group_key = ANY($3)` to explicit `(group_type_index, group_key) IN (...)` pairs
4. Personhog: Send only the valid `GroupIdentifier` pairs instead of the cartesian product

## Context

Found during review of #48651 (personhog integration). The personhog path replicates the existing SQL behavior, so this affects both paths equally. Low priority since the database handles it correctly, but worth cleaning up for efficiency and clarity.

### PR DESCRIPTION
**Pull request by haacked**
## Problem

When evaluating feature flags that involve multiple group types, the Rust flag evaluation service fetched group properties using two independent `ANY` filters:

```sql
WHERE group_type_index = ANY($2) AND group_key = ANY($3)
```

The parameters came from separate `HashSet<GroupTypeIndex>` and `HashSet<String>` collections, so the pairing between each group type index and its key was lost before the query was built. The query expressed a cartesian product: match any row whose index is in the first set **and** whose key is in the second set.

### Example

A team has two group types and three group rows:
- `organization` (index 0), key `"acme"`
- `company` (index 1), key `"acme"` ← same key, different group type
- `company` (index 1), key `"globex"`

A request comes in for `groups: {"organization": "acme", "company": "globex"}`. We want rows for exactly `(0, "acme")` and `(1, "globex")`.

**Old query** (`ANY/ANY`): `group_type_index IN (0, 1) AND group_key IN ('acme', 'globex')` — returns **3 rows**, including the false match `(1, "acme")` because index 1 is in the first array and `"acme"` is in the second. The flag evaluator loads the wrong company's properties.

**New query** (`UNNEST` paired join): matches only the exact `(index, key)` pairs requested — returns the correct **2 rows**.

This isn't theoretical — many teams in production have group keys shared across multiple group type indexes.

### Additional issues with the old approach

- **Silent deduplication**: `HashSet<String>` for keys collapsed duplicate key strings shared across group types, silently dropping a lookup.
- **Extra data transferred**: the old query had to select `group_key` so it could re-associate results with the right group type after the unpaired fetch.

Fixes #49009

## Changes

- Replace separate `HashSet<GroupTypeIndex>` + `HashSet<String>` parameters with a `HashMap<GroupTypeIndex, String>` that preserves the 1:1 pairing
- SQL query now uses `INNER JOIN UNNEST($2, $3)` to match exact `(type_index, key)` pairs, matching the pattern already used in personhog-replica
- No longer selects `group_key` (unnecessary when the join guarantees pairing)

## How did you test this code?

- Unit tests covering the paired group identifier SQL path with multiple group types
- All existing feature flag evaluation tests continue to pass
- Manually tested a flag with group filter

## Publish to changelog?

No

### CODE REVIEW

**Review by sortafreel — COMMENTED** [review]
# ReviewHog Report

## Bugfix

**Files:** `rust/feature-flags/src/flags/flag_matching.rs`, `rust/feature-flags/src/flags/flag_matching_utils.rs`

**Issues:** 1 issue

<details>
<summary>What were the main changes</summary>
<br>

- Replaced separate group type/key sets with a paired HashMap<GroupTypeIndex, String> so group identifiers keep their exact 1:1 mapping.
- Updated group-data preparation to filter by required group type indexes and return early with an empty map when no group-based flags are involved, preventing unnecessary mapping-cache failures for person-only evaluations.
- Changed group property fetching SQL from independent ANY filters to INNER JOIN UNNEST(indexes, keys), which matches only exact (group_type_index, group_key) pairs and removes cartesian-product false matches.
- Adjusted query inputs, selected columns, and logging to reflect paired lookups (group_pair_count) rather than independent type/key counts.

</details>

<details>
<summary>Full analysis</summary>
<br>

This chunk is the core bugfix for incorrect group-property loading during feature flag evaluation when multiple group types are present. The old path split requested group identifiers into two independent sets (`HashSet<GroupTypeIndex>` and `HashSet<String>`) and queried with `group_type_index = ANY(...) AND group_key = ANY(...)`, which turned intended pair lookups into a cartesian-style match and could return unrelated rows (for example, same key reused across group types). The change replaces that data model with a paired `HashMap<GroupTypeIndex, String>` so each lookup keeps a strict 1:1 `(type_index, key)` identity end-to-end.

Architecturally, this sits in the `FeatureFlagMatcher` preparation pipeline (`prepare_evaluation_state_if_needed` -> `prepare_flag_evaluation_state` -> `prepare_group_data` -> `fetch_and_locally_cache_all_relevant_properties`) that preloads DB-backed state into `FlagEvaluationState` before condition evaluation. `prepare_group_data` now computes required group type indexes from flags, short-circuits with an empty map when none are required, and only then reads `GroupTypeMappingCache`. That early return is important because `initialize_group_type_mappings_if_needed` intentionally skips initialization when no group flags exist; without this guard, person-only evaluations could incorrectly fail with `NoGroupTypeMappings` (the issue raised in review comments).

Integration changes are localized but high-impact: `fetch_and_locally_cache_all_relevant_properties` now accepts the paired map, tracing fields/logging moved from separate counts to `group_pair_count`, and SQL switched to `INNER JOIN UNNEST($2::integer[], $3::text[])` to enforce exact pair matching. The group query no longer needs to select `group_key`, since pairing is guaranteed at join time, and the loaded rows are cached by `group_type_index` in evaluation state. This aligns the feature-flags service with existing pairwise UNNEST usage patterns elsewhere in the codebase (including personhog-replica), reducing false matches, removing silent key dedup side effects, and tightening correctness for multi-group-type evaluations.

</details>

File: rust/feature-flags/src/flags/flag_matching.rs [hunk 1]
```diff
@@ -1885,52 +1875,41 @@ impl FeatureFlagMatcher {
...
             .filter_map(|flag| flag.get_group_type_index())
             .collect();
 
-        // Map group names to group_type_index and group_keys
-        let group_type_to_key_map: HashMap<GroupTypeIndex, String> = self
+        if required_type_indexes.is_empty() {
+            return Ok(HashMap::new());
+        }
+
+        let types_to_indexes = self.group_type_mapping_cache.get_group_types_to_indexes()?;
```
Comment (sortafreel) [inline rust/feature-flags/src/flags/flag_matching.rs]: ### `prepare_group_data` now turns missing group mappings into a global DB-prep failure

**Priority:** must_fix | **Category:** bug | **Lines:** 1893, 766-775

---

`prepare_group_data` now uses `get_group_types_to_indexes()?`, so `NoGroupTypeMappings` aborts `prepare_flag_evaluation_state`. That error is then applied to all `flags_requiring_db_preparation`, including unrelated person flags. Previously this path tolerated missing mappings during group-data prep (via `.ok()?`) and still allowed person flags in the same request to evaluate.

<details>
<summary><strong>Suggested fix</strong></summary>
<br>

Keep group mapping lookup failures non-fatal in `prepare_group_data` (at least for `FlagError::NoGroupTypeMappings`) and return an empty group map instead, optionally with an early return when `self.groups.is_empty()`. Example: match `get_group_types_to_indexes()` and `return Ok(HashMap::new())` on `NoGroupTypeMappings`, while preserving hard-fail behavior for other unexpected errors.

</details>

<details>
<summary><strong>Why we think it's a valid issue</strong></summary>
<br>

The issue is valid. In the current code, `prepare_group_data` calls `get_group_types_to_indexes()?` whenever any flag in the batch is group-based; if mappings are missing, `prepare_flag_evaluation_state` fails, and `handle_db_preparation_error` marks all `flags_requiring_db_preparation` as errors (not just group flags). The person-only early return added in this PR avoids this for purely person batches, but mixed person+group batches can still over-fail. This is a behavioral regression from the previous `.ok()?` path, which tolerated missing mappings during group prep and allowed unrelated person flags to continue evaluating.

</details>

<details>
<summary><strong>Prompt to fix with AI (copy-paste)</strong></summary>
<br>

```
## Context
@rust/feature-flags/src/flags/flag_matching.rs#L1893
@rust/feature-flags/src/flags/flag_matching.rs#L766-775

<issue_description>
`prepare_group_data` now uses `get_group_types_to_indexes()?`, so `NoGroupTypeMappings` aborts `prepare_flag_evaluation_state`. That error is then applied to all `flags_requiring_db_preparation`, including unrelated person flags. Previously this path tolerated missing mappings during group-data prep (via `.ok()?`) and still allowed person flags in the same request to evaluate.
</issue_description>

<issue_validation>
The issue is valid. In the current code, `prepare_group_data` calls `get_group_types_to_indexes()?` whenever any flag in the batch is group-based; if mappings are missing, `prepare_flag_evaluation_state` fails, and `handle_db_preparation_error` marks all `flags_requiring_db_preparation` as errors (not just group flags). The person-only early return added in this PR avoids this for purely person batches, but mixed person+group batches can still over-fail. This is a behavioral regression from the previous `.ok()?` path, which tolerated missing mappings during group prep and allowed unrelated person flags to continue evaluating.
</issue_validation>

## Task
Investigate the issue and solve it

<potential_solution>
Keep group mapping lookup failures non-fatal in `prepare_group_data` (at least for `FlagError::NoGroupTypeMappings`) and return an empty group map instead, optionally with an early return when `self.groups.is_empty()`. Example: match `get_group_types_to_indexes()` and `return Ok(HashMap::new())` on `NoGroupTypeMappings`, while preserving hard-fail behavior for other unexpected errors.
</potential_solution>
```

</details>

**Review by patricio-posthog — APPROVED** [review]
Nice! I may be wrong but I think the query should be faster now too because of how the filter works.
