### PR TITLE
`PersonModal` refactor

### LINKED ISSUE #5600: Empty person modal looks sad
## Bug description

image

This happens when opening person modal on funnel historic trends.

## Expected behavior

Either:
1. Don't open a modal
2. Empty state

Also no scrollbars!

## How to reproduce

1. Construct a funnel
2. View it in historic trends
3. Click in a 0-item data point.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

cc @paolodamico which option would you recommend?

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

`PersonModal` was quite messy, so I refactored it in preparation for new session recordings linking. It's still far from ideal (most importantly the logic for handling various people endpoints is kind of hard to reason about), but at least the UX is significantly more polished.
Closes #5600.

| | Before | After |
| --- | --- | --- |
| Trends empty state | Zrzut ekranu 2021-08-24 o 22 08 41 | Zrzut ekranu 2021-08-24 o 22 09 07 |
| Trends | Screen Shot 2021-08-24 at 20 50 56 | Screen Shot 2021-08-24 at 20 44 00 |
| Stickiness | Screen Shot 2021-08-24 at 20 52 59 |  Screen Shot 2021-08-24 at 20 54 30  |
| Funnel | Screen Shot 2021-08-24 at 20 50 27 | Screen Shot 2021-08-24 at 20 49 29 |

### CODE REVIEW

**Comment by macobo** [comment]
Note re empty state and what to show: #5600 

cc @clarkus who might have other designs handy

File: frontend/src/scenes/trends/PersonModal.tsx [hunk 1]
```diff
@@ -55,21 +39,20 @@ export function PersonModal({ visible, view, filters, onSaveCohort }: Props): JS
     const title = useMemo(
         () =>
             isInitialLoad ? (
-                'Loading persons list...'
+                'Loading users…'
```
Comment (mariusandra) [inline frontend/src/scenes/trends/PersonModal.tsx:42]: Aren't we calling this "persons" for consistency everywhere?

File: frontend/src/scenes/trends/PersonModal.tsx [hunk 2]
```diff
@@ -88,119 +72,107 @@ export function PersonModal({ visible, view, filters, onSaveCohort }: Props): JS
...
+                        <div style={{ background: '#FAFAFA' }}>
+                            {people.count > 0 ? (
+                                people?.people.map((person) => (
+                                    <div key={person.id}>
+                                        <PersonRow person={person} />
+                                    </div>
+                                ))
+                            ) : (
+                                <div className="person-row-container person-row">
+                                    We couldn't find any matching users for this datapoint.
```
Comment (mariusandra) [inline frontend/src/scenes/trends/PersonModal.tsx:148]: `persons`?

**Review by mariusandra — COMMENTED** [review]
I think it's definitely an improvement. Though we should probably keep the terminology consistent and user "persons" instead of "users" in the messages?

Will defer to @clarkus for final approval

File: frontend/src/scenes/trends/PersonModal.tsx (hunk 1 above)
Comment (Twixes) [reply frontend/src/scenes/trends/PersonModal.tsx:42]: Wellll, I specifically renamed this because in the graph hover tooltip it's "inspect users". So I do agree the terminology between "users", "persons", and "people" is kind of wavering.

**Comment by Twixes** [comment]
@macobo Thanks, that's a good point. I think it's better to be prepared for no persons in the modal first, but making the tooltip dynamic can come after this too.

File: frontend/src/scenes/trends/PersonModal.tsx (hunk 1 above)
Comment (Twixes) [reply frontend/src/scenes/trends/PersonModal.tsx:42]: Okay, updated, but in a PR on top of this one: https://github.com/PostHog/posthog/pull/5739

Comment (clarkus) [reply frontend/src/scenes/trends/PersonModal.tsx:42]: Agree that it should be persons. We've been inconsistent with this in the past, but looking forward we're going with "persons".

**Review by clarkus — APPROVED** [review]
I think these changes look good. There are some outstanding clean up issues in our modals, but they're probably outside the scope of this change. The only thing I see that needs to change here is the button text label color. Those should be our primary blue instead of black. I'm also curious about the conditionality of the "close" button. That's a nice thing to have in place in all cases even though it's redundant with the `X` action in the upper right of the modal. Otherwise I'm a 👍 . Thanks for working on this, @Twixes

**Comment by Twixes** [comment]
Buttons now, is that correct?

Zrzut ekranu 2021-08-25 o 21 01 16

The Close button in the footer was much too redundant IMO, as not only the X in top right closes the modal (a classic pattern), but also clicking anywhere outside of the modal does that too.

**Comment by mariusandra** [comment]
@Twixes what about taking a few snapshots of these modals and adding to a storybook story, for fun and profit? ([Docs here](https://github.com/PostHog/posthog/pull/5714#issue-718639120), will add make a handbook entry later)

Also, 

image

so I guess it's LGTM'd.

**Comment by Twixes** [comment]
Very intriguing idea. @mariusandra But no time for this as I'm leaving for the offsite. :( May do it after.
