### PR TITLE
fix: persist early access features form changes

### LINKED ISSUE #39814: Early access features UX bugs
1. Adding an early access feature of type `alpha` instead of `concept` means it doesn't show up in the feature previews page... That shouldn't happen
2. changing an early access feature from Alpha to Beta using the action sidepanel doesn't actually stick; on refresh the feature will still be in whatever state it was originally.

### PR DESCRIPTION
**Pull request by ndaba1**
## Problem

Changing an early access feature's name/description via the scene title section and changing the stage via the action sidepanel does not persist and any changes made are lost on refresh 

Closes #39814

## Changes

Makes the form changes persist

### CODE REVIEW

File: products/early_access_features/frontend/EarlyAccessFeature.tsx [hunk 1]
```diff
@@ -255,7 +256,22 @@ export function EarlyAccessFeature({ id }: EarlyAccessFeatureLogicProps): JSX.El
...
+                                            ...earlyAccessFeature,
+                                            stage: value as EarlyAccessFeatureStage,
+                                        })
+                                    )
+                                } else {
+                                    saveEarlyAccessFeature({
+                                        ...earlyAccessFeature,
+                                        stage: value as EarlyAccessFeatureStage,
+                                    })
+                                }
```
Comment (dmarticus) [inline products/early_access_features/frontend/EarlyAccessFeature.tsx:274]: this seems to be the meat of the changes; I _think_ this is all we need to do.

File: products/early_access_features/frontend/EarlyAccessFeature.tsx [hunk 2]
```diff
@@ -135,11 +135,12 @@ export function EarlyAccessFeature({ id }: EarlyAccessFeatureLogicProps): JSX.El
...
-                    onNameChange={(value) => {
-                        setEarlyAccessFeatureValue('name', value)
+                    renameDebounceMs={1000}
+                    onNameChange={(name) => {
+                        saveEarlyAccessFeature({ ...earlyAccessFeature, name })
                     }}
-                    onDescriptionChange={(value) => {
-                        setEarlyAccessFeatureValue('description', value)
+                    onDescriptionChange={(description) => {
+                        saveEarlyAccessFeature({ ...earlyAccessFeature, description })
```
Comment (dmarticus) [inline products/early_access_features/frontend/EarlyAccessFeature.tsx:143]: why do we need to add this debouncing?

**Review by dmarticus — APPROVED** [review]
looks generally good; I have a question about the debouncing but the `onSave` changes look correct

File: products/early_access_features/frontend/EarlyAccessFeature.tsx (hunk 2 above)
Comment (ndaba1) [reply products/early_access_features/frontend/EarlyAccessFeature.tsx:143]: https://github.com/user-attachments/assets/8540f826-4b95-4952-aeea-ebb560843692

hey @dmarticus 
I noticed that edits on the title and description currently aren't also persisted and get lost on refresh. Since there's no "save changes" button or anything similar, I switched the `onChange` listeners to make network requests, rather than updating the form state, and added the debounce to avoid making the requests on every keystroke.

**Comment by dmarticus** [comment]
shipped, thank you!
