### PR TITLE
Don't show actor modal inspect text on dashboards

### LINKED ISSUE #7913: Outstanding Tasks for Insight Tooltips
Leftover items related to https://github.com/PostHog/posthog/pull/7872. Assigning myself for now so that I can finish up if I have free time.

This issue comes out of an action item from standup to capture leftover tasks for the new insight tooltips before we release. @paolodamico 

- [x] https://github.com/PostHog/posthog/issues/7994
- [x] Standardize `dates` parameters in Stickiness and Retention line graphs so that relative date titles can be properly handled by Insight Tooltips.
- [ ] 🎨 Use new tooltips in Funnel Steps (waiting on design input here)
- [x] https://github.com/PostHog/posthog/issues/2620
- [ ] https://github.com/PostHog/posthog/issues/8163

### LINKED ISSUE #8163: Person modal on dashboard doesn't appear on click
## Bug description

[Video](https://www.loom.com/share/4094b29352b5465d8132c06a856a2afb) 

Voice acting by me.

## Expected behavior

I get the list of persons up that produce a data point.

## How to reproduce

1. Go to [this dashboard](https://app.posthog.com/dashboard/20464) showing our largest org signups

## Environment

- [x] PostHog Cloud

### PR DESCRIPTION
**Pull request by alexkim205**
## Changes

Fixes https://github.com/PostHog/posthog/issues/8163.

Closes https://github.com/PostHog/posthog/issues/7913.

Last outstanding task before `line-graph-v2` can be released.

## How did you test this code?

Manually

### CODE REVIEW

File: frontend/src/scenes/funnels/FunnelLineGraph.tsx [hunk 1]
```diff
@@ -10,11 +10,11 @@ import { dayjs } from 'lib/dayjs'
 import { getFormattedDate } from 'scenes/insights/InsightTooltip/insightTooltipUtils'
 
 export function FunnelLineGraph({
-    dashboardItemId,
     inSharedMode,
     color = 'white',
+    showPersonsModal = true,
 }: Omit<ChartParams, 'filters'>): JSX.Element | null {
-    const { insightProps, insight } = useValues(insightLogic)
+    const { insightProps, insight, isViewedOnDashboard } = useValues(insightLogic)
```
Comment (Twixes) [inline frontend/src/scenes/funnels/FunnelLineGraph.tsx:17]: I think it may be better not to rely on this feature of the logic, and instead fully rely on `showPersonsModal`. That's because being viewed on a dashboard is just one of the cases where this should be hidden. The behavior we strictly need is for the persons modal to be disabled _when viewed in `InsightCard`_(and that may be on a dashboard or in saved insights), so a possibly clearer solution is to exclusively pass `showPersonsModal={false}` down when using the viz component in `InsightCard`.

File: frontend/src/scenes/insights/LineGraph/LineGraph.tsx [hunk 2]
```diff
@@ -361,7 +361,7 @@ function LineGraphV2(props: LineGraphProps): JSX.Element {
                                         hideColorCol={isHorizontal || !!tooltipConfig?.hideColorCol}
                                         renderCount={tooltipConfig?.renderCount}
                                         forceEntitiesAsColumns={isHorizontal}
-                                        hideInspectActorsSection={!(onClick && showPersonsModal)}
+                                        hideInspectActorsSection={!onClick || !showPersonsModal}
```
Comment (Twixes) [inline frontend/src/scenes/insights/LineGraph/LineGraph.tsx:364]: Hmm, sorry for not noticing before, but seeing this perhaps we could unify `showPersonsModal` with `onClick`? As in, it doesn't seem like `showPersonsModal={true}` can work with `onClick={undefined}`, while `onClick={() => ...)` should not be set with `showPersonsModal={false}` as that'd be needlessly hiding the feature from the user.

**Comment by alexkim205** [comment]
Merging this in since it fixes the existing bug and variable cleanup is just existing tech debt. Let me know if you'd like me to change things up later.

File: frontend/src/scenes/insights/LineGraph/LineGraph.tsx (hunk 2 above)
Comment (Twixes) [reply frontend/src/scenes/insights/LineGraph/LineGraph.tsx:364]: Well, I suppose in that case we'd just pass `onClick` as `undefined` (in `InsightCard` for instance), but it's not a big deal anyway
