### PR TITLE
fix: unread check is too careful

### LINKED ISSUE #31471: Bug: Unable to clear Team Activity notification badge, possibly because the associated user no longer exists
## Bug description

The Team Activity tab can get into a state where it isn't possible to clear out the notification badge. In this particular case, it seems to have been caused by the associated user no longer existing within the project. 

Clicking `Mark as read` does not resolve the issue.

Image

## How to reproduce
For this particular instance, view as the user in the ticket, however presumably the following steps below could be made to replicate. 

1. Have a project with teams addon, and two test users
2. Test user makes a change that populates the `Team activity` tab
3. Remove the test user from the project
4. View the `Team Activity` tab from the second user

## Additional context
From: https://posthoghelp.zendesk.com/agent/tickets/29291

### Debug info

```shell
Kind: bug

Target area: data_management

Report event: http://go/ticketByUUID/591341cb-6cfc-4978-b8f2-431bc6807888

Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/01964f7b-a61f-76f7-acd6-f329dd062126?t=1430

Exceptions: https://us.posthog.com/project/2/error_tracking?filterGroup=%7B%22type%22%3A%22AND%22%2C%22values%22%3A%5B%7B%22type%22%3A%22AND%22%2C%22values%22%3A%5B%7B%22key%22%3A%22%24session_id%22%2C%22value%22%3A%5B%2201964f7b-a61f-76f7-acd6-f329dd062126%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%7D%5D%7D

Location: https://eu.posthog.com/project/15389

Sentry: http://go/sentryEU/15389

Persons-on-events mode for project: person_id_override_properties_on_events
```

### PR DESCRIPTION
**Pull request by pauldambra**
a user had ended up with the latest notification in the activity log being read, but an earlier notification being unread

when you click "mark all as read" we only react if the latest message is unread

instead we can react if _any_ message is unread

fixes https://github.com/PostHog/posthog/issues/31471

### CODE REVIEW

File: frontend/src/layout/navigation-3000/sidepanel/panels/activity/sidePanelActivityLogic.tsx [hunk 1]
```diff
@@ -105,7 +105,9 @@ export const sidePanelActivityLogic = kea<sidePanelActivityLogicType>([
                         a.created_at.isAfter(b.created_at) ? a : b
                     )
 
-                    if (!latestNotification.unread) {
+                    const hasUnread = values.notifications.some((ic) => ic.unread)
```
Comment (rafaeelaudibert) [inline frontend/src/layout/navigation-3000/sidepanel/panels/activity/sidePanelActivityLogic.tsx:108]: But then look at the code below, we're always passing the latest `created_at`. How does this work then? How is it possible that a newer notification can be read, whilst an older one isn't?

Comment (pauldambra) [reply frontend/src/layout/navigation-3000/sidepanel/panels/activity/sidePanelActivityLogic.tsx:108]: > we're always passing the latest created_at

yep... we store a bookmark per user of the timestamp they've read up to determine if they have something to return from the API

> How is it possible that a newer notification can be read, whilst an older one isn't?

in this case I think Joe's changelog notifications have some special handling, but regardless the check behavior is wrong right now. if there are any unread messages then when you click mark all as read we should set a new bookmark for you

tbh we could always set a bookmark but seems silly to send one if completely unnecessary

**Review by rafaeelaudibert — APPROVED** [review]
