### PR TITLE
fix(survey): Handle label that is empty after trimming in survey results query

### LINKED ISSUE #41783: bug(surveys): empty label breaks hogql column name
### Bug Description

if you create a survey with an "empty" label (just whitespace), then the hogql column name is broken. see:

Image

use-case: customer wants no label, just uses HTML description field for everything

## How to reproduce

1. create survey question with label as a space, and add html description content
2. submit a response
3. view results table

## Additional context
see https://us.posthog.com/project/2/surveys/019a9a0c-a3bf-0000-cd69-e544d90bf95b

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables or https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

### PR DESCRIPTION
**Pull request by lshaowei18**
## Problem

Closes https://github.com/PostHog/posthog/issues/41783

The `title` for the column is calculated in this function:

https://github.com/PostHog/posthog/blob/2f651d23aee7ca8ba0c66db094e13d1fce95cc0c/frontend/src/queries/nodes/DataTable/renderColumnMeta.tsx#L90

And `extractExpressionComment` will trim the title, and if the trimmed title is empty it will return the query:

https://github.com/PostHog/posthog/blob/2f651d23aee7ca8ba0c66db094e13d1fce95cc0c/frontend/src/queries/nodes/DataTable/utils.ts#L58-L63

## Changes

Instead of just passing in `q.question`, we handle the case and also considers `q.description` before defaulting to `Untitled Question`.

https://github.com/user-attachments/assets/fbdf0ad8-14de-48c9-812c-d4f63fda2252

## How did you test this code?

1) Create a hosted survey where a question's label is a single space and add a description
2) Submit the survey.
3) Go to the results tab and scroll down, the table should now show the `description` instead of the long query.

### CODE REVIEW

File: frontend/src/scenes/surveys/utils.ts [hunk 1]
```diff
@@ -619,3 +623,15 @@ export function buildSurveyTimestampFilter(
...
 }
+
+export function getExpressionCommentForQuestion(
+    q: BasicSurveyQuestion | LinkSurveyQuestion | RatingSurveyQuestion | MultipleSurveyQuestion
+): string {
+    if (q.question.trim().length > 0) {
+        return q.question
+    }
+    if (q.description != null && q.description.trim().length > 0) {
+        return q.description
```
Comment (adboio) [inline frontend/src/scenes/surveys/utils.ts]: description may be HTML content, how does the data table renderer handle that? should we consider parsing the html or simply returning “Question {idx}” ? perhaps also relevant if HTML content is very long

**Comment by adboio** [comment]
you’re quick, thank you!!

File: frontend/src/scenes/surveys/utils.ts (hunk 1 above)
Comment (lshaowei18) [reply frontend/src/scenes/surveys/utils.ts]: Good point! 

It now seems to me that return `q.description` might not be a good idea, and I like "Question {idx}" alot better :)

Comment (lshaowei18) [reply frontend/src/scenes/surveys/utils.ts]: Ok I have removed the description and fall back to "Question {idx}" in https://github.com/PostHog/posthog/pull/41798/commits/3d8bcc83f74d58abeba179277015f07dac84e8bd

Thanks for bringing "Question {idx}" up, love it way more than "Untitled Question" 😄

**Review by adboio — APPROVED** [review]
love it!! 🚢
