### PR TITLE
Find aggregation group index properly

### LINKED ISSUE #8026: New tooltips do not respect group types
## Bug description

When analyzing something by groups, the new tooltips look like following:

image

## Expected behavior

Tooltip should say `Click to view organization(s)`

## How to reproduce

1. Go to insights
2. Aggregate by a group type
3. Hover

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

cc @alexkim205, @mariusandra @paolodamico Please keep groups in mind when designing for or implementing new features.

### PR DESCRIPTION
**Pull request by alexkim205**
## Changes

Addresses https://github.com/PostHog/posthog/pull/8045/files#r784656878

Actually closes #8026

## How did you test this code?

Manual QA for all insight types.

### CODE REVIEW

File: frontend/src/scenes/funnels/FunnelLineGraph.tsx [hunk 1]
```diff
@@ -29,6 +29,7 @@ export function FunnelLineGraph({
             insightId={insight.id}
             inSharedMode={!!inSharedMode}
             percentage={true}
+            aggregationGroupTypeIndex={filters.aggregation_group_type_index}
```
Comment (macobo) [inline frontend/src/scenes/funnels/FunnelLineGraph.tsx:32]: Types don't line up here - this can be number | null, `number` on the other end?

File: frontend/src/scenes/insights/LineGraph/LineGraph.tsx [hunk 2]
```diff
@@ -355,7 +357,9 @@ export function LineGraph(props: LineGraphProps): JSX.Element {
                                         forceEntitiesAsColumns={isHorizontal}
                                         hideInspectActorsSection={!(onClick && showPersonsModal)}
                                         groupTypeLabel={
-                                            aggregationLabel(seriesData?.[0]?.action?.math_group_type_index).plural
+                                            aggregationGroupTypeIndex === -1
```
Comment (macobo) [inline frontend/src/scenes/insights/LineGraph/LineGraph.tsx:360]: We don't use -1 anywhere else. `number | null` would be a better type, along with checking it as `== undefined` (see frontend/src/scenes/trends/trendsLogic.ts)

File: frontend/src/scenes/trends/trendsLogic.ts [hunk 3]
```diff
@@ -135,6 +135,17 @@ export const trendsLogic = kea<trendsLogicType>({
                 }
             },
         ],
+        aggregationGroupTypeIndex: [
```
Comment (macobo) [inline frontend/src/scenes/trends/trendsLogic.ts:138]: Note that this selector leads to different behavior to what we discussed.

I suggest:
- If N group lines: `Click to view GroupType`
- If N person lines: `Click to view people`
- If mixed: `Click to view`

File: frontend/src/scenes/funnels/FunnelLineGraph.tsx (hunk 1 above)
Comment (alexkim205) [reply frontend/src/scenes/funnels/FunnelLineGraph.tsx:32]: Hm it looks like both are typed to `number | undefined` so shouldn't the types here be the same?

File: frontend/src/scenes/trends/trendsLogic.ts (hunk 3 above)
Comment (alexkim205) [reply frontend/src/scenes/trends/trendsLogic.ts:138]: I'm probably missing something here, but it looks like this check accounts for this case. 

If every event or action is the same as the first one's `math_group_type_index`, we show an aggregation label. If the first `math_group_type_index` is undefined, all lines are person lines. If the first `math_group_type_index` is a number, all lines are group lines.

If any event or action doesn't satisfy the above condition, it is mixed and we return -1. 

Is there an edge case I'm missing?

File: frontend/src/scenes/insights/LineGraph/LineGraph.tsx [hunk 4]
```diff
@@ -60,6 +60,7 @@ interface LineGraphProps {
     tooltip?: TooltipConfig
     isCompare?: boolean
     incompletenessOffsetFromEnd?: number // Number of data points at end of dataset to replace with a dotted line. Only used in line graphs.
+    aggregationGroupTypeIndex?: number | null
```
Comment (macobo) [inline frontend/src/scenes/insights/LineGraph/LineGraph.tsx:63]: Using two bottom values is kind of sus and should likely get refactored to a better union, e.g. 

```
labelGroupType: number | 'people' | 'none'
```

Seems like a more consistent solution. That said, ymmv

**Review by macobo — APPROVED** [review]
