### PR TITLE
fix: Shows proper message when filter results are empty

### LINKED ISSUE #11400: Insight keyword filter - empty state doesn't match context
## Bug description

When you filter the list of insishts such that there aren't any matching results, the empty state shown doesn't really align to the context. The header is accurate to this context, but the rest of the empty state content is more targeted towards creation. 

Screen Shot 2022-08-19 at 11 22 52 AM

Ideally this empty state would guide the user on how to find what they're looking for, not push them to create something new. The insight count should also reflect that there are no matching insights, not that there are "no insights yet". 

An example of content that would be more targeted in this scenario:

```
Header: No insights matched your search for "[keyword]"
Description: Refine your keyword search, or try using other filters such as type, last modified, created or by. 
```

## How to reproduce

1. Go to insights
2. Filter the list on a non-matching keyword
3. Observe the empty state content 

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

### PR DESCRIPTION
**Pull request by naquiuddin**
## Problem
This PR fixes #11400 
Currently when filters are applied on **Insights**, the empty state shows a message asking user to create insights. 

## Changes
This pull request doesn't change the heading, However the description shows as `Refine your keyword search, or try using other filters such as type, last modified or created by.` when applied filters show empty results. This behavior is added on all **Tabs**. 

Screenshot 2023-01-11 at 7 26 28 PM

## How did you test this code?
I tried running test cases and they ran very inconsistently for me. Sometimes 5 test cases fail and sometimes 7 or more. May be I am missing something when running it. Please shed some light.

I just ran `pnpm test` to run all test cases in frontend. I also ran test cases mentioning only `Insights` folder.

However I haven't written any test cases for this PR.

### CODE REVIEW

File: frontend/src/scenes/insights/EmptyStates/EmptyStates.tsx [hunk 1]
```diff
@@ -266,7 +272,11 @@ export function SavedInsightsEmptyState(): JSX.Element {
                             : title.replace('$CONDITION', `matching these filters`)
                         : title.replace('$CONDITION', 'for this project')}
                 </h2>
-                <p className="empty-state__description">{description}</p>
+                {usingFilters ? (
+                    <p className="empty-state__description">{descriptionOnEmptyFilter}</p>
```
Comment (Twixes) [inline frontend/src/scenes/insights/EmptyStates/EmptyStates.tsx:276]: Hey @naquiuddin! Thanks for this contribution. Only one note: Given `descriptionOnEmptyFilter` is the same for all tabs, could we just inline it?

Comment (naquiuddin) [reply frontend/src/scenes/insights/EmptyStates/EmptyStates.tsx]: My Pleasure!

Makes sense. I would suggest we do same for the `description` field as well, which also has same text for all tabs. Please see my latest commit and let me know whether that makes sense.

Comment (Twixes) [reply frontend/src/scenes/insights/EmptyStates/EmptyStates.tsx]: Ah, so the descriptions are indeed all _almost_ the same, but "almost" is the key word – the one for the "Favorited" tabs has "Once you _favorite_ an insight" instead of "_create_", so we still need that differentiated

Comment (naquiuddin) [reply frontend/src/scenes/insights/EmptyStates/EmptyStates.tsx]: Oh Yeah 😄, I didn't notice that. Thanks,
Reverted that and pushed it again.

**Review by Twixes — APPROVED** [review]
Made tiny formatting fixes, looking good!
