### PR TITLE
Expand taxonomic filter infinite lists, hide properties not seen on event

### LINKED ISSUE #8092: Property that's 'not seen' should be greyed out
## Bug description

When I searched for 'hubspot_score' which is a person property but not an event property (even though it does exist), despite the "not seen" label I still clicked it, and then was confused by the breakdown being empty.

image

## Expected behavior

1. If there are only "not seen" properties on events but there is a "seen" property on persons we should auto select that one
2. Grey out the text of any "not seen" properties to make it more obvious

cc @mariusandra 

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- WIP, putting out there mainly for UX feedback
- Resolves https://github.com/PostHog/posthog/issues/8092
- Adds an option to expand the list of taxonomic filter event properties

## How did you test this code?

Manually in the browser for now. Tests coming.

### CODE REVIEW

**Review by clarkus — CHANGES_REQUESTED** [review]
I think the workflow is solid, but I question the gray italicized treatment for the reveal link. I've been using that as an empty state placeholder elsewhere. I know that we don't really want users to spend their time in this unseen area of the list, but I do think the action for revealing the items could look more actionable. A borderless blue link would be enough. Thoughts?

**Comment by mariusandra** [comment]
I think that can actually work very well:

**Review by clarkus — APPROVED** [review]
UX looks good to me.

**Comment by mariusandra** [comment]
Finally everything's green and this is ready for a code review.

File: frontend/src/lib/components/TaxonomicFilter/taxonomicFilterLogic.tsx [hunk 1]
```diff
@@ -176,8 +176,21 @@ export const taxonomicFilterLogic = kea<taxonomicFilterLogicType>({
                     type: TaxonomicFilterGroupType.EventProperties,
                     endpoint: combineUrl(
                         `api/projects/${teamId}/property_definitions`,
-                        featureFlags[FEATURE_FLAGS.UNSEEN_EVENT_PROPERTIES] ? { event_names: eventNames } : {}
+                        featureFlags[FEATURE_FLAGS.UNSEEN_EVENT_PROPERTIES] && eventNames.length > 0
```
Comment (Twixes) [inline frontend/src/lib/components/TaxonomicFilter/taxonomicFilterLogic.tsx:179]: When I try open the event selector in insight edit mode, the page crashes because of this line: `Uncaught TypeError: Cannot read properties of undefined (reading 'length')`. I guess `eventNames` is an optional prop so in some places it's `undefined`.

File: frontend/src/lib/components/TaxonomicFilter/taxonomicFilterLogic.tsx [hunk 2]
```diff
@@ -176,8 +176,21 @@ export const taxonomicFilterLogic = kea<taxonomicFilterLogicType>({
...
+                            ? combineUrl(`api/projects/${teamId}/property_definitions`, {
+                                  event_names: eventNames,
+                                  is_event_property: true,
+                              }).url
+                            : undefined,
+                    expandLabel: ({ count, expandedCount }) =>
+                        `Show ${expandedCount - count} ${
+                            expandedCount - count === 1 ? 'property' : 'properties'
+                        } that haven't been seen with this event`,
```
Comment (Twixes) [inline frontend/src/lib/components/TaxonomicFilter/taxonomicFilterLogic.tsx:193]: If I have more than one series, I'm not sure if "this event" refers to one of the series, or both combined.
Also, what happens if just one of the series is an action?

**Review by Twixes — CHANGES_REQUESTED** [review]
This is really nice when it works, not so nice when it crashes. 😅

Meta-feedback: please mention the feature flag(s) required in PR descriptions, as it took me a solid couple of minutes to find that I'm just missing the `unseen-event-properties` flag.

File: cypress/integration/events.js [hunk 3]
```diff
@@ -22,7 +22,9 @@ const interceptPropertyDefinitions = () => {
 const selectNewTimestampPropertyFilter = () => {
     cy.get('[data-attr=new-prop-filter-EventsTable]').click()
     cy.get('[data-attr=taxonomic-filter-searchfield]').type('$time')
-    cy.get('.taxonomic-list-row').should('have.length', 1).click()
+    cy.get('.taxonomic-list-row').should('have.length', 1)
+    // don't click on .skeleton-row
```
[the remark this answers is not in the document]
Comment (mariusandra) [reply cypress/integration/events.js:26]: Misleading comment removed. 

Backstory: at some point the tests would flake here by clicking on a `.taxonomic-list-row` that was actually the "loading" skeleton, causing the test to fail, as the `onClick` handler didn't select the element.

File: frontend/src/lib/components/TaxonomicFilter/taxonomicFilterLogic.tsx (hunk 2 above)
Comment (mariusandra) [reply frontend/src/lib/components/TaxonomicFilter/taxonomicFilterLogic.tsx]: Fixed that by saying "this" or "these" as appropriate.

If one of the series is an action that contains an event in any of its steps, `eventNames` will include them here.

**Comment by mariusandra** [comment]
I think I addressed all the points. Ready for another look @Twixes

**Review by Twixes — APPROVED** [review]
Looks good to me! Don't know about Cypress though

**Review by alexkim205 — APPROVED** [review]
