### PR TITLE
feat(insights): Show custom series name in muted style and fix renaming

### LINKED ISSUE #19536: Rename graph series button not working inside of `Detailed results` section
## Bug description

2023-12-28 at 15 58 31@2x

## How to reproduce

1. Open an insight
2. Try to rename a chart series using the edit button in the `Detailed results` section

## Workaround

Use the edit button above (see screenshot)

## Additional context

https://posthoghelp.zendesk.com/agent/tickets/8681

### PR DESCRIPTION
**Pull request by webjunkie**
## Problem

When giving a custom series name, some users want the original name to disappear.

## Changes

- at least make it more subtle
- also added: fix renaming
- when renaming, we also need to reload the insight, otherwise the renamed name does not show within the insight chart or data (and users would assume that it has not renamed)

image

## How did you test this code?

- 👀

### CODE REVIEW

**Review by Twixes — CHANGES_REQUESTED** [review]
Looks fine in non-clickable contexts, but in clickable ones the primary color erases the difference:

Screenshot 2024-03-06 at 12 56 38

File: frontend/src/scenes/insights/filters/ActionFilter/entityFilterLogic.ts [hunk 1]
```diff
@@ -174,6 +177,13 @@ export const entityFilterLogic = kea<entityFilterLogicType>([
                 index: number
             })
             actions.hideModal()
+
+            await breakpoint(100)
+
+            const dataLogic = insightDataLogic.findMounted({
+                dashboardItemId: props.typeKey,
+            })
+            dataLogic?.actions?.loadData(true)
```
Comment (webjunkie) [inline frontend/src/scenes/insights/filters/ActionFilter/entityFilterLogic.ts:186]: This doesn't always fire after setting the renamed series/filters as far as I tested 🤔 
Do you have an idea how to make sure that this happens in the correct order? Not sure I'm using the logics the best way.

**Comment by webjunkie** [comment]
I also added a fix for renaming problems, fixes #19536

File: frontend/src/scenes/insights/filters/ActionFilter/entityFilterLogic.ts (hunk 1 above)
Comment (webjunkie) [reply frontend/src/scenes/insights/filters/ActionFilter/entityFilterLogic.ts:186]: Also seems to pose a problem in tests... any help appreciated.

Comment (neilkakkar) [reply frontend/src/scenes/insights/filters/ActionFilter/entityFilterLogic.ts:186]: Most probably `insightDataLogic` with the right prop isn't mounted. No context, but is it supposed to always exist? If yes, you might want to `connect` it so it mounts always with this logic action. I assume then `loadData` will always fire, since it will always exist

**Review by Twixes — APPROVED** [review]
Nice, looks good!
