### PR TITLE
Possible fix for action/event dropdown

### LINKED ISSUE #1909: Actions aren't appearing when you try to view them in dropdown
## Bug description

*Please describe.*  
If you try to add an entity and start on the raw events dropdown, clicking on actions will show nothing
*If this affects the front-end, screenshots would be of great help.*  
Screen Shot 2020-10-16 at 4 05 29 PM

## Expected behavior
Actions should be loaded
## How to reproduce

1. Go to insights page /trends. Make sure there's already an entity added that's an event (the default $pageview event should be there)
2. Click on $pageview to change the entity
3. Try to change to an action

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

### PR DESCRIPTION
**Pull request by EDsCODE**
## Changes

*Please describe.*  
*If this affects the front-end, include screenshots.*  

## Checklist

- [ ] All querysets/queries filter by Organization, Team, and User (if this PR affects ANY querysets/queries).
- [ ] Django backend tests (if this PR affects the backend).
- [ ] Cypress end-to-end tests (if this PR affects the frontend).

### CODE REVIEW

File: frontend/src/scenes/insights/ActionFilter/ActionFilterDropdown.js [hunk 1]
```diff
@@ -89,7 +89,7 @@ export function ActionPanelContainer({ entityType, panelIndex, options, logic })
     }
 
     const message = () => {
-        if (entityType === EntityTypes.ACTIONS && !filters[EntityTypes.ACTIONS]?.length) {
+        if (entityType === EntityTypes.ACTIONS && !options.length) {
```
Comment (EDsCODE) [inline frontend/src/scenes/insights/ActionFilter/ActionFilterDropdown.js:92]: the prompt was conditional on the wrong values
