### PR TITLE
fix(flags): respect person property overrides in `/flags` for super condition flags

### LINKED ISSUE #33641: early access feature toggle often takes multiple clicks for a feature toggle to stick
### Bug Description

Context: https://posthog.slack.com/archives/C07Q2U4BH4L/p1749654415862209

### Debug info

```shell

```

### PR DESCRIPTION
**Pull request by dmarticus**
> [!IMPORTANT]
> 👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Problem

Closes [33641](https://github.com/PostHog/posthog/issues/33641)

- This should fix the flapping early access feature flag problem, since the issue was that we'd be sending a property override in the request, but then we'd call `/flags` and rather than respecting the override, we'd fall back to the DB and, if the property hadn't been ingested yet, return the old value.  This is why it eventually worked.

## Changes

- Fixed the behavior
- A boatload of tests

https://www.loom.com/share/f61117bf07a040719b9a71590cbc7cd8

## Did you write or update any docs for this change?

- [x] No docs needed for this change

## How did you test this code?

- unit tests for the override merging
- integration tests for the whole flow

### CODE REVIEW

File: rust/feature-flags/src/flags/flag_matching_utils.rs [hunk 1]
```diff
@@ -667,6 +679,108 @@ mod tests {
...
+            key: "email".to_string(),
+            value: Some(json!("user@example.com")),
+            operator: Some(OperatorType::Exact),
+            prop_type: PropertyType::Person,
+            group_type_index: None,
+            negation: None,
+        }];
+
+        // With the bug fix, overrides should be returned even though the flag
+        // doesn't explicitly check for $feature_enrollment/discussions
```
Comment (haacked) [inline rust/feature-flags/src/flags/flag_matching_utils.rs]: Maybe I'm being dense, but this comment is confusing. Mainly, I don't understand why the flag _would_ check for `$feature_enrollment/discussions`.

Was the issue that the old code required a condition for all override properties rather than the other way around?

**Review by haacked — APPROVED** [review]
:shipit: Code and tests look good to me, even if a comment confuses me a bit.
