### PR TITLE
fix(flags): don't use the cohort `not_in` operators for feature flags, since we don't support that operation in flag matching yet

### LINKED ISSUE #25092: `user_blast_radius` calculations aren't respecting the `not_in` operator when calculating amount of cohort membership
## Bug description

See this ticket: https://posthoghelp.zendesk.com/agent/tickets/18234.

### Reproduction steps

1. Create a cohort that has some members
2. Create a feature flag and have it do user targeting based on cohort membership
3. Notice that the amount of people returned are always the members _in_ the cohort, even if the operator is `not_in`.

### Additional context

Here's an example test that should pass when it's been fixed
```
    @snapshot_clickhouse_queries
    def test_user_blast_radius_with_single_not_in_cohort(self):
        for i in range(10):
            _create_person(
                team_id=self.team.pk,
                distinct_ids=[f"person{i}"],
                properties={"group": f"{i}"},
            )

        cohort1 = Cohort.objects.create(
            team=self.team,
            filters={
                "properties": {
                    "type": "OR",
                    "values": [
                        {
                            "type": "OR",
                            "values": [
                                {"key": "group", "value": "none", "type": "person"},
                                {"key": "group", "value": [1, 2, 3], "type": "person"},
                            ],
                        }
                    ],
                }
            },
            name="cohort1",
        )

        response = self.client.post(
            f"/api/projects/{self.team.id}/feature_flags/user_blast_radius",
            {
                "condition": {
                    "properties": [{"key": "id", "type": "cohort", "value": cohort1.pk, "operator": "not_in"}],
                    "rollout_percentage": 100,
                }
            },
        )

        self.assertEqual(response.status_code, status.HTTP_200_OK)

        response_json = response.json()
        self.assertDictContainsSubset({"users_affected": 7, "total_users": 10}, response_json)

        # test the same with precalculated cohort. Snapshots shouldn't have group property filter
        cohort1.calculate_people_ch(pending_version=0)

        with self.settings(USE_PRECALCULATED_CH_COHORT_PEOPLE=True):
            response = self.client.post(
                f"/api/projects/{self.team.id}/feature_flags/user_blast_radius",
                {
                    "condition": {
                        "properties": [{"key": "id", "type": "cohort", "value": cohort1.pk, "operator": "not_in"}],
                        "rollout_percentage": 50,
                    }
                },
            )

            self.assertEqual(response.status_code, status.HTTP_200_OK)

            response_json = response.json()
            self.assertDictContainsSubset({"users_affected": 7, "total_users": 10}, response_json)
```

### PR DESCRIPTION
**Pull request by dmarticus**
## Problem

We had [several](https://posthoghelp.zendesk.com/agent/tickets/18234) [users](https://posthoghelp.zendesk.com/agent/tickets/18484) write in about how the `not_in` operator wasn't working when trying to set up their cohort matching.  Turns out, we [didn't even mean](https://posthog.slack.com/archives/C034XD440RK/p1726854046684919) to make that feature available, since we don't support `not_in` operations for matching feature flag cohorts (yet).  

This is the simplest fix I could think of to get users back into a flow where they can't accidentally make flags that don't match in the way they'd expect them to – users _can_ save these flags with invalid matching conditions, but fortunately (as of 14:47 Pacific Time on September 23), only one user has tried this, and it was me testing if it was possible at all.  So the user impact seems limited to folks who wrote in noticing that the blast radius calculation was wrong.

image

this functionally closes: https://github.com/PostHog/posthog/issues/25092

## Changes

The behavior for using cohort filters on the feature flag page is now back to the way it was before https://github.com/PostHog/posthog/pull/24848.  All other pages should keep the new cohort matching behavior.  Loom: https://www.loom.com/share/07d0141285cc429f911a849881cbb320

## Does this work well for both Cloud and self-hosted?

Yes

## How did you test this code?

Visual regression tests.

### CODE REVIEW

File: frontend/src/lib/components/DefinitionPopover/utils.ts [hunk 1]
```diff
@@ -23,6 +23,10 @@ export function genericOperatorToHumanName(property?: AnyPropertyFilter | null):
 
 export function allOperatorsToHumanName(operator?: PropertyOperator | null): string {
     if (operator && allOperatorsMapping[operator]) {
+        // for the case of cohort, we want to return the operator name without the "In" prefix
+        if (operator === PropertyOperator.In) {
+            return 'in'
+        }
```
Comment (dmarticus) [inline frontend/src/lib/components/DefinitionPopover/utils.ts:29]: this is so that I can see this behavior

image

instead of this behavior

image

Maybe risky going forward, but this method is only used in the FeatureFlagReleaseConditions.tsx file so there's no risk to it damaging other parts of the product.  It's just a bit hacky.

File: frontend/src/lib/components/PropertyFilters/PropertyFilters.tsx [hunk 2]
```diff
@@ -38,6 +38,7 @@ interface PropertyFiltersProps {
     propertyAllowList?: { [key in TaxonomicFilterGroupType]?: string[] }
     allowRelativeDateOptions?: boolean
     disabledReason?: string
+    exactMatchFeatureFlagCohortOperators?: boolean
```
Comment (dmarticus) [inline frontend/src/lib/components/PropertyFilters/PropertyFilters.tsx:41]: this feels like _such_ kludge to prop drill this value but it was the easiest way to get this fix out and specify it explicitly for the feature flag release conditions.  It's pretty annoying that we can't do advanced cohort matching for feature flags alone.  Open to ideas on a better way to do this.

File: frontend/src/lib/components/PropertyFilters/components/TaxonomicPropertyFilter.tsx [hunk 3]
```diff
@@ -85,7 +86,11 @@ export function TaxonomicPropertyFilter({
     const showInitialSearchInline =
         !disablePopover &&
         ((!filter?.type && (!filter || !(filter as any)?.key)) || filter?.type === PropertyFilterType.HogQL)
-    const showOperatorValueSelect = filter?.type && filter?.key && filter?.type !== PropertyFilterType.HogQL
+    const showOperatorValueSelect =
+        filter?.type &&
+        filter?.key &&
+        !(filter?.type === PropertyFilterType.HogQL) &&
+        !(filter?.type === PropertyFilterType.Cohort && exactMatchFeatureFlagCohortOperators)
```
Comment (dmarticus) [inline frontend/src/lib/components/PropertyFilters/components/TaxonomicPropertyFilter.tsx:93]: I use this prop to get rid of the operator value selector so we can have the same experience that we had before Sandy's change went in.

File: frontend/src/scenes/feature-flags/FeatureFlagReleaseConditions.tsx [hunk 4]
```diff
@@ -244,6 +244,7 @@ export function FeatureFlagReleaseConditions({
                                           })
                                         : null
                                 }
+                                exactMatchFeatureFlagCohortOperators={true}
```
Comment (dmarticus) [inline frontend/src/scenes/feature-flags/FeatureFlagReleaseConditions.tsx:247]: passing it into the FeatureFlagReleaseConditions component, which is the only place I need to do it (this component is reused when setting up feature flag targeting in surveys).

**Review by aspicer — APPROVED** [review]
Looks good! Thanks.

The flag isn't any worse than the rest of the props, and it cleans this up quick, so perfect!
