### PR TITLE
Fix funnel trends incomplete data points when conversion window overlaps

### LINKED ISSUE #7645: Funnel trends broken
## Bug description

- Date range not applied
- Conversion windows not respected

## Expected behavior
- Data points before the conversion window is completed should be incomplete data points
- The chart should contain the dates that the query says it contains

## How to reproduce

1. View this [funnel](https://app.posthog.com/insights/Y1k2Wbh9/edit?insight=FUNNELS&actions=%5B%7B%22id%22%3A%222674%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22name%22%3A%22User%20Signed%20Up%20(Comprehensive)%22%2C%22math%22%3A%22dau%22%7D%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22math%22%3A%22dau%22%2C%22properties%22%3A%5B%7B%22key%22%3A%22email%22%2C%22value%22%3A%22is_not_set%22%2C%22operator%22%3A%22is_not_set%22%2C%22type%22%3A%22event%22%7D%5D%7D%5D&display=FunnelViz&layout=horizontal&interval=day&properties=%5B%5D&filter_test_accounts=true&funnel_to_step=1&funnel_viz_type=trends&exclusions=%5B%5D&funnel_from_step=0) or this [Slack thread](https://posthog.slack.com/archives/C02283301EK/p1639160785465300)
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

### PR DESCRIPTION
**Pull request by alexkim205**
## Changes

Closes #7645

Changes: Now we indicate incomplete data in funnel trends whenever there is overlap with conversion window time ranges and the current date. 

https://user-images.githubusercontent.com/13460330/145903587-1d672287-0d9f-486f-850e-b9acbc6d99d4.mov

## How did you test this code?

Util test + manual visual QA + regression tests pass (for other line graphs pass).

### CODE REVIEW

File: frontend/src/scenes/insights/LineGraph/LineGraph.jsx [hunk 1]
```diff
@@ -213,6 +211,7 @@ export function LineGraph({
         } else {
             datasets = datasets.map((dataset, index) => processDataset(dataset, index))
         }
+        console.log('STEPS datasets', datasets)
```
Comment (EDsCODE) [inline frontend/src/scenes/insights/LineGraph/LineGraph.jsx:214]: remove console log

**Review by EDsCODE — APPROVED** [review]
