### PR TITLE
Tweak action toolbar

### LINKED ISSUE #889: Actions can be saved without names
**Describe the bug**
You can save actions without names, which looks weird in the interface

**To Reproduce**
1. Manually create an action for a front end element (NOT using the toolbar)
2. Don't give it a name
3. Press save
4. It saves

**Expected behavior**

Error "needs a name" or similar

### PR DESCRIPTION
**Pull request by EDsCODE**
## Changes
- fixes #889 
- took some liberties with reshaping the toolbar (removed save & new action, added a view button to redirect users back to posthog.com)
- updating an action on toolbar wasn't working
- updated new modal so it doesn't double over itself

## Checklist
- [ ] All querysets/queries filter by Team (if applicable)
- [ ] Backend tests (if applicable)
- [ ] Cypress E2E tests (if applicable)

### CODE REVIEW

File: frontend/src/scenes/actions/actionEditLogic.js [hunk 1]
```diff
@@ -60,7 +60,7 @@ export const actionEditLogic = kea({
             })
             try {
                 if (action.id) {
-                    action = await api.update(props.apiURL + 'api/action/' + action.id, action)
+                    action = await api.update(props.apiURL + 'api/action/' + action.id + '/', action)
```
Comment (EDsCODE) [inline frontend/src/scenes/actions/actionEditLogic.js:63]: update was never working because of this missing '/' :(

**Comment by EDsCODE** [comment]
Didn't go about refactoring as much as I could've (hooks, ui, etc.) since @mariusandra is going to be working on the new toolbar soon

**Comment by mariusandra** [comment]
Cool, thanks for fixing this! Merged

**Review by mariusandra — APPROVED** [review]
