### PR TITLE
fix(flags): handle gzip compression on requests

### LINKED ISSUE #33752: fix gzip for `/flags` on android
context: https://posthog.slack.com/archives/C07Q2U4BH4L/p1750059277047069?thread_ts=1749803054.185859&cid=C07Q2U4BH4L

### PR DESCRIPTION
**Pull request by dmarticus**
> [!IMPORTANT]
> 👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Problem

fixes https://github.com/PostHog/posthog/issues/33752

## Changes

Adds explicit gzip decoding and a bunch of tests for it

## Did you write or update any docs for this change?

- [x] No docs needed for this change

## How did you test this code?

new unit tests
existing tests passed
tested it on a local gzip file

### CODE REVIEW

File: rust/feature-flags/src/flags/flag_request.rs [hunk 1]
```diff
@@ -71,10 +71,19 @@ impl FlagRequest {
...
-            FlagError::RequestDecodingError(String::from("invalid body encoding"))
-        })?;
+        // Handle UTF-8 conversion more gracefully, similar to form data handling
+        let payload = match String::from_utf8(bytes.to_vec()) {
+            Ok(s) => s,
+            Err(e) => {
+                tracing::debug!(
+                    "Invalid UTF-8 in request body, using lossy conversion: {}",
+                    e
+                );
```
[the remark this answers is not in the document]
Comment (dmarticus) [reply rust/feature-flags/src/flags/flag_request.rs:81]: no ❤️

**Review by andyzzhao — APPROVED** [review]

File: rust/feature-flags/src/flags/flag_request.rs [hunk 2]
```diff
@@ -71,10 +71,19 @@ impl FlagRequest {
...
+                // Use lossy conversion as fallback - this handles Android clients that might
+                // send malformed UTF-8 sequences after decompression
```
Comment (marandaneto) [inline rust/feature-flags/src/flags/flag_request.rs:83]: interesting that the old /decide didn't fail, though
if its a malforled utf8, this should have failed on /decide too
let me know once this is released, i can test if needed

File: rust/feature-flags/src/handler/decoding.rs [hunk 3]
```diff
@@ -38,21 +38,61 @@ pub fn decode_request(
...
+            Compression::Gzip => decompress_gzip(body),
+            Compression::Base64 => decode_base64(body),
+            Compression::Unsupported => Err(FlagError::RequestDecodingError(
+                "Unsupported compression type".to_string(),
+            )),
+        };
+    }
+
+    // Auto-detect gzip by checking magic bytes (0x1f, 0x8b) if no compression specified
+    // This handles cases where Android sends gzipped data without the compression query param
```
Comment (marandaneto) [inline rust/feature-flags/src/handler/decoding.rs]: `compression=gzip-js` should be optional though since we set `http.header("Content-Encoding", "gzip")`
