### PR TITLE
Resolves #3801 - Test users filters

### LINKED ISSUE #3801: Test users filters break when adding new filter
## Bug description

When I finish typing another URL to exclude and hit `Return`, the previous default filters are lost. Remnants of only empty chips are left in their place.

image

**Demo:** 
https://www.loom.com/share/d7df3d5a0fda49d499451e75777af5ed

## Expected behavior

Retain the existing filters and just add the new one.

Bonus UX enhancement: Don't let the length of text change the width of the property pane (seen in the video between `0:09`-`0:13`).

## How to reproduce

1. Create a new Cloud account
2. Go to Project page and type something like `localhost:3000`, then `Return`
3. Previous filters will now disappear

## Environment

PostHog Cloud

### PR DESCRIPTION
**Pull request by samwinslow**
## Changes

- Fixes disappearing filters in "Filter out test users" section of project settings
- Flex-sized columns in the property pane are now fixed width
- Closes #3801

As shown here, the fixed-width columns obscure some data. This might not be ideal, even though it looks less "jumpy" than before.

Screen Shot 2021-04-01 at 6 23 18 PM

First PR in this repository! Please feel free to point out anything about code style, naming of branches/commits, etc. that can ease my transition into the team.

## Checklist

- [x] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [x] Jest frontend tests
- [x] Cypress end-to-end tests

### CODE REVIEW

File: frontend/src/lib/components/PropertyFilters/PropertyFilter.js [hunk 1]
```diff
@@ -58,11 +58,11 @@ function PropertyPaneContents({
                                           propkey,
                                   }
                         }
-                        onChange={(type, value) =>
+                        onChange={(type, _value) =>
```
Comment (paolodamico) [inline frontend/src/lib/components/PropertyFilters/PropertyFilter.js:61]: FYI @samwinslow fixed this shadow variable issue (pre-existing), but think it demonstrates our typical bias for action / tread on toes workflow.

**Review by paolodamico — CHANGES_REQUESTED** [review]
Great initial approach! Seems like the values disappearing thing has been fixed!

Did notice a couple of UX problems (see recording below):
1. The initial input is quite small, and it's hard to read the properties
2. Input gets resized way out of bounds of the window.

image

3. Not part of the original issue, but after you specify a custom option, it's quite confusing that you keep seeing the same option only until you figure out you need to start typing again. It's particularly confusing if you're looking to add a custom option first and an autofill one second.

image


Also a minor thing FYI, I think GitHub does not link the issues if you add the Resolves keyword on the title, so I added it in the description of the PR.

**Comment by paolodamico** [comment]
One final comment is that you may want to take a stab at converting these files to Typescript (totally optional), but at least this bug could've probably been prevented with that.

**Review by samwinslow — COMMENTED** [review]
@paolodamico 

Re: custom option suggestions, that has been fixed. Good catch!
Re: resizing, here's a GIF showing improved styling (with max-width of 50vw on the value input):
Screen Shot 2021-04-02 at 2 19 36 PM (2)

I also added a title prop to the "tag"... because it is not an actual ant-design Tag component, the styling won't look right if I pass a `<Tag />`, so I have recreated the markup ant-design normally renders. This means super-long URLs can be inspected by mouseover.

File: frontend/src/lib/components/PropertyFilters/PropertyValue.js [hunk 2]
```diff
@@ -64,11 +64,11 @@ export function PropertyValue({
...
                 autoFocus={!value && !isMobile()}
                 style={{ width: '100%', ...style }}
-                onChange={(_, payload) => {
+                onChange={(value, payload) => {
                     if (isOperatorMulti(operator) && payload.length > 0) {
-                        onSet(payload.map(({ value: val }) => val))
+                        onSet(value)
                     } else {
-                        onSet((payload && payload.value) || null)
+                        onSet(payload?.value ?? null)
```
[the remark this answers is not in the document]
Comment (paolodamico) [reply frontend/src/lib/components/PropertyFilters/PropertyValue.js]: Yeah I believe this is fine

File: frontend/src/lib/components/PropertyFilters/OperatorValueSelect.tsx [hunk 3]
```diff
@@ -83,13 +83,14 @@ export function OperatorSelect({ operator, operators, onChange }: OperatorSelect
                 label: operatorMap[operator || 'exact'],
             }}
             placeholder="Property key"
-            onChange={(_, newOperator) => {
-                onChange(newOperator.value as PropertyOperator)
+            onChange={(_value, op) => {
+                const newOperator = op as { value: PropertyOperator } & Record<string, any>
```
Comment (paolodamico) [inline frontend/src/lib/components/PropertyFilters/OperatorValueSelect.tsx:87]: Why the `Record<string, any>`? Are there any other components that are not properly typed that this could be hiding?

File: frontend/src/lib/components/SelectGradientOverflow.tsx [hunk 4]
```diff
@@ -20,6 +21,27 @@ function DropdownGradientRenderer({
...
+ * Ant Design does not export the component used in multi-select lists,
+ * so we're recreating it with a title property for better UX
+ */
+type CustomTagProps = Parameters<Exclude<SelectProps<any>['tagRender'], undefined>>[0]
+
+function CustomTag({ label, onClose, value }: CustomTagProps): JSX.Element {
+    return (
+        <div className="ant-select-selection-overflow-item">
+            <span className="ant-select-selection-item">
+                <span className="ant-select-selection-item-content" title={value.toString()}>
```
Comment (paolodamico) [inline frontend/src/lib/components/SelectGradientOverflow.tsx:34]: If we're going to do this entire override, might be worth using `Tooltip` component instead of browser's title? It'd be a matter of testing to see if this provides better UX, but just a hunch.

Also, if I understand correctly the reason to re-write this code is that the component cannot be imported? Becuase a simple wrap in a `Tooltip` will definitely make for more cleaner/reusable code.

File: frontend/src/lib/components/PropertyFilters/PropertyFilters.js [hunk 5]
```diff
@@ -29,7 +29,14 @@ const FilterRow = React.memo(function FilterRow({
     }
 
     return (
-        <Row align="middle" className="mt-05 mb-05" data-attr={'property-filter-' + index}>
+        <Row
```
Comment (paolodamico) [inline frontend/src/lib/components/PropertyFilters/PropertyFilters.js:32]: Great improvement here! Still looks weird in small screens, but not a blocker for now, it seems unlikely someone would want to update this on a mobile device.

**Review by paolodamico — CHANGES_REQUESTED** [review]
Almost there! Found a couple of errors when testing out (probably with Cypress tests aren't passing),

- These happened when I tried to add a new test filter.

File: frontend/src/lib/components/SelectGradientOverflow.tsx (hunk 4 above)
Comment (samwinslow) [reply frontend/src/lib/components/SelectGradientOverflow.tsx]: Rewrote this to use a `Tooltip` wrapped around a `Tag` with custom CSS
