### PR TITLE
Sessions table bug fixes

### LINKED ISSUE #4960: Bugs/improvements on better sessions
Some late feedback on #4840.

1. After I've opened a person page, the back button on the browser doesn't work, it keeps me in the person page but with some weird behavior going on. I'd expect to be able to get back to the person list if I click back.
2. Related to the above, if I click back to insights the person modal is closed when I get back.
3. The "matches" terminology seems a bit confusing. I don't know what I'm matching against. Maybe we should specify the exact event/action, or say something like "matches your trend query", not sure. CC @clarkus 
    
4. The hover background color is very unintuitive, color should probably be a darker shade of yellow. You can try yellow 100 or darkening 10% the highlight color, but tagging @clarkus who will probably have a better idea.
    image
5. I don't think expand all sessions should be a toggle but rather a button, because you can change the state of the sessions manually and then the toggle will show incorrect information. I would have here an "Expand all sessions"/"Collapse all sessions" button.
6. Something weird going on with the play all button, spacing is off.

### PR DESCRIPTION
**Pull request by alexkim205**
## Changes

Closes #4960. See discussion for more info.

1. Hide 'expand all' button behind FF for ux and performance reasons
Screen Shot 2021-07-02 at 1 58 28 PM

2. Darker highlighting

https://user-images.githubusercontent.com/13460330/124318685-db0cea00-db2d-11eb-84f0-e2ae5ca30e7f.mov

3. Change wording of tooltip

Screen Shot 2021-07-02 at 3 47 39 PM

4. Emphasis and clear imaging for individual events

Screen Shot 2021-07-02 at 3 48 09 PM

+ a few more minor UI bugs

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [X] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [X] Frontend/CSS is usable at 320px (iPhone SE) and decent at 360px (most phones)
- [ ] Breaking changes are backwards-compatible. Ensure old/new frontend requests work with new/old backends, and vice versa.

### CODE REVIEW

File: frontend/src/scenes/sessions/sessionsTableLogic.ts [hunk 1]
```diff
@@ -176,8 +186,17 @@ export const sessionsTableLogic = kea<sessionsTableLogicType<SessionRecordingId>
                 ),
         ],
         expandedRowKeys: [
-            (selectors) => [selectors.sessions],
-            (sessions: SessionType[]): string[] => sessions?.map((s) => s.global_session_id) || [],
+            (selectors) => [selectors.sessions, selectors.rowExpandState],
+            (sessions: SessionType[], rowExpandState: ExpandState): string[] | boolean => {
```
Comment (macobo) [inline frontend/src/scenes/sessions/sessionsTableLogic.ts:190]: `string[] | boolean` is such a weird type and does not match with the name -> code smell.

Would empty array work for the 2nd case?

Alternatively how about renaming this `expandedRowKeysProps` and returning either `{}` or `{ expandedRowKeys: [1,2,3] }` - this avoids weird hacks in the component.

File: frontend/src/scenes/sessions/sessionsTableLogic.ts [hunk 2]
```diff
@@ -176,8 +186,17 @@ export const sessionsTableLogic = kea<sessionsTableLogicType<SessionRecordingId>
...
+                if (rowExpandState === ExpandState.collapsed) {
+                    return []
+                }
+                if (rowExpandState === ExpandState.manual) {
+                    return false
+                }
+                // expand all
+                return sessions?.map((s) => s.global_session_id) || []
```
Comment (macobo) [inline frontend/src/scenes/sessions/sessionsTableLogic.ts:198]: Is this the case when `ExpandState.expanded`? Code could also be cleaner here to indicate that. 

Example:

```
switch(rowExpandState) {
  case ExpandState.collapsed: 
    return []
  case ExpandState.collapsed: 
    return something
  case ExpandState.expanded:
    return something
}
```

This has the benefit of erroring when a new expand state is added

Comment (macobo) [reply frontend/src/scenes/sessions/sessionsTableLogic.ts:198]: Is the `?` and default needed here? The type above `sessions: SessionType[]` indicates it's always an array. If that's not true, we should fix the type first.

File: frontend/src/scenes/sessions/sessionsTableLogic.ts [hunk 3]
```diff
@@ -10,6 +10,12 @@ import { sessionsFiltersLogic } from 'scenes/sessions/filters/sessionsFiltersLog
 
 type SessionRecordingId = string
 
+enum ExpandState {
+    expanded,
```
Comment (macobo) [inline frontend/src/scenes/sessions/sessionsTableLogic.ts:14]: Other enums are capitalized throughout the codebase - worth keeping it consistent.

File: frontend/src/scenes/sessions/sessionsTableLogic.ts [hunk 4]
```diff
@@ -10,6 +10,12 @@ import { sessionsFiltersLogic } from 'scenes/sessions/filters/sessionsFiltersLog
...
+    collapsed,
+    manual,
```
Comment (macobo) [inline frontend/src/scenes/sessions/sessionsTableLogic.ts:16]: This name is confusing - what does manual mean? When can something manually expand?

**Comment by macobo** [comment]
It's worth adding screenshots to the PR as well since the images under the issue are mostly for discussion and might be out of date.

---

Feedback: The UX around these filters feels confusing. 

image

Expanding "all" sessions is also a weird operation - why would you do that? If you go under app.posthog.com under a realistic load, you have 100s of sessions each with tens to thousands of events - expanding them all loads a lot of data that is just noisy on the screen and does not deliver any value.

That said if your team decides to go for it :+1:

File: frontend/src/scenes/sessions/SessionDetails.tsx [hunk 5]
```diff
@@ -90,6 +93,23 @@ export function SessionDetails({ session }: { session: SessionType }): JSX.Eleme
                 },
                 rowExpandable: (event) => !!event,
                 expandRowByClick: true,
+                columnWidth: ANTD_EXPAND_BUTTON_WIDTH + MATCHING_EVENT_ICON_SIZE,
+                expandIcon: function _renderExpandIcon(expandProps) {
+                    const { record: event } = expandProps
```
Comment (macobo) [inline frontend/src/scenes/sessions/SessionDetails.tsx:98]: Probably worth doing this above? E.g. `function _renderExpandIcon({ record }) {

File: frontend/src/scenes/sessions/SessionDetails.tsx [hunk 6]
```diff
@@ -90,6 +93,23 @@ export function SessionDetails({ session }: { session: SessionType }): JSX.Eleme
...
+                    return (
+                        <ExpandIcon {...expandProps}>
+                            {(session.matching_events || []).includes(event.id) ? (
```
Comment (macobo) [inline frontend/src/scenes/sessions/SessionDetails.tsx:101]: Note: You're introducing n^2 search here which can cause issues whenever someone is using a slower computer on a large project. Is it guaranteed that both arrays are small?

If not, worth considering using `Set` object.

**Comment by macobo** [comment]
On heroku the expand all does not seem to work properly, it stays loading forever.

https://user-images.githubusercontent.com/148820/124277217-795c7800-db4d-11eb-84aa-61c6ba6673e1.mp4

I assume the issue is with `loadSessionEvents` not being called properly. Postgres loads events lazily as rows get expanded and over time (for performance reasons) so will clickhouse.

However just calling `loadSessionEvents` on all of them is also crazy expensive and introduces a lot of load.

File: frontend/src/scenes/sessions/SessionDetails.tsx (hunk 5 above)
Comment (alexkim205) [reply frontend/src/scenes/sessions/SessionDetails.tsx:98]: Hm I did this because I still need the whole expandProps object in line 100

File: frontend/src/scenes/sessions/SessionDetails.tsx (hunk 6 above)
Comment (alexkim205) [reply frontend/src/scenes/sessions/SessionDetails.tsx:101]: makes sense! I think it's worth changing because we perform the same computation in line 76

File: frontend/src/scenes/sessions/sessionsTableLogic.ts (hunk 4 above)
Comment (alexkim205) [reply frontend/src/scenes/sessions/sessionsTableLogic.ts:16]: Good point- what about [Uncontrolled](https://reactjs.org/docs/uncontrolled-components.html) or Unset?

Comment (macobo) [reply frontend/src/scenes/sessions/sessionsTableLogic.ts:16]: Both seem fine :+1:

File: frontend/src/scenes/sessions/SessionDetails.tsx (hunk 5 above)
Comment (macobo) [reply frontend/src/scenes/sessions/SessionDetails.tsx:98]: Didn't catch that, my bad!

File: frontend/src/scenes/sessions/sessionsTableLogic.ts (hunk 1 above)
Comment (alexkim205) [reply frontend/src/scenes/sessions/sessionsTableLogic.ts:190]: Thanks! that makes sense. Still kind of hacky that I'm inferring state from the "emptiness" of an object. Maybe I can also pass in a `state: ExpandState` key into this object to be more explicit?

File: frontend/src/scenes/sessions/SessionDetails.tsx (hunk 5 above)
Comment (alexkim205) [reply frontend/src/scenes/sessions/SessionDetails.tsx:98]: no worries!

File: frontend/src/scenes/sessions/sessionsTableLogic.ts (hunk 1 above)
Comment (alexkim205) [reply frontend/src/scenes/sessions/sessionsTableLogic.ts:190]: Ah I see what you're getting at! super clean that we can just drop this into `expandable`

**Comment by alexkim205** [comment]
Bringing over the discussion from the [issue](https://github.com/PostHog/posthog/issues/4960#issuecomment-873029812) here:

> > It also adds a ton of load to our servers to send megabytes of raw event data from the API.
> 
> I actually think we query for all events already upon first load of the sessions page, so expanding all sessions won't incur any more network costs than we already have. However I think this is only true for our Clickhouse users and not our SH users. We could also hide the expand all button behind a `is_clickhouse_enabled` check?
>
> @macobo & @paolodamico what are your thoughts?

File: frontend/src/scenes/sessions/SessionDetails.tsx [hunk 7]
```diff
@@ -16,6 +19,7 @@ export function SessionDetails({ session }: { session: SessionType }): JSX.Eleme
     const [page, setPage] = useState(1)
     const [pageSize, setPageSize] = useState(50)
     const events = session.events || filteredSessionEvents[session.global_session_id]
+    const matchingEventIds = new Set(session.matching_events || [])
```
Comment (macobo) [inline frontend/src/scenes/sessions/SessionDetails.tsx:22]: Note: In the ideal world this belongs in the logic, not the component. Every re-render it would recalculate this. In practice this should be quite cheap though unless we rerender in a loop.

Comment (macobo) [reply frontend/src/scenes/sessions/SessionDetails.tsx:22]: Suggestion: `useMemo`?

**Review by macobo — COMMENTED** [review]
Thanks for the changes. One small nitpick remains!

Up to you whether to merge it here or wait for a in-team review.

**Review by paolodamico — APPROVED** [review]
Made a few UX tweaks and addressed @macobo's final comment as @alexkim is OOO. Merging.﻿
