### PR TITLE
fix: Unify what's new to go to the changelog

### LINKED ISSUE #19948: Bug: We have two new What's New buttons that do different things
## Bug description

We have a button here, called What's New? which goes to the changelog
screenshot_2024-01-24_at_14 58 15

And one here, called What's New? which opens the sidebar tab about 3000. 
screenshot_2024-01-24_at_14 58 28

Different icons, different targets.

I feel like we can either:

- Retire the 3000 sidetab and direct it to /changelog, so it matches the existing behaviour (easy)
- Remove one of the buttons and redirect the remaining one to point to /changelog (medium)
- Have the changelog open in-app in the sidebar (hard)

Don't have a preference. But two buttons with different behaviours like this is Bad, and we don't need the 3000 sidebar anymore. 

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/settings/project-details#variables]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem

Closes https://github.com/PostHog/posthog/issues/19948

## Changes

- [x] Fixes the account popover button to open the right page
- [x] Fixes not opening the right place if the docs panel wasn't already open
- [x] Remove / replace the side panel "whats new" 3000 stuff.

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

File: frontend/src/layout/navigation/TopBar/AccountPopover.tsx [hunk 1]
```diff
@@ -221,8 +223,10 @@ export function AccountPopoverOverlay(): JSX.Element {
             <AccountPopoverSection>
                 <ThemeSwitcher fullWidth type="tertiary" />
                 <LemonButton
-                    onClick={closeAccountPopover}
-                    to="https://posthog.com/changelog"
+                    onClick={() => {
+                        closeAccountPopover()
+                        openSidePanel(SidePanelTab.Docs, '/changelog')
+                    }}
```
Comment (Twixes) [inline frontend/src/layout/navigation/TopBar/AccountPopover.tsx:229]: It's always keeping the `href` (aka `to`) in links, even if there's some custom in-app handling of the link: It's often frustrating to have de facto links which you can't right-click>"Open in new tab"

Comment (benjackwhite) [reply frontend/src/layout/navigation/TopBar/AccountPopover.tsx:229]: Oh yeah good point

**Review by Twixes — APPROVED** [review]
That's pretty much it, thanks!
