### PR TITLE
fix: Removing target options for survey resets its value to remove validation error

### LINKED ISSUE #22186: Surveys: Can't remove user targeting options without setting rollout
## Bug description

Can't save a survey if you've opened user targeting but not set any properties inside it. Clicking the save button doesn't do anything because of a hidden validation error.

Use case: I wanted to target users, but realized I needed to create a cohort first. So I wanted to save my work, go to another section, then come back.

First, I looked for a trash can icon to remove the first user property I didn't complete. (This should exist.) After not finding this, I clicked the _Remove all user properties_ button.

The default state for the rollout form has no value set. (We should default this to something!) As a result of no value being set _and_ this form now hidden (since I removed user properties), the page can't be submitted due to the validation error.

**[Loom demo](https://www.loom.com/share/7e84a69cb97c4966970b2a796e375826)**

## How to reproduce

1. Create a survey
2. Click _Add user targeting_
3. Click _Remove all user properties_
4. Try to save the form (which won't save)

## Additional context

There are several things we could/should change here:

- [ ] Default _roll out to..._ to some default value (don't show error message by default)
- [ ] If above is done, this should solve the original issue. If we don't do this, the user property should actually be destroyed, not just hidden from the UI
- [ ] Add option to remove an individual user property (trash can icon next to duplicate icon)

### Debug info

```shell
- [X] PostHog Cloud
```

### PR DESCRIPTION
**Pull request by lucasheriques**
## Problem

Fixes https://github.com/PostHog/posthog/issues/22186

When we add property targeting to a surveys and then remove it, we can't save the survey anymore.

Because there's a hidden form validation error hidden in the UI.

To fix it:

- When removing property targeting, remove it from the state as well
- Adds a trash icon next to the property, as suggested on the bug: https://github.com/PostHog/posthog/issues/22186. Then, if it's the last item, we actually remove the whole targeting from the survey

## Changes

CleanShot 2024-12-23 at 15 23 18@2x

Old deleting behavior: https://www.loom.com/share/7e84a69cb97c4966970b2a796e375826

New behavior:

https://github.com/user-attachments/assets/55aad853-7c8e-4ce3-a395-4b41e8b867e7

Notice that now, after removing the property, there's no hidden form validation error.

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

### CODE REVIEW

File: frontend/src/scenes/surveys/SurveyEdit.tsx [hunk 1]
```diff
@@ -732,7 +739,7 @@ export default function SurveyEdit(): JSX.Element {
                                                                     groups: [
                                                                         {
                                                                             properties: [],
-                                                                            rollout_percentage: undefined,
+                                                                            rollout_percentage: 50,
```
Comment (lucasheriques) [inline frontend/src/scenes/surveys/SurveyEdit.tsx:742]: added 50 as the default value for the rollout percentage

Comment (dmarticus) [reply frontend/src/scenes/surveys/SurveyEdit.tsx:742]: why not default to 100?  I feel like generally people treat these targeting conditions as booleans (on/off).

**Review by dmarticus — APPROVED** [review]
one question about a default, but no hard blockers.  Nice work!

**Review by marandaneto — APPROVED** [review]
nice!

File: frontend/src/scenes/surveys/SurveyEdit.tsx (hunk 1 above)
Comment (lucasheriques) [reply frontend/src/scenes/surveys/SurveyEdit.tsx]: updated
