### PR TITLE
fix(login): Consolidate social login buttons to always use `next` properly

### LINKED ISSUE #14565: Clicking an app link when not logged in takes you to the home page after you log in
## Bug description

I often click on links straight to a dashboard or insight that I access frequently (e.g. bookmarks). If I've been logged out of the app, I'll be shown the login screen and prompted to log in again which is fine. 

However, after logging in, I'm then sent to my home view in the app rather than the link I originally clicked on. 

## How to reproduce

1. Sign out of the PostHog app
2. Try to visit a link that requires you to be logged into PostHog
3. Go through the login flow

## Environment

- [x] PostHog Cloud US, project ID: 2
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

### PR DESCRIPTION
**Pull request by Twixes**
## Problem

Resolves #14565 – the `next` redirect worked when using the social login buttons at the bottom of the card, but not when using the "Log in with <provider>" button that popped up for orgs with SSO enforced (such us ours).

## Changes

Fixes the problem by consolidating the SSO link logic into one component, `SSOLoginLink`. Also made sure that we always use the verb "Log in" (two words) as opposed to the noun "Login", and made the SSO enforced login button a bit nicer: it's now secondary instead of tertiary (primary doesn't work because the provider logos don't work on a blue background) + centered like "Log in".

## How did you test this code?

Tested the links locally in Storybook + added a new story to snapshot the login page with SSO enforcement on.

### CODE REVIEW

**Review by raquelmsmith — APPROVED** [review]
Looks good thank you for fixing this!

File: frontend/src/lib/components/SocialLoginButton/index.tsx [hunk 1]
```diff
@@ -2,52 +2,70 @@ import { useValues } from 'kea'
...
     }
 
-    // SAML-based login requires an extra param as technically we can support multiple SAML backends
-    const extraParam = provider === 'saml' ? (queryString ? '&idp=posthog_custom' : '?idp=posthog_custom') : ''
-
     return (
-        <LemonButton
-            size="medium"
-            to={`/login/${provider}/${queryString || ''}${extraParam}`}
-            disableClientSideRouting
```
Comment (pauldambra) [inline frontend/src/lib/components/SocialLoginButton/index.tsx:43]: I guess that shifting from `Link` with `disableClientSideRouting` to an `a` is the cause here https://posthog.slack.com/archives/C0185UNBSJZ/p1678302859353109

Comment (Twixes) [reply frontend/src/lib/components/SocialLoginButton/index.tsx:43]: A `<Link disableClientSideRouting to="">` is literally an `<a href="">`, except with less React complexity involved, so this change is a no-op. Turns out it's the lack of a trailing slash!
