### PR TITLE
fix(insights): fix series color for compare option

### LINKED ISSUE #23665: Colors change in insights when compare is turned on
https://posthoghelp.zendesk.com/agent/tickets/15160

### PR DESCRIPTION
**Pull request by thmsobrmlr**
## Problem

Colors for "previous" result should be a more transparent version of the "current" result. At the moment they are all over the place.

Customer ticket: https://posthoghelp.zendesk.com/agent/tickets/15160 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/19042)

Fixes https://github.com/PostHog/posthog/issues/23665

## Changes

Looks like we've been alternating between "current" and "previous" in the query response before and now we return all "current" options, followed by the "previous" options.

This PR uses the `compare_value` attribute in the response combined with the length of the response value (i.e. it assumes we always have a value for "previous", when there is a value for "current") to determine the color.

## How did you test this code?

Tested locally

### CODE REVIEW

File: frontend/src/lib/components/InsightLegend/InsightLegendRow.tsx [hunk 1]
```diff
@@ -53,24 +53,27 @@ export function InsightLegendRow({ rowIndex, item }: InsightLegendRowProps): JSX
         formatPropertyValueForDisplay
     )
 
+    const isPrevious = !!item.compare && item.compare_label === 'previous'
+    const adjustedIndex = isPrevious ? item.seriesIndex - totalItems / 2 : item.seriesIndex
```
Comment (anirudhpillai) [inline frontend/src/lib/components/InsightLegend/InsightLegendRow.tsx:57]: Am missing why we do `item.seriesIndex - totalItems / 2` for previous?
We already adjust the `baseHex` for previous + if I understand correctly, previous should have the lowest index out of all series items?

Might have missed something

**Review by anirudhpillai — APPROVED** [review]

File: frontend/src/lib/components/InsightLegend/InsightLegendRow.tsx (hunk 1 above)
Comment (thmsobrmlr) [reply frontend/src/lib/components/InsightLegend/InsightLegendRow.tsx:57]: The reason for this is that the previous item should have the same color as the current item. This adjustment will make it have the same index and thus the same color.

The other adjustment on `baseHex` tones down opacity a bit, so that you can distinguish previous and total items.

This is best seen with a single series - notice how both items are the same blue color, just the previous series is a bit lighter:
Screenshot 2024-07-23 at 08 10 51
