### PR TITLE
fix(experiments): better message when results time out

### LINKED ISSUE #24688: A/B test 504 should show an error message
## Bug description

When an experiment fails to load, it shows the default (empty) state. A refresh will solve it, but if you don't know to do that, it looks like the data is just gone.

Adding a message to the page saying the experiment failed to load (and to try again) would be super useful here.

504:

```
https://us.posthog.com/api/projects/1721/experiments/44114/results/
```

image

### Debug info

_No response_

### PR DESCRIPTION
**Pull request by jurajmajerik**
## Problem
Closes https://github.com/PostHog/posthog/issues/24688

## Changes
Show a descriptive empty state when the results calculation times out.

image

## How did you test this code?
👀

### CODE REVIEW

**Review by oliverb123 — APPROVED** [review]

File: frontend/src/scenes/experiments/ExperimentView/components.tsx [hunk 1]
```diff
@@ -274,13 +274,33 @@ export function NoResultsEmptyState(): JSX.Element {
         )
     }
 
-    // Non-400 errors are rendered as plain text
+    if (experimentResultCalculationError?.statusCode === 504) {
```
Comment (neilkakkar) [inline frontend/src/scenes/experiments/ExperimentView/components.tsx:277]: this ought to be any 5XX ?

Comment (jurajmajerik) [reply frontend/src/scenes/experiments/ExperimentView/components.tsx:277]: a timeout should always be 504, to be handled by this specific message

for any other error we have a more generic message down below: `Experiment results could not be calculated`
