### PR TITLE
Fix no funnel time conversion

### LINKED ISSUE #5211: Breakdown on funnel fails to load
## Bug description

Tried to breakdown funnel by browser, country and a few other attributes none return any results, an example: https://app.posthog.com/insights?insight=FUNNELS&properties=%5B%5D&filter_test_accounts=true&interval=day&events=%5B%7B%22id%22%3A%22insight%20loaded%22%2C%22name%22%3A%22insight%20loaded%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%5D&actions=%5B%7B%22id%22%3A2674%2C%22name%22%3A%22User%20Signed%20Up%20(Comprehensive)%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A4912%2C%22name%22%3A%22Discovered%20Learning%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A2%7D%5D&new_entity=%5B%5D&breakdown=%24geoip_country_name&breakdown_type=person&display=FunnelViz

## Expected behavior
Return a breakdown of the funnel based on this property

## How to reproduce

1. https://app.posthog.com/insights?insight=FUNNELS&properties=%5B%5D&filter_test_accounts=true&interval=day&events=%5B%7B%22id%22%3A%22insight%20loaded%22%2C%22name%22%3A%22insight%20loaded%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%5D&actions=%5B%7B%22id%22%3A2674%2C%22name%22%3A%22User%20Signed%20Up%20(Comprehensive)%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A4912%2C%22name%22%3A%22Discovered%20Learning%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A2%7D%5D&new_entity=%5B%5D&breakdown=%24geoip_country_name&breakdown_type=person&display=FunnelViz

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

### PR DESCRIPTION
**Pull request by alexkim205**
## Changes

- Remove duplicate timeConversionBins kea value and always end query

Fixes #5211

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

### CODE REVIEW

File: frontend/src/scenes/funnels/funnelLogic.ts [hunk 1]
```diff
@@ -215,9 +211,7 @@ export const funnelLogic = kea<funnelLogicType>({
 
                         return { results: result.result, timeConversionResults }
                     } catch (e) {
-                        if (!isBreakpoint(e)) {
-                            insightLogic.actions.endQuery(queryId, ViewType.FUNNELS, null, e)
-                        }
+                        insightLogic.actions.endQuery(queryId, ViewType.FUNNELS, null, e)
                         return EMPTY_FUNNEL_RESULTS
```
Comment (alexkim205) [inline frontend/src/scenes/funnels/funnelLogic.ts:215]: Ran into a bug where queries weren't ending for some graph loads. Shouldn't we always end queries on catching errors?

Comment (samwinslow) [reply frontend/src/scenes/funnels/funnelLogic.ts:215]: This will cancel the preceding request if one is active, right? I think that's what we want — always have the latest request's values. Totally different library than Kea, but in Redux-Saga this behavior would be called [takeLatest](https://redux-saga.js.org/docs/advanced/Concurrency/).

**Review by samwinslow — APPROVED** [review]
Looks good to me! I sort of wish there was a more built-in way to run loaders concurrently (rather than having `loadResults` be a gigantic function, and using `Promise.all`) — but the only way I could think of doing that with Kea right now would be a dispatch action and two listeners, which might add some cruft.

File: frontend/src/scenes/funnels/funnelLogic.ts (hunk 1 above)
Comment (alexkim205) [reply frontend/src/scenes/funnels/funnelLogic.ts:215]: That makes a lot of sense. I made this change b/c for some reason the `showTimeoutMessage` var seems to be persisting across sync calls, but I think I should put this back where I found it then.

**Comment by samwinslow** [comment]
Nice catch on putting back the `isBreakpoint` check — just realized that was seeming to cause the visualization to flash "Query took too long to complete" after 1-2 secs

File: frontend/src/scenes/funnels/funnelLogic.ts (hunk 1 above)
Comment (mariusandra) [reply frontend/src/scenes/funnels/funnelLogic.ts]: The breakpoints were actually inspired by `takeLatest` and try to imitate the same feature :). redux-saga offers many more controls though.
