### PR TITLE
Fix Cohort Select width

### LINKED ISSUE #4045: Dropdowns too narrow
## Bug description

Dropdowns seem to open at the width of the previously selected option.

image

## Expected behavior

It would be ideal to decouple the width of the dropdown from the currently-selected option. The expanded dropdown should ideally be the width of the longest option, with a reasonable max-width for edge cases.

## How to reproduce

1. Choose a short math selector
2. Open the dropdown again

## Environment

PostHog Cloud

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Changes

We added a wrapping div in #3957 that didn't set width, so when the cohort `select` was setting `width: 100%`, it was actually referring to a div with a width of 42px.

This fixes that + removes some unnecesssary React fragments.

Closes #4045

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious

### CODE REVIEW

File: frontend/src/lib/components/SelectGradientOverflow.tsx [hunk 1]
```diff
@@ -100,7 +100,7 @@ export function SelectGradientOverflow({
     }
     document.addEventListener('click', outsideClickListener)
     return (
-        <div ref={containerRef}>
+        <div ref={containerRef} style={{ width: '100%' }}>
```
Comment (yakkomajuri) [inline frontend/src/lib/components/SelectGradientOverflow.tsx:103]: This is the relevant change - the other diffs look large but it's just the formatting that changed after removing the fragment

**Review by samwinslow — APPROVED** [review]
LGTM!
