### PR TITLE
Make Jest tests work better with TypeScript

### LINKED ISSUE #2535: Jest path configuration issue
## Bug description

Jest seems to ignore webpack configuration for paths, therefore when running tests with the following import, tests fail.

```typescript
import { lightColors } from 'lib/colors' /* Absolute path: this fails in tests, works at runtime */
```

## Expected behavior

Tests should pass properly.

## How to reproduce

1. Change line 7 on `frontend/src/lib/utils.tsx` to `import { lightColors } from 'lib/colors'`
2. Run tests and see them fail.

## Environment

Development.

## Additional context

Related to #2479.
CC @Twixes

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

[ts-jest](https://github.com/kulshekhar/ts-jest) is a way to make Jest work smoothly with TypeScript. Should resolve #2535.

## Checklist

- [x] Jest frontend tests

### CODE REVIEW

File: frontend/src/lib/utils.tsx [hunk 1]
```diff
@@ -171,20 +171,18 @@ export const selectStyle: Record<string, (base: Partial<CSSProperties>) => Parti
 }
 
 export function debounce(func: (...args: any) => void, wait: number, immediate: boolean, ...args: any): () => void {
-    let timeout: NodeJS.Timeout | undefined
-    return function () {
-        const context = this // eslint-disable-line
-        function later(): void {
+    let timeout: number | undefined
```
Comment (paolodamico) [inline frontend/src/lib/utils.tsx:179]: FYI it seems like we currently don't use this function anywhere, anyways might be a good idea to keep it and add unit tests.

File: frontend/src/lib/utils.tsx [hunk 2]
```diff
@@ -38,16 +38,16 @@ export function toParams(obj: Record<string, any>): string {
...
         ? {}
         : window.location.search
               .slice(1)
               .split('&')
-              .reduce((a, b) => {
-                  b = b.split('=')
-                  a[b[0]] = decodeURIComponent(b[1])
-                  return a
-              }, {})
+              .reduce((paramsObject, paramString) => {
```
Comment (paolodamico) [inline frontend/src/lib/utils.tsx:46]: **Non-blocking.** Maybe worth to using the default logic on kea-router?

**Review by paolodamico — COMMENTED** [review]
A few non-blocking comments in the review. Only thing is I tested the case reported on #2535 and it still throws the exception.

```typescript
import { lightColors } from 'lib/colors' // Line 7 of lib/utils.tsx
```

```
 FAIL  frontend/src/lib/utils.test.ts
  ● Test suite failed to run

    Configuration error:
    
    Could not locate module lib/colors mapped as:
    ./src/lib/$1.
    
    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/^lib\/(.*)$/": "./src/lib/$1"
      },
      "resolver": undefined
    }

       5 | import moment from 'moment'
       6 | import { EventType } from '~/types'
    >  7 | import { lightColors } from 'lib/colors'

```
Also, might be worth for someone with stronger expertise on Jest to take a look, but if we can fix the case described above, IMO it's good to go.

File: frontend/src/lib/utils.tsx (hunk 1 above)
Comment (Twixes) [reply frontend/src/lib/utils.tsx:179]: Ah, right. I removed it then – we use Kea breakpoint for debouncing anyway, and this util was written a bit oddly imo.

File: frontend/src/lib/utils.tsx (hunk 2 above)
Comment (Twixes) [reply frontend/src/lib/utils.tsx:46]: In another PR.

**Comment by Twixes** [comment]
Hm, yes, the problem from #2535 does persist and I honestly have no idea how to fix it. 🤔

**Comment by paolodamico** [comment]
Maybe it's worth merging this PR anyways, though it seems like #2535 is not resolved yet. It's not an issue right now, but it might become an issue later as we start adding more unit tests to files that have absolute imports.

**Comment by Twixes** [comment]
@paolodamico Actually ended up not using ts-jest, but this _seems_ to resolve #2535 nevertheless. 🤔 Take a look please, maybe we can merge.

File: package.json [hunk 3]
```diff
@@ -72,6 +72,7 @@
         "reselect": "^4.0.0",
         "rrweb": "^0.9.11",
         "sass": "^1.26.2",
+        "ts-node": "^9.1.1",
```
Comment (paolodamico) [inline package.json:75]: My only hold-up is why this isn't kept as a dev dependency instead of a regular dependency? Tested locally and everything seems to work as expected too.

**Review by paolodamico — APPROVED** [review]

File: package.json (hunk 3 above)
Comment (Twixes) [reply package.json]: Thanks for catching this! Should've been be a dev dependency
