### PR TITLE
fix(cohort): Duplicating a criteria clears value in other criteria in specific scenarios

### LINKED ISSUE #33813: bug(cohorts): Duplicating a criteria clears value in other criteria
## How to reproduce

1. Create some criteria in a dynamic cohort
2. Try to duplicate a criteria

Expected: The criteria is duplicated and all other criteria retain their values.
Actual: Some other criteria is cleared out. 

Example:

Before:
Image
After:
Image

Here's the filters for the repro cohort:

```json
{
  "properties": {
    "type": "OR",
    "values": [
      {
        "type": "AND",
        "values": [
          {
            "key": "is_owner",
            "type": "person",
            "value": [
              "yes"
            ],
            "negation": false,
            "operator": "exact"
          },
          {
            "key": "org_created_at_timestamp",
            "type": "person",
            "value": "1747673400",
            "negation": false,
            "operator": "gt"
          },
          {
            "key": "id",
            "type": "cohort",
            "value": 15,
            "negation": true
          }
        ]
      }
    ]
  }
}
```

## Additional context

Reported by customer: https://posthoghelp.zendesk.com/agent/tickets/32289

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables or https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

### PR DESCRIPTION
**Pull request by lshaowei18**
> [!IMPORTANT]
> 👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Problem

As described in #33813. This happens when we duplicate a criteria with a cohort/not in cohort criteria below. 

I'm currently not sure of why this is happening, but I noticed that when we duplicate a record in the above scenario, this particular onChange is firing for the duplicated record:

https://github.com/PostHog/posthog/blob/07c13d69feda9b94f05902a6d3dbc232f5af143c/frontend/src/scenes/cohorts/CohortFilters/CohortCriteriaRowBuilder.tsx#L103-L110

My hypothesis is that we start with 2 criteria:

1) Behavioural criteria
2) Cohort criteria

When we duplicate 1), React tries to [reconcile](https://legacy.reactjs.org/docs/reconciliation.html#recursing-on-children), which means that the second component is not remounted; it is updated from `cohort criteria` to `behavioural criteria`, which causes the `onChange` to fire. 

Closes #33813

## Changes

https://github.com/user-attachments/assets/8354c4ca-87b6-427f-af21-d9357a89e45d

The ideal situation should be that when we add or remove items on the list, the items on the list should be remounted. 

Currently, the key used here is an index: 

https://github.com/PostHog/posthog/blob/07c13d69feda9b94f05902a6d3dbc232f5af143c/frontend/src/scenes/cohorts/CohortFilters/CohortCriteriaGroups.tsx#L78

As mentioned in the [docs](https://legacy.reactjs.org/docs/reconciliation.html#recursing-on-children):
> As a last resort, you can pass an item’s index in the array as a key. This can work well if the items are never reordered, but reorders will be slow.

>Reorders can also cause issues with component state when indexes are used as keys. Component instances are updated and reused based on their key. If the key is an index, moving an item changes it. As a result, component state for things like uncontrolled inputs can get mixed up and updated in unexpected ways.

As each criteria does not have a unique key, introduced a new key called `sort_key` that is only for the react component and is not send to the backend.  

 
## Did you write or update any docs for this change?
- [x] No docs needed for this change

## How did you test this code?

Tested locally!

### CODE REVIEW

File: frontend/src/scenes/cohorts/CohortFilters/CohortCriteriaGroups.tsx [hunk 1]
```diff
@@ -74,8 +74,10 @@ export function CohortCriteriaGroups(logicProps: CohortLogicProps): JSX.Element
                         >
                             <>
                                 {group.values.map((criteria, criteriaIndex) => {
+                                    const key =
+                                        criteria.type != null ? `${criteria.type}-${criteriaIndex}` : `${criteriaIndex}`
```
[the remark this answers is not in the document]
Comment (lshaowei18) [reply frontend/src/scenes/cohorts/CohortFilters/CohortCriteriaGroups.tsx]: Hmmmm lmk if there is a more unique that we can fall back to; this is the best i can think of

**Comment by haacked** [comment]
Any key based on the index will be problematic when something changes the order or position of elements (such as duplicating a criteria). You can see what I did in [this PR](https://github.com/PostHog/posthog/pull/33780). I just added a "client-only" key field and used that for the React key. That way, sorting and insertions/deletions are stable.

**Comment by haacked** [comment]
> do you think we should switch to that in this PR as well?

I do. It'll be more robust.

File: frontend/src/models/cohortsModel.ts [hunk 2]
```diff
@@ -40,6 +40,18 @@ export const DEFAULT_COHORT_FILTERS: CohortFilters = {
     page: 1,
 }
 
+export function generateUUID(): string {
```
Comment (lshaowei18) [inline frontend/src/models/cohortsModel.ts]: Thanks @haacked for the suggestion. Do you think we should move this function into `frontend/src/lib/utils`?

Comment (haacked) [reply frontend/src/models/cohortsModel.ts]: Yeah, that makes sense. Then we can delete the one in `frontend/src/scenes/feature-flags/FeatureFlagReleaseConditionsLogic.ts`

**Review by haacked — APPROVED** [review]
Nice work! I'll merge this after you consolidate the `generateUUID` method like we discussed. Thank you!

**Comment by lshaowei18** [comment]
> I pushed a commit to your PR with a fix for the TypeScript errors.

Ah thanks, was going to get to that; will also fix the failing tests.

**Comment by lshaowei18** [comment]
> Nice work! I'll merge this after you consolidate the `generateUUID` method like we discussed. Thank you!

Consolidated, fixed the test as well! Thanks for the recommendation, learned a new technique!
