### PR TITLE
fix(data-m): fix property filter resetting event filter

### LINKED ISSUE #11258: custom event selector changes when changing filter in 'calculated events' creation UI
## Bug description

per title. The filter should not change the existing event, especially when the prop to filter on belongs to only one of the events. If I'm selecting a property that doesn't belong to current event, ui should alert me of that rather than changing the underlying event (not sure that's what's happening here though)

https://posthog.slack.com/files/U02NGDTLPL3/F03TZ8FKYL8/screen_recording_2022-08-11_at_2.14.46_pm.mov

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

### PR DESCRIPTION
**Pull request by alexkim205**
## Problem

https://posthog.slack.com/archives/C02KGGDCA6Q/p1660220258554529

Fixes https://github.com/PostHog/posthog/issues/11258

## Changes

There was a bug where the property filters was reusing a stale logic for filters. Changing the key will refresh the logic with the most current filters.

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

Manually

### CODE REVIEW

File: frontend/src/scenes/actions/ActionEdit.tsx [hunk 1]
```diff
@@ -64,6 +64,8 @@ export function ActionEdit({ action: loadedAction, id, onSave, temporaryToken }:
         </LemonButton>
     )
 
+    console.log('ACTION BLAH', action.steps)
```
Comment (liyiy) [inline frontend/src/scenes/actions/ActionEdit.tsx:67]:
```suggestion
```

**Review by liyiy — APPROVED** [review]
