### PR TITLE
More tests + Rename Modal state refactor

### LINKED ISSUE #6153: Move FilterRenameModal state into separate logic
## Bug description

Tech debt followup from here https://github.com/PostHog/posthog/pull/6063#pullrequestreview-765000965

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

### PR DESCRIPTION
**Pull request by alexkim205**
## Changes

Adds a bunch of tests. Followup for https://github.com/PostHog/posthog/pull/6063#pullrequestreview-765000965

Closes #6153

- [ ] Move local state in RenameModal into separate logic
- [ ] Add test for renameModalLogic
- [ ] Add util tests for insight utils
- [ ] Refactor text selection into separate hook
- [ ] Add modal behavior test in entityFilterLogic
- [ ] Consolidate entity types into EntityFilterTypes

## How did you test this code?

Wrote tests for new and existing logics + utils.

### CODE REVIEW

File: frontend/src/scenes/insights/utils.ts [hunk 1]
```diff
@@ -24,9 +24,8 @@ export const getDisplayNameFromEntityFilter = (
     filter: EntityFilter | ActionFilter | null,
     isCustom = true
 ): string | null => {
-    // Make sure custom name isn't a blank string
+    // Make sure names aren't blank strings
     const customName = (filter?.custom_name ?? '').trim() === '' ? null : filter?.custom_name
-
     const name = (filter?.name ?? '').trim() === '' ? null : filter?.name
```
Comment (pauldambra) [inline frontend/src/scenes/insights/utils.ts:29]: With 28 and 29 being identical _and_ needing a comment I'd be tempted to extract an `ensureStringIsNotBlank` method

Saves a future reader having to grok they're the same bar the input

File: frontend/src/scenes/insights/ActionFilter/RenameModal.tsx [hunk 2]
```diff
@@ -79,3 +64,20 @@ export function FilterRenameModal({ visible, setModalOpen, view }: Props): JSX.E
...
     )
 }
+
+function useSelectAllText(
+    ref: React.MutableRefObject<Input | null>,
+    options: InputFocusOptions,
+    dependencies: any[] = []
+): void {
+    // Hacky setTimeout is needed to select all text on modal open
+    // https://github.com/ant-design/ant-design/issues/8668#issuecomment-352955313
```
Comment (pauldambra) [inline frontend/src/scenes/insights/ActionFilter/RenameModal.tsx:74]: +1 for leaving the context in the comment 🙌

File: frontend/src/scenes/insights/ActionFilter/renameModalLogic.test.ts [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+                pathname
+            )
+        ) {
+            return { results: [] }
+        } else {
+            throw new Error(`Unmocked fetch to: ${pathname} with params: ${JSON.stringify(searchParams)}`)
+        }
+    })
+
+    initKeaTestLogic({
```
[the remark this answers is not in the document]
Comment (pauldambra) [reply frontend/src/scenes/insights/ActionFilter/renameModalLogic.test.ts:35]: are you thinking so that you can mock a dependent logic?

would mocking the module in the test file do it?

File: frontend/src/scenes/insights/utils.test.ts [hunk 4]
```diff
@@ -0,0 +1,32 @@
...
+            [createFilter(3, '', ''), true, '3'],
+            [createFilter(3, '  ', '    '), true, '3'],
+            [createFilter(3), true, '3'],
+            [createFilter('hi'), true, 'hi'],
+            [createFilter(), true, null],
+            [createFilter(3, 'name', 'custom_name'), false, 'name'],
+            [createFilter(3, '  ', 'custom_name'), false, '3'],
+        ]
+
+        paramsToExpected.forEach(([filter, isCustom, expected]) => {
```
Comment (pauldambra) [inline frontend/src/scenes/insights/utils.test.ts:28]: very pedantic nit but you can create the test method inside the forEach so that failures are limited to a single testcase... lets you use a template string to name the test based on the parameters

**Review by pauldambra — APPROVED** [review]

File: frontend/src/scenes/insights/ActionFilter/RenameModal.tsx [hunk 5]
```diff
@@ -1,65 +1,50 @@
...
 import { entityFilterLogic } from 'scenes/insights/ActionFilter/entityFilterLogic'
-import React, { useEffect, useRef, useState } from 'react'
+import React, { useEffect, useRef } from 'react'
 import { EntityFilter, InsightType, ViewType } from '~/types'
 import { Button, Input, Modal } from 'antd'
 import { getDisplayNameFromEntityFilter } from 'scenes/insights/utils'
+import { renameModalLogic } from 'scenes/insights/ActionFilter/renameModalLogic'
+import { InputFocusOptions } from 'antd/es/input/Input'
 
 interface Props {
```
Comment (mariusandra) [inline frontend/src/scenes/insights/ActionFilter/RenameModal.tsx:10]: nit: we usually follow the `ComponentNameProps` pattern here, though doesn't really matter...

File: frontend/src/scenes/insights/ActionFilter/entityFilterLogic.test.ts [hunk 6]
```diff
@@ -55,26 +55,36 @@ describe('entityFilterLogic', () => {
...
+                })
+            )
+        })
+
+        it('close modal after renaming', () => {
+            expectLogic(logic, () => {
+                logic.actions.renameFilter(filterWithCustomName)
             })
-        )
+                .toDispatchActions(['renameFilter', 'setModalVisible'])
```
Comment (mariusandra) [inline frontend/src/scenes/insights/ActionFilter/entityFilterLogic.test.ts:86]: I like to call my actions with slightly more explicit names, such as `showModal`, `hideModal` and avoid the `set*` pattern as much as possible. Making that change would also make it easier to test: 

```ts
.toDispatchActions(['renameFilter', 'hideModal'])
```

However, you can also explicitly test that the modal was hidden with:

```ts
.toDispatchActions(['renameFilter', logic.actionCreators.setModalVisible(false)])
```

File: frontend/src/scenes/insights/ActionFilter/renameModalLogic.test.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (mariusandra) [reply frontend/src/scenes/insights/ActionFilter/renameModalLogic.test.ts:35]: What exactly do you want to mock in/out of the other logic? Nothing exists for this now, though we can always add things. For example, it could be possible to add code that would prevent any listeners running on an adjacent logic, or to make actions do nothing, or ... 

However this is fine as well I think.

File: frontend/src/scenes/insights/ActionFilter/RenameModal.tsx [hunk 7]
```diff
@@ -1,65 +1,50 @@
...
-        }, 0)
-        return () => clearTimeout(autoFocusTimeout)
-    }, [visible])
+    const ref = useRef<Input | null>(null)
+    useSelectAllText(ref, { cursor: 'all' }, [modalVisible])
 
     const onRename = (): void => {
         renameFilter({ ...selectedFilter, custom_name: name } as EntityFilter)
-        setModalOpen(false)
     }
```
Comment (mariusandra) [inline frontend/src/scenes/insights/ActionFilter/RenameModal.tsx:28]: Could any of the logics also call this directly? Because as things stand now, this line is untested.

**Review by mariusandra — DISMISSED** [review]
Some thoughts inline

File: frontend/src/scenes/insights/ActionFilter/RenameModal.tsx (hunk 7 above)
Comment (alexkim205) [reply frontend/src/scenes/insights/ActionFilter/RenameModal.tsx:28]: good catch!

File: frontend/src/scenes/insights/ActionFilter/entityFilterLogic.test.ts (hunk 6 above)
Comment (alexkim205) [reply frontend/src/scenes/insights/ActionFilter/entityFilterLogic.test.ts:86]: Sweet, didn't know I could pass in an actionCreator w/ parameters here as well.

File: frontend/src/scenes/insights/utils.ts (hunk 1 above)
Comment (alexkim205) [reply frontend/src/scenes/insights/utils.ts:29]: good point, I'll move this into a util

File: frontend/src/scenes/insights/utils.test.ts (hunk 4 above)
Comment (alexkim205) [reply frontend/src/scenes/insights/utils.test.ts:28]: that's shwifty

File: frontend/src/scenes/insights/ActionFilter/renameModalLogic.test.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (alexkim205) [reply frontend/src/scenes/insights/ActionFilter/renameModalLogic.test.ts:35]: Sorry I should've clarified more-- I was wondering if there's a way to mock the actions in `entityFilterLogic` that a reducer in `renameModalLogic` depends on. I couldn't get around this without initializing the entire `entityFilterLogic` with props because it was throwing some "accessing {property} of undefined errors". It just seems a little awkward to setup and run logic B code in a logic A test—having a util function that noops on all actions of a mock could be a nice addition to the kea test suite that I can pickup if I have some time. 

For now I'll keep this as it is

**Comment by alexkim205** [comment]
Thank you both for the solid feedback, learned a lot about testing! Will retag @mariusandra for a re-review

File: frontend/src/lib/utils.tsx [hunk 8]
```diff
@@ -1079,3 +1079,7 @@ export function validateJsonFormItem(_: any, value: string): Promise<string | vo
         return Promise.reject('Not valid JSON!')
     }
 }
+
+export function ensureStringIsNotBlank(s?: string | null): string | null {
+    return (s ?? '').trim() === '' ? null : s ?? null
+}
```
Comment (mariusandra) [inline frontend/src/lib/utils.tsx:1085]: Nit/creep: 1) tests? 2) Something like `typeof s === 'string' && s.trim() !== '' ? s : null` seems cleaner and safer

File: frontend/src/scenes/insights/ActionFilter/RenameModal.tsx (hunk 7 above)
Comment (mariusandra) [reply frontend/src/scenes/insights/ActionFilter/RenameModal.tsx:28]: I meant to remove the `renameFilter({ ...selectedFilter, custom_name: name } as EntityFilter)` line actually and move that into a logic, so it could also be tested.

All this data is accessible in a logic, so why should a React component know the inner details of how the filters object works?

**Review by mariusandra — CHANGES_REQUESTED** [review]
One more round :)

File: frontend/src/lib/utils.tsx (hunk 8 above)
Comment (alexkim205) [reply frontend/src/lib/utils.tsx:1085]: 1) ah yes, absolutely 2) changing this too

**Review by mariusandra — APPROVED** [review]
I think it could be possible to also get the `name` in the logic (via `connect` probably), but this already lgtm. Up to you to change it even more or just merge 👍

**Comment by alexkim205** [comment]
Hm, I see what you mean, but think I'll just leave it as is for now because it makes more sense to me that renameFilter explicitly takes in a `name` parameter rather than inferring that value's being pumped in via connected logic.
