### PR TITLE
fix: show only valid property definition fields

### LINKED ISSUE #10408: Bug: First/Last Seen not loading on properties
## Bug description

Me: "Is this worth a bug report?"
Yakko: "Probably."

Screenshot 2022-06-22 at 10 51 03

No first/last seen data loading into property window, even though there are plenty of people attached to this property. 

## How to reproduce

1. Persons
2. Filter, JoinedAt
3. Profit!

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

We show property definitions and events as if they have the same data available. But they don't

We don't have first and last seen at for property definitions, and we deprecated volume for property definitions

## Changes

* Hides first and last seen at, and volume when showing a property definition. 
* Changes `raw event name` to `raw event property name`
* Makes property type visible on the view page for a property definition
* moves property type to the same location in the popup card as in the view page

| before | after|
|-|-|
|Screenshot 2022-09-06 at 11 58 42|Screenshot 2022-09-08 at 10 59 54|
|Screenshot 2022-09-06 at 11 56 06|Screenshot 2022-09-06 at 11 47 07|

## How did you test this code?

with my eyes 👀

### CODE REVIEW

File: frontend/src/scenes/data-management/definition/DefinitionView.tsx [hunk 1]
```diff
@@ -114,14 +114,25 @@ export function DefinitionView(props: DefinitionLogicProps = {}): JSX.Element {
...
+                        {isEvent && (
+                            <DefinitionPopup.Card
+                                title={<ThirtyDayVolumeTitle />}
+                                value={
+                                    definition.volume_30_day == null
+                                        ? '-'
+                                        : humanFriendlyNumber(definition.volume_30_day)
+                                }
+                            />
+                        )}
```
Comment (alexkim205) [inline frontend/src/scenes/data-management/definition/DefinitionView.tsx:135]: Could we place all of these under one conditional?

```
{isEvent && (
    <>
        ...
    </>
)}
```

**Review by alexkim205 — CHANGES_REQUESTED** [review]
Everything looks good except one comment. Also, this is simply the best kind of testing!

**Review by alexkim205 — APPROVED** [review]

**Comment by pauldambra** [comment]
@clarkus does this work for you? 

Longer term it would be great to add these values for properties but need to get celery under control first

**Review by clarkus — APPROVED** [review]
Thanks for working on this. Previous concepts had the property type adjacent to the property name. If we show it in the placement you have now, I'd probably drop the pill / label pattern and show it as simple text. That way it's more aligned with other attributes and has equal priority. Thoughts?

Does this PR also update the detail view for the property? We show the same attributes there.

**Comment by pauldambra** [comment]
@clarkus if detail view is e.g. https://app.posthog.com/data-management/event-properties/01790132-ed31-0000-6a3c-3b28470485fa then yep, that's covered. If I'm missing a view I'll follow up there too!
