### PR TITLE
fix(livestream): Enable custom livestream host (#26106)

### LINKED ISSUE #26106: Live Activity not working on Self-Hosted instance
## Bug description
Live Acitivty page is not working on self-hosted instance.
Frontend tries to fetch `http://localhost:8666/events` and `http://localhost:8666/stats`.

billede

## How to reproduce

1. Navigate to self-hosted live activity page
2. Page shows "Waiting for events…"

## Additional context
Maybe the problem is caused by this code?
https://github.com/PostHog/posthog/blob/d844b47438495358deddbac9cf13006e3fd72f0b/frontend/src/lib/utils/apiHost.ts#L11C17-L11C37

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables or https://eu.posthog.com/settings/project-details#variables]
- [ x ] PostHog Hobby self-hosted with `docker compose`, version/commit: d844b47438495358deddbac9cf13006e3fd72f0b
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

### PR DESCRIPTION
**Pull request by Yiidiir**
## Problem

This is for self-hosted instances, live event features are broken when not running on localhost because of a hard-coded value.

I can also follow up with an updated `docker-compose.hobby.yml` but I feel the ability to set live events host is more important.

Closes #26106 

## Changes

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?
Works for self-hosted / No impact for cloud

## How did you test this code?

1. Build [./Dockerfile](https://github.com/PostHog/posthog/blob/master/Dockerfile)
2. Set `LIVESTREAM_HOST` value to URI of host serving [livestream ](https://github.com/PostHog/posthog/blob/master/livestream/Dockerfile) service
3. Events features in self-hosted posthog start working again

### CODE REVIEW

**Comment by Yiidiir** [comment]
@pauldambra @benjackwhite Can you guys look into this?  I made this change small to make it easy to merge. Thanks

File: frontend/src/lib/utils/apiHost.ts [hunk 1]
```diff
@@ -17,5 +17,5 @@ export function liveEventsHostOrigin(): string | null {
     } else if (appOrigin === 'https://app.dev.posthog.dev') {
         return 'https://live.dev.posthog.dev'
     }
-    return 'http://localhost:8666'
+    return process.env.LIVESTREAM_HOST || 'http://localhost:8666'
```
Comment (benjackwhite) [inline frontend/src/lib/utils/apiHost.ts:20]: Uhhh does this actually work? As far as I am aware the frontend doesn't get any env vars this way.

**Review by benjackwhite — CHANGES_REQUESTED** [review]

File: frontend/src/lib/utils/apiHost.ts (hunk 1 above)
Comment (Yiidiir) [reply frontend/src/lib/utils/apiHost.ts:20]: I didn't want to do any acrobatics here 😅 `process.env.*` seems to be used everywhere eg. [frontend/src/index.tsx](https://github.com/PostHog/posthog/blob/master/frontend/src/index.tsx)

Any alternatives?

Comment (benjackwhite) [reply frontend/src/lib/utils/apiHost.ts:20]: Thats not true. There are only a couple of "magic envs" that come from the compiler such as STORYBOOK and NODE_ENV but envs passed to the docker image definitely aren't passed through, so sadly you would need to go the route of modifying the app context that is a little more involved https://github.com/PostHog/posthog/blob/master/posthog/templates/head.html#L46

**Review by benjackwhite — CHANGES_REQUESTED** [review]

**Comment by Yiidiir** [comment]
image

@fuziontech

**Comment by nightire** [comment]
@Yiidiir I'm curious about what is the value of the env `LIVESTREAM_HOST` by default? Should we setup another domain for it?

**Comment by benjackwhite** [comment]
I'm just gonna approve and merge this as it seems fine to me

**Comment by benjackwhite** [comment]
Sorry for the hold up @Yiidiir 🙌

**Comment by Yiidiir** [comment]
What happened @benjackwhite 😂
