### PR TITLE
Better handling of current project edge cases

### LINKED ISSUE #6896: You can delete your only Project, and then not be able to access the website
## Bug description

In [this conversation (private papercups link)](https://app.papercups.io/share?cid=6f2a0bbd-5e1a-41a3-9e8f-64dd48c187b7&token=SFMyNTY.g2gDaAJtAAAAJDg3M2Y1MTAyLWQyNjctNGIwOS05ZGUwLWQ2ZTc0MWUwZTA3Nm0AAAAkNDAyMjA3OWQtNTc3ZC00N2I3LTlmMmYtYmRlNmRkODdhYzllbgYAoXtz6nwBYgABUYA.VM7Ay_P0bZHgVzwi6nPmHYXOVMXQo1ByYVvhmFGEK3A)  a customer reported that they deleted their only project because they didn't need it any more.

They were expecting to be able to create a new project afterwards

Once they had done that they could no longer visit app.posthog.com. The site would briefly appear and then as API calls failed (because the team ID was not found) the site would white-screen.

It was possible to fix this by throttling the browser so that the API calls took a long time. This allowed a gap where you could click on the project button in the header and create a new project.

## Expected behavior

Either you cannot delete your only project. Or if you do not have a project then we serve a page with appropriate text and let you create a project

## How to reproduce

1. create a user with a single project
2. delete their project
3. refresh the site

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

The user had just paid for PostHog. That might be a necessary step between 1 and 2

### PR DESCRIPTION
**Pull request by Twixes**
## Changes

Resolves #6896 and a few other problems:
- lemonade UI looking awkward when there's no current project and/or when project creation is unavailable for the user
- user that lost their access to the current project not being redirected away
- org/project creation modals not being helpful

## How did you test this code?

Manually by bringing the edge cases described above into the instance.

### CODE REVIEW

File: frontend/src/scenes/App.tsx [hunk 1]
```diff
@@ -67,15 +66,14 @@ export function App(): JSX.Element | null {
     const { showApp, showingDelayedSpinner } = useValues(appLogic)
     const { user } = useValues(userLogic)
     const { currentTeamId } = useValues(teamLogic)
-    const { sceneConfig } = useValues(sceneLogic({ scenes: appScenes }))
```
Comment (mariusandra) [inline frontend/src/scenes/App.tsx:70]: If you don't need the var here, can you replace this with `useMountedLogic(sceneLogic({ scenes }))` instead, as the `<LoadedSceneLogics />` below also uses sceneLogic, before AppScene. It'd be an endless game of cat and mouse, so just `useMountedValues` at the highest level will save the day.

**Review by mariusandra — CHANGES_REQUESTED** [review]
One comment, and there's an infinite loop in jest.

**Comment by Twixes** [comment]
Fixed. Also added some console logging – it generally doesn't make sense in production, but in this case it feels better to have this hint for various debugging purposes (in logic tests but also to know where the redirects are coming from in prod) – though I don't feel strongly about this.

**Review by mariusandra — APPROVED** [review]
