### PR TITLE
fix: Multiselect broken for single mode

### LINKED ISSUE #17450: slack subscription: cannot choose channel
## Bug description

It is not possible right now to create a slack subscription since clicking a channel will result in an error.
Screenshot 2023-09-14 at 17 16 06

## How to reproduce

1. Go to a dashboard
2. Create a subscription -> slack
3. (setup slack app if not already set up)
4. try to select a channel

## Additional context

related ticket: https://posthoghelp.zendesk.com/agent/tickets/5807

### PR DESCRIPTION
**Pull request by benjackwhite**
## Problem

Fixes https://github.com/PostHog/posthog/issues/17450

I think a mixture of multiple changes and forced types led to the single select getting screwed up. Underlying, AntD's poor typing causes the issue

## Changes

* Removes a thing that was added but never used from what I could see
* Fixes the issue 

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

### CODE REVIEW

File: frontend/src/lib/lemon-ui/LemonSelectMultiple/LemonSelectMultiple.tsx [hunk 1]
```diff
@@ -18,20 +18,20 @@ export interface LemonSelectMultipleOptionItem extends LemonSelectMultipleOption
...
     loading?: boolean
     placeholder?: string
     labelInValue?: boolean
-    onChange?: ((newValue: string[]) => void) | ((newValue: LabelInValue[]) => void)
     onSearch?: (value: string) => void
     onFocus?: () => void
     onBlur?: () => void
     filterOption?: boolean
     mode?: 'single' | 'multiple' | 'multiple-custom'
+    onChange?: ((newValue: string) => void) | ((newValue: string[]) => void)
```
Comment (pauldambra) [inline frontend/src/lib/lemon-ui/LemonSelectMultiple/LemonSelectMultiple.tsx:34]: below we say `const typedOnChange = onChange as (newValue: string | null) => void` should this be `((newValue: string) => void) | ((newValue: string[]) => void) | ((newValue: null) => void)`?

(I have lazily only read the code in the diff 🙈)
