### PR TITLE
fix: have a single edit mode on insights page

### LINKED ISSUE #11551: Having to save title changes as well as insight changes can be confusing
## Bug description

https://posthogusers.slack.com/archives/CTLTM70RM/p1661521059037479

i often add a title in here, forget to press save on the title, then save the insight itself. And then end up with strange names. I'd expect that when i type into the title box, clicking anywhere else on the screen is same as clicking save.
having to save the title name and then save the insight sometimes is strange.

image

## How to reproduce

1.
2.
3.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

### PR DESCRIPTION
**Pull request by pauldambra**
## Problem

closes #11551 

You can get up to three save and cancel buttons visible in the insight page

Screenshot 2022-08-31 at 11 31 46

too-damn-high.meme

## Changes

In insight view mode you can edit the title or description as currently.

In edit mode the one set of save and cancel buttons controls whether we save the changes being made.

And adds story to explain the possible modes (which took my a minute to understand by finding the actual implementations)

Screenshot 2022-08-31 at 11 35 04

## How did you test this code?

running it locally and seeing it work when editing an insight

### CODE REVIEW

File: frontend/src/lib/components/EditableField/EditableField.tsx [hunk 1]
```diff
@@ -134,6 +145,15 @@ export function EditableField({
                                         onChange?.(e.target.value)
                                         setTentativeValue(e.target.value)
                                     }}
+                                    onBlur={
```
Comment (Twixes) [inline frontend/src/lib/components/EditableField/EditableField.tsx:148]: This would address the user's direct issue, but it seems like quite unexpected behavior though – I wouldn't expect the new name to auto-save if I accidentally clicked outside of the text box. It seems the most intuitive thing would be if clicking "Save" on the insight also saved the tentative `EditableField` value, though that would require some complex `ref`s. Or… the field wouldn't have cancel/save in edit mode – then it'd get saved/canceled same way as all the rest of an insight.

Comment (pauldambra) [reply frontend/src/lib/components/EditableField/EditableField.tsx]: Less lazy version proposed :)

Comment (Twixes) [reply frontend/src/lib/components/EditableField/EditableField.tsx]: This is a great approach but there's a problem we've brought onto ourselves: Because so many things rely on the whole `insight` reducer from `insightLogic`, every time `insight` changes EVERYTHING on the insight page re-renders, which is why fast typing results in huge lags:



Ideally we should reduce the reliance of the code on `insight`, because it's very rare that a single component cares about (for instance) both the name and calculation results. I'm not sure what the quick fix is (bearing in mind that we don't want `insightLogic` to be tangled further).

**Review by Twixes — CHANGES_REQUESTED** [review]
Looks great, but we need to make this fasta

**Comment by pauldambra** [comment]
a wild debounce appears

File: frontend/src/scenes/insights/Insight.tsx [hunk 2]
```diff
@@ -84,6 +85,12 @@ export function Insight({ insightId }: { insightId: InsightShortId | 'new' }): J
         return <InsightSkeleton />
     }
 
+    const debouncedOnChange = useDebouncedCallback((insightMetadata) => {
+        if (canEditInsight && insightMode === ItemMode.Edit) {
```
Comment (Twixes) [inline frontend/src/scenes/insights/Insight.tsx]: Is there a situation where `canEditInsight` is false but `insightMode` is `ItemMode.Edit`? I think this should be handled at logic level. For now I removed `canEditInsight` here as I pushed a fix to annoying autofocus relying on `insightMode`.

**Review by Twixes — APPROVED** [review]
I thought about debouncing too, but was worried it might have an impact on the experience. Turns out it works great! Nice
